### ISSUE TITLE
[4.74.3] Signal crashes when trying to setup chat backups (UnsupportedOperationException from TypedArray.getColor())

### ISSUE THREAD

**Issue by danmcgoo** [signalapp/Signal-Android#10131]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal 4.74.3 crashes every time I try to Signal Settings > Chats and media > Chat backups.
The crash seems to be due to an UnsupportedOperationException from TypedArray.getColor().

### Steps to reproduce
- Open Signal
- Go to Signal Settings > Chats and media > Chat backups

**Actual result:** Signal crashes.
**Expected result:** Signal should not crash

### Screenshots
![Screenshot_2020-10-25-22-51-41](https://user-images.githubusercontent.com/777129/97120131-628b9900-1715-11eb-9455-e410422be2a1.png)

### Device info
**Device:** Samsung Galaxy SIII
**Android version:** 4.4.4
**Signal version:** 4.74.3

### Link to debug log
https://debuglogs.org/95b42adf53bc28b9a7177e67fedc3197d9f18d949ee2ed75c038d0ce589fa622

**Comment by danmcgoo** [comment]
I am currently switching to a new phone.
So, it would be very helpful to have this issue fixed as soon as possible.

**Comment by cody-signal** [comment]
@danmcgoo This should be fixed in 4.75 and has started rolling out to production. If you'd like it sooner, you can join the beta group via the play store page listing or going here: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-75-release/17727

**Comment by danmcgoo** [comment]
@cody-signal Thank you for your quick answer and for your responsiveness. That's a huge relief for me.

**Comment by danmcgoo** [comment]
@cody-signal I just finished the transfer from my old to my new phone. Thank you again.

**Comment by mmsenxxx** [comment]
Issues persists with version 4.78.5 and was present in version 4.77.5. Android 10 (Lineageos 17.1 and MicroG)

settings > chats and media > chat backups > turn on > choose folder  = 'Signal keeps stopping'

**Comment by greyson-signal** [comment]
@mmsenxxx Can you please post a log?

**Comment by socialsciencesoftware** [comment]
The issue was resolved once I re-enabled my stock file picker app (Files in my case).

**Comment by Talw3g** [comment]
> 
> 
> The issue was resolved once I re-enabled my stock file picker app (Files in my case).

I am running LineageOS 17.1, and I can't seem to find any stock file picker app... When I try using "Files", it says "The file manager provided by your phone is not available".
That might explain the issue with Signal, but I'm still stuck :(

**Comment by greyson-signal** [comment]
If you're still getting crashes (instead of a prompt saying that there's no file manager available), please post a log. 

As far as lineage not providing a default file manager... not sure what to do that. Seems to be a gap in lineage. Android OS's are supposed to have some file manager as part of the whole Storage Access Framework thing. It's the only way we can get permission to write data to a directory.

**Comment by Talw3g** [comment]
Thanks for your quick reply!
You'll find the log here: [logcat.txt](https://github.com/signalapp/Signal-Android/files/5766419/logcat.txt)

The "choose folder" button in Signal was hit at 20:17:00, and I tried to include every useful log lines after this timestamp.

**Comment by greyson-signal** [comment]
Thanks! Relevant part:

```java
01-04 20:17:00.284 10084 10084 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5210)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:796)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.BackupDialog.lambda$showChooseBackupLocationDialog$5(BackupDialog.java:129)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.-$$Lambda$BackupDialog$Q7E-ezTwyVjjHQAJj-rXu7j-Aug.onClick(Unknown Source:4)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-04 20:17:00.284 10084 10084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```
