### ISSUE TITLE
Pictures taken in portrait mode will be rotated in the Signal gallery

### ISSUE THREAD

**Issue by Rouzax** [signalapp/Signal-Android#10493]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Pictures taken in portrait mode will be rotated in the Signal gallery, I have screen rotation enabled, so it is not similar to the other bugs.

### Steps to reproduce
- Take picture in Portrait mode with Samsung Galaxy S10SE with main rear camera
- Picture will appear correct in Google Photos and Samsung Gallery
- Picture is rotated in Signal gallery

**Actual result:** Pictures taken in portrait mode will be rotated in the Signal gallery
**Expected result:** Pictures should have right orientation

### Screenshots
Original photo
![20210111_143903](https://user-images.githubusercontent.com/4103090/104190990-341c8080-541d-11eb-9708-7e350d6e5cc6.jpg)

Exif Info
<details>
```
ExifTool Version Number         : 12.14
File Name                       : 20210111_143903.jpg
Directory                       : C:/Temp
File Size                       : 82 KiB
File Modification Date/Time     : 2021:01:11 14:40:46+01:00
File Access Date/Time           : 2021:01:11 14:49:46+01:00
File Creation Date/Time         : 2021:01:11 14:40:46+01:00
File Permissions                : rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : samsung
Camera Model Name               : SM-G970F
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : G970FXXS9DTK9
Modify Date                     : 2021:01:11 14:39:03
Y Cb Cr Positioning             : Centered
Exposure Time                   : 1/50
F Number                        : 1.5
Exposure Program                : Program AE
ISO                             : 400
Exif Version                    : 0220
Date/Time Original              : 2021:01:11 14:39:03
Create Date                     : 2021:01:11 14:39:03
Shutter Speed Value             : 1
Aperture Value                  : 1.5
Exposure Compensation           : 0
Max Aperture Value              : 2.4
Metering Mode                   : Center-weighted average
Flash                           : No Flash
Focal Length                    : 4.3 mm
Color Space                     : sRGB
Exif Image Width                : 1276
Exif Image Height               : 2268
Exposure Mode                   : Auto
White Balance                   : Auto
Digital Zoom Ratio              : 1
Focal Length In 35mm Format     : 26 mm
Scene Capture Type              : Standard
Image Unique ID                 : 758f17a9c43ca6650000000000000000
GPS Version ID                  : 2.2.0.0
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Altitude Ref                : Above Sea Level
Compression                     : JPEG (old-style)
Thumbnail Offset                : 908
Thumbnail Length                : 2718
Image Width                     : 1276
Image Height                    : 2268
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 1.5
Image Size                      : 1276x2268
Megapixels                      : 2.9
Scale Factor To 35 mm Equivalent: 6.0
Shutter Speed                   : 1/50
Thumbnail Image                 : (Binary data 2718 bytes, use -b option to extract)
GPS Latitude                    : 
GPS Longitude                   : 
Circle Of Confusion             : 0.005 mm
Field Of View                   : 69.4 deg
Focal Length                    : 4.3 mm (35 mm equivalent: 26.0 mm)
GPS Position                    : 
Hyperfocal Distance             : 2.49 m
Light Value                     : 4.8
```
</details>

Screenshot from Google Photos
![TMrtksQWEi](https://user-images.githubusercontent.com/4103090/104191128-6332f200-541d-11eb-95f2-94b73789c236.png)

Screenshot from Signal gallery
![image](https://user-images.githubusercontent.com/4103090/104191252-91183680-541d-11eb-81ce-b18730efec90.png)

### Device info

**Device:** Samsung Galaxy S10se (SM-G970F)
**Android version:** 10
**Signal version:** 5.0.8

**Comment by schmeat** [comment]
Accidentally made a duplicate entry: https://github.com/signalapp/Signal-Android/issues/10516

**Comment by Rouzax** [comment]
That could very well be my issue as well. 
My phone also stores them as HEIC.

**Comment by deltaclock** [comment]
Same issue here for Samsung Galaxy S20FE.
Pictures are rotated 90 degrees, removing the exif orientation tag had no effect.

I attach below the original heic image and some screenshots of how its shown in Signal.
[image.heic.zip](https://github.com/signalapp/Signal-Android/files/6206234/image.heic.zip)

![Screenshot_20210325-181056_Signal](https://user-images.githubusercontent.com/24370162/112506045-4a33af00-8d85-11eb-9fd0-8f1c8a484637.png)

![Screenshot_20210325-181100_Signal](https://user-images.githubusercontent.com/24370162/112506053-4b64dc00-8d85-11eb-8ab9-2379a7994778.png)

**Comment by deltaclock** [comment]
Did some digging and saw Glide is being used to convert the heic image to jpeg [here](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/util/ImageCompressionUtil.java#L57).

Based on the thread issue on Glide github [here](https://github.com/bumptech/glide/issues/4283#issuecomment-752534279) i suggest maybe to fix this issue, we need to update exifinterface to the latest version or update glide to version 4.12.

Change [here](https://github.com/signalapp/Signal-Android/blob/master/app/build.gradle#L324) and [here](https://github.com/signalapp/Signal-Android/blob/master/app/build.gradle#L374)

**Comment by schmeat** [comment]
Yes this is an issue still. I suppose dev priorities are the only blocker.

**Comment by NickEckardt** [comment]
I am also experiencing this issue on the galaxy S22.

**Comment by liesnikov** [comment]
Not sure if the cause is the same, but attaching two HEIC pictures in a row is also problematic.

1. It takes a ridiculously long time (>10s) to show up in a "pre-send" edit gallery.
2. When it does, the rotation behaviour is wrong -- the picture is placed on a black background with the original (I think?) pic ratio.

**Comment by VadimMuhtarov** [comment]
Same issue on my Galaxy A70, Android 11, Signal 5.34.10

**Comment by joomkra** [comment]
1,5 year pass and this doesn't seem to have been seen by the devs. 
Sending emails to support also get ignored.
My photos on my S21 are always sideways or upside-down.
Signal is the only app having this issue.

**Comment by UserX404** [comment]
Correlating dev comment:
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-40-release/44641/54

**Comment by captainR0bbo** [comment]
Keeping issue alive. Confirmed issue on galaxy S22. No issue on iOS with heic

**Comment by VadimMuhtarov** [comment]
Can't reproduce it now, looks like it was fixed

**Comment by alex-signal** [comment]
@VadimMuhtarov Are you on the newest beta? (5.49)

**Comment by VadimMuhtarov** [comment]
No, production build 5.48.3

**Comment by Reeceeboii** [comment]
Still experiencing this on Android Signal v7.62.0. Images taken in portrait mode as HEICs are auto rotated to be incorrectly landscape when I send them. Samsung S25 Ultra.
