### ISSUE TITLE
Inconsistent proximiy sensor

### ISSUE THREAD

**Issue by lnwor** [signalapp/Signal-Android#10908]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I saw similar issues but they're not the same that I'm experiencing. When I try to listen to a voice message and I bring my phone close to the ear the screen should turn off and the message should play on the ear speaker, but this happens only sometimes. Sometimes when I bing the phone to my ear the sound still plays from the media speaker, sometimes it plays from the ear speaker but the screen doesn't turn off. Sometimes it works more or less as intended.
In whatsapp or telegram when I play a voice message a light blinks near my front camera, meaning the proximity sensor is active, and when I bring my phone close to my ear the screen instantly turns off and the sounds plays from the ear speaker. This is the way it should work and it has always worked perfectly in those apps. In signal the blinking light doesn't appear at all.

### Steps to reproduce
- Press the play button to start playing a voice message
- Bring the phone close to the ear
- See what happens

**Actual result:** When I play a voice message and I bring my phone close to my ear the sound still playes from the media speakers. Other times it plays from the ear speakers but the screen doesn't turn off, accepting as input the touch of my face on the screen. When it works it's not as fast and precise as others instant messaging apps
**Expected result:** When I play a voice message and I bring my phone close to my ear the screen should immediately turn off and the sound should play only from the ear speakers.

### Device info

**Device:** Samsung Galaxy S10
**Android version:** Android 11
**Signal version:** 5.3.7.1

### Link to debug log

https://debuglogs.org/3a548d8562d54f5261eef565808e287daa0b47fe5d09e5706c3ce667a12d973d

**Comment by slugger7** [comment]
I am having this same issue on a OnePlus 6T, Android 10, Signal 5.4.7

**Comment by andradei** [comment]
Same issue
OnePlus Nord N10
version 5.4.12

**Comment by f0lg0** [comment]
same issue on a Samsung Galaxy A51 with latest signal build (5.24.7)

**Comment by lnwor** [comment]
it's fixed now

**Comment by f0lg0** [comment]
> it's fixed now

in which version is it fixed?

**Comment by lnwor** [comment]
I don't know precisely, I didn't check each version. I'm on 5.30.1 now and it works as it should

**Comment by f0lg0** [comment]
> I don't know precisely, I didn't check each version. I'm on 5.30.1 now and it works as it should

I'm on 5.28.10 and the bug is still there. My situation is closer to issue #7576 but the two are kinda related. I'll wait for the 5.30...

**Comment by f0lg0** [comment]
> > I don't know precisely, I didn't check each version. I'm on 5.30.1 now and it works as it should
> 
> I'm on 5.28.10 and the bug is still there. My situation is closer to issue #7576 but the two are kinda related. A lot of people are experiencing this, I wonder why it doesn't get much attention. I'll wait for the 5.30 update, in the meantime I'll be available for clarifications. 

Update on the situation: I'm on 5.30.6 and the bug is still there... #7576 is pretty inactive, hopefully this gets more attention.

**Comment by cody-signal** [comment]
We're tracking this internally. Hope to have a fix soon, but don't know when for sure.

**Comment by cody-signal** [comment]
Closing as duplicate of https://github.com/signalapp/Signal-Android/issues/7576
