### ISSUE TITLE
Image sending - black

### ISSUE THREAD

**Issue by snajlcz** [signalapp/Signal-Android#11014]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While opening image folders show Black thumb and after open any photo samé Black view

### Steps to reproduce
- opening any contacts and send random image

### Screenshots
![Screenshot_20210222_110912_org thoughtcrime securesms](https://user-images.githubusercontent.com/548866/108694283-23bcf280-74ff-11eb-808c-430c2a29dcaf.jpg)

### Device info

**Device:** Huawei p30 Pro 
**Android version:** 10.1.
**Signal version:** 5.4.7 (79302)

### Link to debug log
https://debuglogs.org/4d1306c33277bd95af4345c466f1a5e2ca76627ccaa64ee41b2b2f2e66104163

**Comment by hiqua** [comment]
What happens if you try to send these black images (you can send to "Notes to self")?

I tried (I also have black images like you) and it results in a crash (FileNotFoundException in EncryptedCacheDecoder):

https://debuglogs.org/3ac16ed73cda045873c6f58c9a784752a751c8f6ec7e0628d231507fe674ea91

**Comment by aeturnum** [comment]
I have a very similar situation with my signal. Here's what I've found:

- Can be resolved by opening google photos and 'sharing' a photo to signal.
- Sometimes signal will load thumbnails if I wait long enough.
- If I can see a thumbnail, it will send fine.
- If I can't see a thumbnail, it will send forever until I close signal (I haven't had it crash trying yet)

**Comment by fatpat** [comment]
try https://github.com/signalapp/Signal-Android/pull/11016

on my P30 pro I had similar issues, since I added this patch, the problem is also gone. Not sure how it's related.

**Comment by phil8900** [comment]
I have the exact same issue since I started using Signal like a month ago and it is blocking me from really using it.

**Device info**
Samsung Galaxy S5 DuoS (SM-G900FD)
Signal 5.4.7 (793, 79301)
Android 10 (lineage_klteduos 10 QQ3A.200805.001)

**Link to debug log**
https://debuglogs.org/ae72d0a95f011cb8f3e013555eddc0de2648fd7725f428c0e536bab6cbce3d50?fbclid=IwAR11K2LahlVypRS-W9g0v72qoBnSPozIHyRrxT1jvd890Njp8G5Dg_5ol2k

**Comment by snajlcz** [comment]
> try #11016
> 
> on my P30 pro I had similar issues, since I added this patch, the problem is also gone. Not sure how it's related.

this isnt fix, i now tested, and same problem.

**Comment by fatpat** [comment]
> > try #11016
> > on my P30 pro I had similar issues, since I added this patch, the problem is also gone. Not sure how it's related.
> 
> this isnt fix, i now tested, and same problem.

ok, sorry, at least you tried it :-/

**Comment by snajlcz** [comment]
On update emui 11 problem solved
P30pro

**Comment by cfe84** [comment]
> On update emui 11 problem solved
> P30pro

That's interesting. I have the exact same issue on a Samsung Galaxy S9, I'm wondering what the source of the problem is

**Comment by phil8900** [comment]
I can verify that the problem persists on my Galaxy S5 DUOS with Signal 5.4.12.

https://debuglogs.org/4fc22ac935aeeec679f3fc568759a8591f62ef63ac04cc72fd0dc8c236939582?fbclid=IwAR382RhsxmJ2BmpkmUJB0tTanSOqAy-3CZGAw2U8AFMdx5wqtz7xO7A4zBk

**Comment by aeturnum** [comment]
This problem has become less severe recently (the gallery is no longer all black, but it's common for the last few photos to be unloaded black squares for a while).

https://debuglogs.org/68fab74e489f19fe211f9ecfa1f6f30964b11d5e1d720c17213b91ca3c39eee3

**Comment by clampak** [comment]
> That's interesting. I have the exact same issue on a Samsung Galaxy S9, I'm wondering what the source of the problem is. I have noticed another problem - when sharing a picture or video from another app (gallery, ...), the spinner shows for 30s to a minute before I can select a contact to send the picture to. This doesn't do the same on my wife's phone (Galaxy A8).
> 
> What's more, waiting sometimes brings some thumbnails, however scrolling down then back up makes them disappear and re-appear randomly.

The same happens on my Galaxy S9, though the spinner doesn't show for all that long.  This black thumbnail is a new issue as of a month or two now, it never used to do it.  Very frustrating.

**Comment by q2apro** [comment]
Same here on Honor View 20.

And multiple other phones. See also Reddit thread: https://www.reddit.com/r/signal/comments/kk1qka/black_ghost_images_after_moving_files/

Please try to fix this. This bug should have high priority.

**Comment by clampak** [comment]
I just updated my Galaxy S9 from Android 10 update 29 to update 30, and the issue is gone.  

So, Baseband version G960USQS9FUB2.  

Hope this helps some folks.

**Comment by UserX404** [comment]
This issue seems to be already monitored https://github.com/signalapp/Signal-Android/issues/11074 and a possible fix for this has already be found for the [image library](https://github.com/bumptech/glide/commit/042f6b57d511c9d1652d280f5d385d5fef071647).

It seems we has to wait for the next glide release.

**Comment by varac** [comment]
Similar issue:  #11212 

Possible workaround: Reducing the picture size for new pictures taken with the camera app down to 2.1 megapixel "fixed" it for me (although this is just a temporary stop-gap measure until this gets fixed properly).

**Comment by phil8900** [comment]
Updating to Lineage 18.1 solved the issue for me!

**Comment by varac** [comment]
> Updating to Lineage 18.1 solved the issue for me!

Not for me, I'm on Lineage 18.1 and Pictures >2.1 megapixel still show up black when selecting from the gallery.

**Comment by mklilley** [comment]
I have this problem on Oneplus 5, Android 10, OxygenOS 10.0.1. I am using Signal version 5.21.5. I find the black thumbnail problem is sporadic and have not managed to identify what causes it and when. The only fix I find when it happens is to restart my phone. This does seem to have been going on for a while.

**Comment by ErikSkinnari** [comment]
For me it has been fixed. @mklilley 
Do not see any black thumbnails anymore. 

But I do get some random blur/color overlay on parts of the image thumbnails in the chat on images I have sent. But if I click the image it is shown correctly.

**Comment by irisv** [comment]
I'm still experiencing this issue.
Motorola One, android 10, Signal 5.40.4
Sometimes sharing from another app works, but often even with that workaround pics are never sent.

**Comment by cody-signal** [comment]
What are the file types of the images you are trying to preview?

**Comment by irisv** [comment]
> What are the file types of the images you are trying to preview?

The screenshot I attached is from the Camera folder, ie the photos taken with my phone's camera; those are jpg with the occasional mp4 video (like the second item on the fifth row of the screenshot, marked with the triangular video icon).
But if I access, for example, the download folder, there are more mixed files, but again the same black thumbnails. My phone saves screenshots like the one above as png, and again, black thumbnails.

But just as the OP, I do get one or two thumbnails occasionally. It doesn't seem linked to a specific file type. My impression is that Signal tries to create thumbnails for a fraction of a second, stops well before that process is anywhere near done, and any images that aren't covered in that time, are never attempted again.

**Comment by cody-signal** [comment]
Thanks for the extra details. Android and HEIC have historically not gotten along so wanted to check. Can you provide an updated debuglog after viewing the gallery?

**Comment by irisv** [comment]
Thanks for picking this up.

Here's what I did: I force closed Signal, cleared the cache, opened the app, went to the Note to self conversation, hit the blue + button, then gallery, then Camera -- which gave me all black thumbnails, I selected the first image and tried to send it, let Signal work on that for a minute or two, lost patience and backed out to go get the log. 

It's here:

https://debuglogs.org/android/5.40.4/57b6f3baae397a9e8652b64c2e0394a54ebc769c0599b4d3aae357c06e88af7f

Hope that helps!

**Comment by greyson-signal** [comment]
@irisv For context, your log is filled with a lot of this:

```java
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder          Failed to load media.
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AutoCloseInputStream->Object->Drawable}, LOCAL
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder              Cause (1 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->APNGDecoder->Drawable}
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder              Cause (2 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->GifDrawable->Drawable}
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder              Cause (3 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->Bitmap->Drawable}
[5.40.4] [main ] 2022-06-13 17:42:27.317 GMT+02:00 W FileViewHolder              Cause (4 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->BitmapDrawable->Drawable}
```

Which is to say that Glide has no idea how to load the media file. We'll think on this and see if there's any other debuginfo we could get. In the meantime, if one of these files are shareable, it'd be cool to get a copy of one to see if we can reproduce. You can email it to greyson@signal.org. Thanks!

**Comment by Hnasar** [comment]
I've also had this issue for years:

https://debuglogs.org/android/5.41.10/4aaccc99d996ebd47ed2045eb19849a48519cac7a3a4e707f01a55a65fa2aff6

**Comment by irisv** [comment]
Bump!

**Comment by alex-signal** [comment]
If people are still experiencing this on newer versions of Signal, please include new logs. Our logs expire after 30 days or so, and fresh logs can help give us a bigger picture of what is  happening and help diagnose the issue. There are some relevant open tickets on Glide, so I'm not currently convinced that this is solvable on our part (without updating some dependencies.)

Our Glide version is 4.11, and the newest is 4.13. However, reading through glide issues it seems 4.12 introduced some broken behavior. Our exifinterface dependency is also quite out of date (1.0.0 vs 1.3.3) so once I have a chance to talk to the guys about why these haven't moved, I'll see about updating these dependencies for the next beta, and we'll see if we can't see some movement here.

**Comment by irisv** [comment]
Yup, still experiencing the same issue: 
![Screenshot_20220831-145047](https://user-images.githubusercontent.com/12911799/187683302-e7804ef4-17fe-4349-bf33-f4a2cb009701.png)

Here's my log : https://debuglogs.org/android/5.47.3/94e788fdcbec11ab120a72e73a64b9d75c4403b3a4d069e2f216b855d3f78228

**Comment by UserX404** [comment]
potential fixed with https://github.com/signalapp/Signal-Android/commit/4baa7527f71fb0e307fb4322863233e5bbeba7be

**Comment by alex-signal** [comment]
Definitely please let me know if there are any changes here with that update.

**Comment by irisv** [comment]
> Definitely please let me know if there are any changes here with that update.

Will do! I've rejoined the beta -- or is it better to wait for the main release?

**Comment by alex-signal** [comment]
@irisv Up to you, the beta is a beta, so there is an acknowledgement that there will be bugs and other issues that don't normally make it through to a production release.

**Comment by irisv** [comment]
The app now reports version 5.49.1 and the issue persists.

https://debuglogs.org/android/5.49.1/01b38437efd397cc0d080f5eb95874965e827add5fc729df23f5fde29294cb0f

**Comment by alex-signal** [comment]
@irisv Thanks! Do you mind providing your phone model? I see it's a Motorola One but I see there are multiple phones with that name. Might be time for me to order a test device.

Can other folks please comment which device this is occurring on? I'll see if I can't reproduce it somehow, ideally with a device I already have access to.

**Comment by irisv** [comment]
Mine's a Motorola One XT1941-4. I believe it was one of the earliest Android One phones by Motorola. It's not rooted but I do have developer options turned on. Android build is on QPKS30.54-22-27.

**Comment by Fishermanjb** [comment]
Having thebsame problem on a Galaxy A53, Model number SM-A536B/DS

**Comment by fatpat** [comment]
Same here with a huawei P30 pro and a P30 also.

It's the same for at least 2 years

**Comment by BenBen244** [comment]
Same problem here - its a Google Pixel 7 pro. I couldn't find a way to add pictures to Signal from the phones gallery. I see only the black thumbnails as well. Since this problem is 2 years old I guess we can expect this wont get fixed.

**Comment by irisv** [comment]
> We rely on the [Glide image library](https://github.com/bumptech/glide) to populate this images. Glide can have issues with unusual or newer image formats, such as HEIF or DNG. We adopt new versions of Glide as they are released.

That's not the whole issue though. [As stated above](https://github.com/signalapp/Signal-Android/issues/11014#issuecomment-1152872339), I'm experiencing this issue with .jpg photos and .mp4 videos taken with my phone's camera, and .png screenshots. Those formats aren't unusual or new.

Also, sometimes I get to see some thumbnails, sometimes none at all. Thumbs I've seen before might be gone the next time and vice versa. This would suggest the file or format isn't the issue.

**Comment by BenBen244** [comment]
> 

Some more hints: in my case Signal shows <everything> in the gallery that was created in the last years up to end of December 2022. But from later created pictures maybe just 10% is shown. I dont think its about the file type. As an example: in the "OpenCamera" folder all pictures have the same type, but just 10% have a thumbnail, all other are just black. (I scratch my head, but I'm not sure: potentially the pictures are shown that I edited and saved again after I took them).

**Comment by fatpat** [comment]
same here, to me this is not related to the file type.

maybe this is related to the number of photos to load ...

**Comment by joshyy1312** [comment]
It seems related to filesize, but not only to that.

I had a 6.2mb png that didn't show and appeared instantly when converted to a 1.08mb jpeg.

Other png's from the same batch I copied to the phone showed, but only those under 4.5mb.

I previously copied pngs of more than 6mb and had no problems...

**Comment by cf216** [comment]
Problem persists for HEIC but not JPG with S24 (SM-S921B) running newest version of vendor's Android 14, and SIGNAL 7.10.3. Any news?

**Comment by saphieron** [comment]
On 7.19.2 the same issue is still the case, for a 7.12MB .png file.

**Comment by greyson-signal** [comment]
My understanding is that at least _some_ of the issues people are experiencing are due to this bug:
https://github.com/bumptech/glide/issues/4517

Not sure yet if we can use the glide plugin system to replace the bad component.

**Comment by dirkblaster** [comment]
Disappointed to see this issue has been open so long with so many reports but without resolution. 

Encountering this bug on a new Samsung Galaxy S25 (SM-S931B) on Android 15/OneUI 7.0 running Signal 7.34.2. Random .heic pictures are refusing to load thumbnails or send. If I convert the pictures to JPG they are fine. Luckily there is a workaround within the Gallery app to convert to JPG when sharing, but I cannot browse and attach within Signal anymore, which is annoying. 

Interestingly, my old S21 (SM-G991B) on Android 14/OneUI 6.1 running Signal 7.31.1 never had these issues and the images that were imported from this phone onto the S25 which are also .heic all load correctly, 

As soon as I started taking photos on the new S25 the issue appears to have manifested??

**Comment by greyson-signal** [comment]
@andrewjunggg You're running into https://github.com/bumptech/glide/issues/4517

@dirkblaster until there's some way to workaround these issues with our image library, it's unclear what the best strategy is. Also, I've enabled HEIC photos on my S24 and haven't been able to reproduce the issue yet.

**Comment by mklilley** [comment]
I've most often had this issue when connected to Wifi. When I switch Wifi off and go to 4G data the problem often goes away. I don't know how that relates to the glide issue but I thought I'd chime in because it seems like there are some issues reproducing this issue.

**Comment by dirkblaster** [comment]
Thank you, I really appreciate the update and can't wait to see this fix get pushed out. 

I looked at the bug ticket you opened for Glide in 2021, is there any likelihood they will ultimately fix this?

**Comment by greyson-signal** [comment]
Tbh, not a trivial problem for them to solve. They've sort of backed themselves into a corner with the InputStream interface they've provided, since they'll need some max buffer. I think if the fix is gonna come from anywhere, it may have to be from us, where we provide alternate image loaders.

**Comment by dirkblaster** [comment]
Thanks, fingers crossed I guess! Will wait for your latest fix that you mentioned to make it to the Play Store.

I saw in the glide ticket there was a proposed hotfix in Nov 2022 (https://github.com/bumptech/glide/pull/4946) that never went anywhere, but wasn't sure if was technically sound? Does someone else with CLA approval need to just resubmit it for review?

**Comment by panagiotis94** [comment]
> The issue doesn't appear to be dependent on HEIC's, nor does it necessarily affect all HEIC's. It affects any image that is very large (i.e. > 5MiB) with a certain file structure.
> 
> It all has to do with Glide choking on these types of images when the data source is an InputStream. I was able to fix the image selection screen in the latest release by not using an InputStream, but now those images will just fail to load in the editor, because we _do_ need an InputStream at that point. I don't have a great solution at the moment, apologies.



For me it happens even for smaller images... Sometimes they may show up in the gallery but when you choose them they don't show up in the next step... (image below) 

Version 7.40.2 (apk install)  has been happening for months for me
Sometimes it works fine and sometimes not. 

![Image](https://github.com/user-attachments/assets/0bc3f083-1966-404a-9dbb-2c2d9b7f5195)

**Comment by jeffrey-signal** [comment]
This issue _should_ be fixed in 7.53 (upcoming). Once it's available, please update and let us know if the problem persists! 🙂

**Comment by struthio** [comment]
I do not know if this is just Me or general issue. I have 7.54.1. 
It was working for like once. I managed to send some pictures to my family, but now the issue is back.
Instead of picture there is black place holder and when sending, error is returned.


The gallery (thumbnails) works. I can select photos, but after I click "blue arrow" every preview is black.

**Comment by jeffrey-signal** [comment]
The fix had to be reverted due to it causing other issues. I'll update this issue once it's fixed again!

**Comment by jeffrey-signal** [comment]
Resolved in v7.55
