### ISSUE TITLE
Constant spurious "Checking for messages..." notifications

### ISSUE THREAD

**Issue by samott** [signalapp/Signal-Android#11084]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is producing spurious "Checking for messages" notifications at irregular intervals which cause my device to think there is a new message. I've been seeing this behaviour for a week or two now but have only just realised that it is Signal causing the problem.

### Steps to reproduce
The notifications seem somewhat random, e.g. I'll get one in the middle of the night and then nothing for a day - or two or three together. Recently they appeared as I was using the device which is how I noticed it was Signal.

### Device info
**Device:** Google Pixel 2 XL
**Android version:** 11
**Signal version:** 5.4.12 (non app store version)

**Comment by greyson-signal** [comment]
So we do post those occasionally to check for messages in the background as a way to help devices that limit some app's abilities to receive push notifications. However, we put them in a low-priority notification channel that should cause your phone not to emphasize them. We also only show a notification if a fetch is taking some time.

> or two or three together

Currently we have them set for every 6 hours. Are you seeing them occur in bunches more frequently than that?

**Comment by NeutralBit** [comment]
> However, we put them in a low-priority notification channel that should cause your phone not to emphasize them.

Low-priority notification still shows a notification icon, which gives an impression of new message. Is it possible to use minimal-priority channel? It doesn't show icon.

**Comment by samott** [comment]
> So we do post those occasionally to check for messages in the background as a way to help devices that limit some app's abilities to receive push notifications. However, we put them in a low-priority notification channel that should cause your phone not to emphasize them. We also only show a notification if a fetch is taking some time.
> 
> > or two or three together
> 
> Currently we have them set for every 6 hours. Are you seeing them occur in bunches more frequently than that?

Yes, I saw a couple within a few minutes of each other. However, I haven't noticed any ghost notifications for at least 24h now (they might have appeared in the notification shade but not triggered a sound).

**Comment by greyson-signal** [comment]
>  Is it possible to use minimal-priority channel? It doesn't show icon.

Unfortunately 'low' is as low as you can go for a foreground service. If you go lower, android will put in an ugly placeholder notification that just says 'Signal is doing work in the background'.

@samott I believe we've figured out the bug that could cause this fetch to happen too often, and it'll be fixed in 5.5.0. Thanks!

**Comment by samott** [comment]
Does this address my original problem though? Or am I still going to be annoyed by random, but less frequent beeps? I've never had a problem with push notifications on Signal so maybe this service should be made optional, for those with phones that need it.

As as side note, I'd really love to make the update notifications optional too (tell me in the app, not through the notification system) as these also wake me up in the middle of the night.

**Comment by samott** [comment]
Still having this issue with the latest version. I'm on the verge of just uninstalling Signal at this point as the annoying pings from my phone every so often are becoming unbearable.

Surely the "Checking for messages..." check can be made optional? I never had any problems before without it.

**Comment by cody-signal** [comment]
@samott please post a debuglog so I can give it a look. There should be no audible sound when the notification pops unless something in settings has been changed for the "Other" channel.

**Comment by kees** [comment]
This happens through Android Wear devices. I don't see the notification on my phone, but my watch buzzes frequently.

**Comment by revpriest** [comment]
Yeah, these are informational messages which surely should have an off switch. They're coming in on my watch and I honestly will never ever want to be notified that the app is checking for messages unless, you know, if finds one.

**Comment by kees** [comment]
Can we please reopen this issue? It's clearly not fixed, and I get like 50 alerts a day for "Checking for messages..."

**Comment by zilexa** [comment]
Same here! Super annoying. Even with Signal app open, I'm looking at my messages. Then that notification comes and it takes 30 seconds or longer before I actually see the new message. It makes no sense and if I need an urgent reply I nowadays switch more often to WhatsApp because of this.
