### ISSUE TITLE
Messages not received until app is placed in background or restarted, and probable root cause + fix

### ISSUE THREAD

**Issue by jonahbeckford** [signalapp/Signal-Android#11095]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The bug is fairly general: I've waited for up to an hour waiting for messages to be received. I've seen other people report similar things. If I switch apps (ex. switch to a game, and then switch back to Signal) my messages start going through.

I think I've found the root cause, so this issue describes the smallest set of steps to reproduce the issue. I will likely send a pull request to fix that small sequence, but that fix will likely need to be made more general.

Possibly related issues since Feb 1:
* https://github.com/signalapp/Signal-Android/issues/11079
* https://github.com/signalapp/Signal-Android/issues/11071 (perhaps)
* https://github.com/signalapp/Signal-Android/issues/11048
* ~~https://github.com/signalapp/Signal-Android/issues/11023~~
* https://github.com/signalapp/Signal-Android/issues/10974
* https://github.com/signalapp/Signal-Android/issues/10939

### Steps to reproduce
It is important _not_ to switch Signal into the background during these steps.

*On your phone*

- First, go through the "registration" flow: Welcome, Enter Phone, Verify Phone, Re-enter Signal PIN, Enter Profile Info
- Second, send a message "hi" to another Signal user ("other")

*On other phone*

- Third, accept the message sender (or see the "Your safety number ... has changed)
- Fourth, reply to the message with "Hi2"

*On your phone*

- Fifth, wait for a long time (1hr 2 mins and counting) ... no "Hi2" message
- Sixth, move the Signal app into the background and then back into the foreground. _Sometimes_ you will get the "Hi2" message. If you do get a message, it will be immediately after switching apps.
- Seventh: If you close the Signal app and re-open, you will get the undelivered messages immediately.

**Actual result:** Reply message is stuck for a long time
**Expected result:** You get the reply message within seconds

### Device info
**Device:** Android Emulator Pixel 2 XL 
**Android version:** 9.0 x86 with Google APIs
**Signal version:** 5.5.0

### Link to debug log
* https://debuglogs.org/ca04bcd0d8fd2dd35b1b364c522f47e968874a11d1224ba82715a10d0cc6bf0a is the reproduction steps from "First" to "Fourth". No reply message seen.
* https://debuglogs.org/8a1579aa888dc8c2cc14b7572713307d88ebfee1a7c1460f69cfb86c06bf6469 is the steps from "First" to "Sixth". (Noise: I additionally sent the first debug log URL to the "other" user in step "Sixth".) No reply message seen.
* https://debuglogs.org/d8267b7509e71e79757e0e6b78e173995e3679ed00ec55d67ffe867dab1826b5 is the steps from "First" to "Fourth" but only after applying the "Limited Fix" below. I can see the reply message immediately.

### Probable root cause 1
1. The BackgroundMessageRetriever will keep doing "Skipping retrieval -- app is in the foreground" correctly because the Signal app has never been in the background. All the FCM messages will be ignored.
2. The IncomingMessageObserver.MessageRetrievalThread will be stuck in an Object wait state (through IncomingMessageObserver.waitForConnectionNecessary). The only way for it to connect to a websocket is if someone notifies IncomingMessageObserver ... which only happens when the Signal app is has a foreground or background event. 
3. One of the 5 conditions in IncomingMessageObserver.isConnectionNecessary() is TextSecurePreferences.isPushRegistered() == true. That value changes (see log line `03-12 16:54:39.432 23431 23633 I TextSecurePreferences: Setting push registered: true`). However, according to "2." above, there is no one to notify IncomingMessageObserver! If there were some notification, we would see a corresponding `IncomingMessageObserver: Network: true, Foreground: true, FCM: true, Censored: false, Registered: true, Websocket Registered: true, Proxy: false` log line, but we don't.

The above explains why people are getting inconsistent, seemingly irreproducible behavior. Only if they switch their app, the messages magically start. And even switching their app does not always work, because the foreground / background event is not emitted reliably.

### Probable root cause 2

1. The AppForegroundObserver used by IncomingMessageObserver seems flaky. It would be useful to actually emit a log line when the app is foregrounded or backgrounded to know for sure, but the lack of `IncomingMessageObserver: Network: true, Foreground: true, FCM: true, Censored: false, Registered: true, Websocket Registered: true, Proxy: false` log line in the second debug log even after foregrounding/backgrounding repeatedly indicates that AppForegroundObserver is not reliable.

### Limited Fix for probable root cause 1

Added "new code" to the bottom of `org.thoughtcrime.securesms.registration.service.CodeVerificationRequest#verifyAccount`

```java
    TextSecurePreferences.setWebsocketRegistered(context, true);
    // ...
    TextSecurePreferences.setPushRegistered(context, true);
    // ...
    // BEGIN new code
    IncomingMessageObserver incomingMessageObserver = ApplicationDependencies.getIncomingMessageObserver();
    synchronized (incomingMessageObserver) {
      incomingMessageObserver.notifyAll();
    }
    // END new code

    PinState.onRegistration(context, kbsData, pin, hasPin);
```

This limited, hacky fix just sends an `Object.notifyAll()` notification after the registration flow. A more general fix would be to send a notification when any of the 5 conditions changes. For example, any change via TextSecurePreferences.setPushRegistered should directly or indirectly notify IncomingMessageObserver.

I could submit a pull request as-is *or* do a more clean and more general fix. If a more general fix, I'd like to get suggestions from the Signal team for a clean mechanism to do the notifications (ex. is there an internal-to-Signal-app event mechanism?).

**Comment by sailbird** [comment]
@jonahbeckford Thanks for the outstanding deep dive... but why do you suppose this bug goes in mood cycles which are only temporarily fixed by nothing short of upgrading or reinstalling the app itself? At least, in the following manifestation, (un)backgrounding doesn't seem to be the issue; notifications just suddenly break.

https://github.com/signalapp/Signal-Android/issues/11023

**Comment by jonahbeckford** [comment]
First, I didn't mean to notify all of the other "possible related" issues. I'm still a newbie with Github issues.

Second, after looking again at the debug logs in #11023 it does seem like there was a `notify` done on the IncomingMessageObserver. So this issue is not a root cause for the #11023 issue. I'll comment directly on that issue.

**Comment by greyson-signal** [comment]
Thank you very much for the research here! At least in one case, you were very right :) Gave you a shoutout in the commit.

**Comment by Songbird0** [comment]
I am reopening this thread to report that I am still experiencing the problem.
See https://community.signalusers.org/t/messages-do-not-synchronize-in-real-time/29942?u=roboyo
