### ISSUE TITLE
Signal call stutters heavily but worked a month ago

### ISSUE THREAD

**Issue by major-mayer** [signalapp/Signal-Android#11789]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a few weeks I experience heavy stutters when i try to call somebody from my home wifi.
This behavior was not present before and does disappear when i switch from my Wifi to LTE.
This is very weird, because my Wifi is very stable and fast (200/20 Mbit)  with 20 ms ping and almost no jitter and packet loss according to Speedtest.net.

I already tried connecting to different APs, including the router itself, which did not change much.
I also tested it with different contacts and it always resulted in the same stutter/ lag.

This bug makes calling with Signal nearly impossible for me, which is very unfortunate...
In fact i really liked the call quality from Signal and recommended it to my friends.
WhatsApp calls work just fine btw...

I know that this might be not enough information to debug this problem, but don't know of anything else that i could do.
But feel free to tell me what i could do, this happens with any call right from the beginning anyway...

### Steps to reproduce
- Connect to my home wifi
- Start a call with any person

**Actual result:** Call is very distorted with lag/ dropped sections/ stutter
**Expected result:** Call should not be distorted

### Screenshots
---

### Device info

**Device:** Poco F3
**Android version:** 11
**Signal version:** 5.27.3

### Link to debug log

https://debuglogs.org/f30e69935bb2d876bef4ab6d1d377d4e19f00015c193cdbfc6c0a72188676aa6

**Comment by major-mayer** [comment]
I've tried it once again using another WiFi network from a different provider for both the caller and the receiver side and we again had the same problems. Communication was almost impossible, because sections of more than 5 seconds were completely dropped.

I have a 1 GBit/s connection, the other one isn't bad either.
When I switch to cellular network, everything works as intended (apart from eating up my data volume...).

Is there anything that I can do to help debugging this problem?

**Comment by enoch85** [comment]
Also wondering. It's embarrassing to invite people to Signal and hear them complain about video/call quality.

I'm on Android 12 and OP9, latest app. 
Wifi 250/250 7 ms response time.

**Comment by major-mayer** [comment]
Hmm at least good to know that i am not the only one that has this problem.
Could you tell me if your ISP is using Dual-Stack Lite (DSLite) for the connection?

I would doubt it tho that that this is the reason for the issue, because i also tested it at another location, where they have a pure IPV4 connection and the problem was still the same.

But for you the Signal calls over normal cellular network work too?

**Comment by enoch85** [comment]
I'm located in Sweden. Here we have pure fiber almost everywhere. I actually don't know what DSLite is? We had ADSL around year 2000 though.

I'm on a 5G net on mobile, and it's the same thing. :/

**Comment by enoch85** [comment]
Still same issue. Tried different networks.

**Comment by major-mayer** [comment]
Jep i can confirm this. It really makes calling on my WIFI network practically impossible.
I always have to switch to cellular which consumes my data volume.

**Comment by enoch85** [comment]
Here's mine.

https://debuglogs.org/android/5.36.3/6320e7dc5c3a63855f8035d2713bffadb985bca0bf002a3cf1e5bd0bd1bc60eb

**Comment by major-mayer** [comment]
And here is mine: https://debuglogs.org/android/5.36.3/1861cebb6072dcc57add68c6e3cb9c6080ca7111d73075800e74f435ec1db5d1
I did a quick call with Wifi enabled, the stuttering started again and it was very hard to understand anything, then i disabled Wifi and my phone switched over to LTE, which made the quality as good as it was months ago.

**Comment by imightbelosthere** [comment]
I am facing the same situation. Calls over WiFi are just randomly stuttering. I switch over to 4G and it's fast and no symptoms of anything.

Curious enough I also have an OP9 so I don't know if it's device related. I am going to test with a Poco F2 Pro.

WiFi's 1.6Gbps and my net connection's sitting at 500Mbits so I don't believe that's the issue since Teams, Zoom, Duo and other video calls work perfectly.

**Comment by major-mayer** [comment]
Seems like this can be reproduced by at least a handful of people.
It shouldn't be closed. Can you please reopen it @cody-signal @greyson-signal?

**Comment by major-mayer** [comment]
Hmm, I just did a quick test call and apart from the fact that my phone didn't ring one time, the call issues were indeed gone.
I will monitor this in the next days and report if encounter got any issue.

**Comment by abdusalamApps** [comment]
I'm having the exact same issue. Stutters on WIFI, no issues on 4G/Cellular.
I guess the issue has to do with upload speed. I live in Sweden and Have no problem with Signal calls on WIFI here. I have a 100/100 mbps fiber, but when I visited Turkey and tried Signal calls on WIFI on a 100/10 mbps fiber I got very poor call quality. Stutters, missing sections and even dropped calls. Signal calls on 4G/Cellular work fine in Turkey too. The only difference I can think of is upload speed.

**Comment by abdusalamApps** [comment]
There an option in the settings (Settings -> Data and storage -> Calls -> Use less data) that is supposed to make calls more stable on slower networks, I guess. What if this option could use even less data than what is specified right now. Wouldn't this solve the problem?

**Comment by imightbelosthere** [comment]
Damn I had a call yesterday over WiFi and ... I forgot to capture the logs. :(
Situation's the same tho... over WiFi on a video call it stutters and when I move to 4G/5G on the mobile operator it works flawlessly.

I'm going to have another one of these calls next week, I've put a reminder to capture the debug logs and bring it back here.
Sorry for this guys.

**Comment by ozmax** [comment]
same issue here, halp plox

**Comment by greyson-signal** [comment]
Hey folks, for anyone experiencing call issues, please share a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug).

**Comment by major-mayer** [comment]
Here you go: https://debuglogs.org/android/6.7.3/50f54d011421a163128d663484390965652108b883e11916608d9601b9f6f3f7
Completely different network than the last time when I posted a debug log, but still the stutter appear a few times per minute.
I wonder if this is a very device specific issue...? In my case, it's still a POCO F3.

I can't reproduce those issues when calling with Signal Desktop over the same network.

**Comment by muelli** [comment]
I also observe stuttering at least once per second when using the Android app on Wifi. It works well on the cellular network. The desktop app also works well on the same WiFi.

> Here you go: https://debuglogs.org/android/6.7.3/50f54d011421a163128d663484390965652108b883e11916608d9601b9f6f3f7


```
01-10 21:08:31.283 18876 22830 W packet_***.cc: (line 175): Packet buffer flushed, 50 packets discarded.
01-10 21:08:31.283 18876 22830 W packet_***.cc: 
01-10 21:08:33.535 18876 22724 I WebSocketConnection: [normal:48103591] Sending keep alive...
01-10 21:08:33.535 18876 22724 I WebSocketConnection: [unidentified:176299338] Sending keep alive...
01-10 21:08:39.236 18876 22831 I ringrtc::webrtc::stats_observer: ringrtc_stats!,connection,1673381319231914,21ms,258206bps
01-10 21:08:39.236 18876 22831 I ringrtc::webrtc::stats_observer: ringrtc_stats!,audio,send,1002,50.0,100.0,40001.6bps,0.0%,4ms,14ms,0.338
01-10 21:08:39.237 18876 22831 I ringrtc::webrtc::stats_observer: ringrtc_stats!,video,send,1003,0.0,0.0,0bps,0.0fps,0,0.0ms,0x0,0,0.0bps,0.0ms,0,0,other,0,0.0%,0.0ms,0.0ms
01-10 21:08:39.237 18876 22831 I ringrtc::webrtc::stats_observer: ringrtc_stats!,audio,recv,2002,49.9,0.0%,39921.6bps,4ms,1.176
01-10 21:08:39.237 18876 22831 I ringrtc::webrtc::stats_observer: ringrtc_stats!,video,recv,2003,0.0,0.0%,0bps,0.0fps,0,0.0ms,0x0
01-10 21:08:40.797 18876 22830 W packet_***.cc: (line 175): Packet buffer flushed, 50 packets discarded.
```

I have the same entries in the log when the problem occurs.
I couldn't observe these log items when being on the cellular network.

**Comment by major-mayer** [comment]
Damn, that's interesting, good job.
Hopefully the Signal Android devs can do something with this information.

**Comment by ryannathans** [comment]
I upgraded to a new phone and now I have this problem, signal is now unusable. Same wifi network and same signal version works fine on other phones in the house.

**Comment by major-mayer** [comment]
That's what I also experienced, other people in my household can use signal calls just fine using the same network.
This problem seems to be really device specific, but only affects Signal.

30.01.2023 04:10:42 Ryan ***@***.***>:

**Comment by muelli** [comment]
do you mind sharing debug logs?

**Comment by ozmax** [comment]
In case it helps, my device that has the exact same problem is a Xiaomi 11 Lite 5G NE with MIUI 13 on Android 12. Previous device was a Xiaomi 7 Note Pro and Signal was working fine there.

**Comment by muelli** [comment]
> In case it helps, my device that has the exact same problem is a Xiaomi 11 Lite 5G NE with MIUI 13 on Android 12. 

same here. maybe it is indeed specific to the modified Android :(
Maybe we can get one of those devices into the hands of a capable developer to debug the issue further.

**Comment by ryannathans** [comment]
https://debuglogs.org/android/6.9.2/173241d3fd7f4f9e3351298f53ff48ded9d7064a8a460c3e32aec6054726e28a

here are my logs created immediately after reproducing the problem

**Comment by muelli** [comment]
> here are my logs created immediately after reproducing the problem

you, too, have these "50 packets discarded" items in your log:
```
[6.9.2] [6133 ] 2023-01-29 14:15:41.368 GMT+11:00 I ringrtc::webrtc::stats_observer: ringrtc_stats!,audio,recv,1002,35.8,0.8%,22343.2bps,2ms,0.452
[6.9.2] [6133 ] 2023-01-29 14:15:41.368 GMT+11:00 I ringrtc::webrtc::stats_observer: ringrtc_stats!,video,recv,1003,0.0,0.0%,0bps,0.0fps,0,0.0ms,0x0
[6.9.2] [6131 ] 2023-01-29 14:15:46.485 GMT+11:00 W packet_buffer.cc: (line 175): Packet buffer flushed, 50 packets discarded.

[6.9.2] [6131 ] 2023-01-29 14:15:49.986 GMT+11:00 W packet_buffer.cc: (line 175): Packet buffer flushed, 50 packets discarded.

[6.9.2] [6133 ] 2023-01-29 14:15:51.367 GMT+11:00 I ringrtc::webrtc::stats_observer: ringrtc_stats!,connection,0x2659c0cc84a710f2,1674962151362272,80ms,443840bps
[6.9.2] [6133 ] 2023-01-29 14:15:51.367 GMT+11:00 I ringrtc::webrtc::stats_observer: ringrtc_stats!,audio,send,2002,27.2,74.2,16144.9bps,1.5%,91ms,86ms,0.002
```

**Comment by ryannathans** [comment]
```
[6.9.2] [13977] 2023-01-31 20:41:56.770 GMT+11:00 W packet_buffer.cc: (line 175): Packet buffer flushed, 50 packets discarded.

[6.9.2] [13977] 2023-01-31 20:42:00.287 GMT+11:00 W packet_buffer.cc: (line 175): Packet buffer flushed, 50 packets discarded.

[6.9.2] [13977] 2023-01-31 20:42:03.806 GMT+11:00 W packet_buffer.cc: (line 175): Packet buffer flushed, 50 packets discarded.
```

these messages appear to correlate strongly with the frequency of drops

**Comment by ryannathans** [comment]
I captured the logs after a call between 2 devices unaffected by the issue, these packet_buffer log messages do not exist.

Interestingly, logs from a phone not affected by the issue called by a phone affected by the issue DOES have the packet_buffer.cc discarded messages

**Comment by jrose-signal** [comment]
Thank you everyone for your reports! Just to check, some people in this thread are talking about *video* calls and some are talking about *audio* calls. Can you clarify whether "stutter" means "incoming audio was dropped/bad/choppy", "incoming *video* was dropped/frozen/pixelated/choppy", or something else?

**Comment by jrose-signal** [comment]
Additionally, if you're willing to go the extra mile, could you ask *the person on the other side of the call* for a debug log as well? It's extremely useful for establishing whether an issue is sender-side or receiver-side if we have logs for both sides of a call. (I know there's commonality on the receiver-side reports here, but it may be the case that it's the send side that's misbehaving, but only, say, when the receive-side is on a steady enough connection.) If they're worried about linking them publicly on GitHub, they can send it to our Support, mentioning "GitHub Android issue 11789".

**Comment by muelli** [comment]
> Thank you everyone for your reports! Just to check, some people in this thread are talking about _video_ calls and some are talking about _audio_ calls.

I certainly have the issue with audio calls, but I remember video calls also being heavily impacted.

> Can you clarify whether "stutter" means "incoming audio was dropped/bad/choppy", "incoming _video_ was dropped/frozen/pixelated/choppy", or something else? (EDIT: or both?)

So for me, I have blank incoming audio for 250ms or so every second, at least. The other parties report that they experience me being similarly blank for them. For the video, I remember calls being stalled the same way, i.e. the video feed not updating (as with the audio).



> If they're worried about linking them publicly on GitHub, they can send it to our Support

I feel almost sorry to ask: how would one send anything to the "support"?

**Comment by jrose-signal** [comment]
The option to send your debug log to Support should come up after you submit it as well, at least on mobile!

**Comment by ryannathans** [comment]
These are the logs from both sides immediately after a call with heavy dropouts.

I also noticed that some speech was significantly delayed in addition to dropping out.

https://debuglogs.org/android/6.9.2/fdaffa2eb1fb957fec33b174d02aac286b48256708fadb6d726684f5c20fb261

https://debuglogs.org/android/6.9.2/31bc8b0549589a575fcf795fa324febab15a649979983137ae5de85ceacee352

**Comment by major-mayer** [comment]
> The option to send your debug log to Support should come up after you submit it as well, at least on mobile!

I cannot confirm this. The only option available is to share them via an arbitrary messaging app.

But nevertheless, here you go:
https://debuglogs.org/android/6.10.5/b13abfb8111d436cd8ae077087f5778199215f09c4dd35a04e65f711e3ac4cd5
https://debuglogs.org/android/6.9.2/a6e998ddb753f5dd7f9b809a978b6ccc570b6c2bd728ccbd6c55bb282281f6bc

Just did a quick test call and experienced some enormous stuttering. 
It was basically impossible to understand a single sentence completely.

**Comment by muelli** [comment]
just wanted to report that 6.10.9 works much much better for me than the previous versions.

**Comment by ryannathans** [comment]
> just wanted to report that 6.10.9 works much much better for me than the previous versions.

no difference whatsoever for me

**Comment by abdusalamApps** [comment]
@muelli It works much better for me too. I don't feel the need to switch to cellular data anymore. Even on WIFI with slow upload speeds like 10 Mbps

**Comment by rashad-signal** [comment]
In version 6.13 of the app, there are improvements that address audio stuttering. It's now available in production, so if you're still experiencing this issue, can you try updating and let us know how things are now? If you're still having problems, then new debuglogs would help.

**Comment by keeponkeepnon** [comment]
I'm having this same issue. Just started when I switched to a galaxy S23+. Signal call quality is terrible over wifi just about unusable, same with 5G cellular connectivity. I've tried it on multiple routers and no change. The only way I can have clear calling over Signal is by connecting to a VPN first then the calls are crystal clear and no lag. Anyone have any ideas ? I'm in the United States so no state firewalls etc at play. 

Would really really like to get this resolved as I rely on Signal calling every single day.

Running version 6.13.6
Android 13
Wi-Fi 250/250 Fiber optic 12ms ping 0% packet loss

**Comment by major-mayer** [comment]
> In version 6.13 of the app, there are improvements that address audio stuttering. It's now available in production, so if you're still experiencing this issue, can you try updating and let us know how things are now? If you're still having problems, then new debuglogs would help.

Hi @rashad-signal ,
I had issues with Signal calls since ages, and I am happy to confirm that the latest versions did indeed improve the situation a lot!
Big thanks for your work :heart:

One last thing that I noticed, is that while the stuttering seems to be gone, I now experience some delay, when talking with another person.
This makes communication a bit hard, because you often answer on things, and the other person has already continued with the next topic.
Should I create a separate issue for this and close this one, or should we stick to it?
Do debug logs help in this situation?

**Comment by ryannathans** [comment]
This patch fixed the stutter and introduced a HEAVY delay that makes communication even worse

Logs from affected phone: https://debuglogs.org/android/6.13.6/f4f2d97ebecedba690bea632abc0f831392694b366f86df962cb92eb02b335a0

Logs from other phone: https://debuglogs.org/android/6.14.2/0b11a73e8c22d9d76589238fe60af33ae1a8badff8ee4da221ad74b8a6dfc72d

**Comment by major-mayer** [comment]
Yes, unfortunately I have to confirm this.
I did two test calls on 20.03.2023 at about 21:53 and indeed the stuttering is more or less completely gone, but when I'm on Wifi I now have a delay of about 6 seconds, which is far from acceptable.
Interestingly, as soon as I switch to the (slower) cellular connection, the delay is not an issue any more.
I hope that this issue will be fixed completely at some point. Right now, it's more of an improvement for the worse.

Here are the debug logs: https://debuglogs.org/android/6.14.4/436a83320e141d84f9c0969e973fa06cf120f60625b2d15059829cd11c9a635b

Both sides were on Signal 6.13/14

**Comment by muelli** [comment]
> I'm on Wifi I now have a delay of about 6 seconds, which is far from acceptable

I've also just experienced this lag of about 5 to 6 seconds.

**Comment by enoch85** [comment]
Same here, not matter if I'm on Wifi or not, the lag is there about 5-6 seconds as mentioned before. Maybe not so helpful, but just confirming the issue.

**Comment by rashad-signal** [comment]
Version 6.16 of the app is now rolled out fully and it reverts the changes that caused the increase in audio delays, but it also will likely reintroduce the stutter for people who previously experienced it.

We still haven't figured out a complete solution to this, but there's something else that would be helpful to know for debugging it: Does turning on the option to [use less data for calls](https://support.signal.org/hc/en-us/articles/360056044831-Data-Usage-Options-Wi-Fi-Cellular-#android_data) for both WiFi and Cellular help reduce the stuttering (or delay if on a version with high delays)? This option is off by default, so turning it on for both phones in the call and getting logs from both sides would help. Or at least turning it on for one phone and getting logs from the other side.

**Comment by ryannathans** [comment]
@rashad-signal 

My phone, with "use less data for calls" enabled, on wifi: https://debuglogs.org/android/6.17.3/9b722708b76379c446c093af22f9e3494fc21400a90024a9d468d9715b1d3e7b

Friend's phone, with it likely disabled/default: https://debuglogs.org/android/6.17.3/3487a6a237bcc52cabccc396b12935be36d0ab79ca5d135c3c2368cf65c91da2

The experience: we experienced severe delay again, but it did not stutter

**Comment by toilala** [comment]
I have turned on use less data in both phone and the stutter lag makes the call unusable totally unusable.

Debug log: https://debuglogs.org/android/6.18.4/b711685f97cda17802d659050d691489ec0f041ebd0918ab23a925ee8827f2a1

**Comment by rashad-signal** [comment]
@toilala It looks like you were doing a video call, so could you clarify whether the problem was happening with audio or video (or both) for you? It would be useful to know whether the other person in the call experienced the same problem (debug logs from them would be even better if you can get them).

Looking at your logs, it seems like there might have been some delay with the audio, but nothing was being dropped. And for video, there would've been stutter (dropping frames), but maybe not as much lag, if any? Does that sound accurate?

It's also not too surprising that "use less data" doesn't help for this case since video is using up more data. I was hoping it would help for audio-only calls, so if you could try an audio-only call too and get logs, that could be helpful.

**Comment by bhlevca** [comment]
> Thank you everyone for your reports! Just to check, some people in this thread are talking about _video_ calls and some are talking about _audio_ calls. Can you clarify whether "stutter" means "incoming audio was dropped/bad/choppy", "incoming _video_ was dropped/frozen/pixelated/choppy", or something else? (EDIT: or both?)

Choppy means that there are frequent freezes of audio and video, sometimes for seconds.
The video calls show that the disconnect and try to reconnect.

Sometimes this is so bad that no dialog can take place. I love Signal, but if this doesn't get fix it is hard to keep my friends on the platform. It is safe but not useful. 
This needs urgent  attention!! Thanks

**Comment by toilala** [comment]
It's both. For me each and every time I call, the video and audio is fine for first couple of seconds and it worsens to the point it's totally unusable. 

I don't know why this issue is overlooked as it's one of the main features of the app. I love signal but if it does not get fixed I'll be forced to switch.

**Comment by enoch85** [comment]
> It is safe but not useful.

Couldn't agree more. My wife now refuses to use Signal, and she took her family with her in the "fall". More and more people leave Signal, and this is just one of the reasons. 

Sure, it's safe and all that, but it needs to be usable to be liked by others than privacy and integrity interested people.

**Comment by arnowelzel** [comment]
Same here - Signal audio recording or audio in Signal calls does not work at all (LineageOS 20 which is based on Android 13) while calls using the phone app work just fine and also audio recording with other apps.

**Comment by keeponkeepnon** [comment]
Same issue with me except turning on video tends to negate the audio
quality issues if I remember correctly.

None of this was a problem until I upgraded phones and went from Android 10
to Android 13.

Now the only way I can reliably use Signal audio calling is by turning on a
VPN connection first (any commercial VPN will do) then all lag and
choppiness is gone.

I also notice the choppiness/lagginess seems to mostly occur when I'm on my
home WIFI or the cellular tower serving my home. If I leave and get on a
different wifi network or different tower the issues subside quite a bit.
No idea what to make of it all. Would really really like to get Signal
calling working reliably again.

That said it's nice to know I use about 5 GB in audio a month. (VPN
allotment)

**Comment by arnowelzel** [comment]
> Version 6.22 of the app is now rolled out fully and it has some changes to how audio is sent in calls. Could someone who is still experiencing this issue try updating and let us know how things are now? New debug logs from both sides of the call would help for understanding remaining problems.

No - still the same problem :-(

And it is **not** how audio is sent - even recording a message fails with heavy stuttering, exactly as it was with 6.21.

**Comment by bhlevca** [comment]
Actually, my version reads 6.23.1 (beta tester) . For me, the problem is the same or even worse. 
I captured yesterday wa popup message while talking with a friend for 30 minutes with numerous interruptions: 
"weak wi-fi" switching to mobile data" 
My Wi-fi is very strong and I was on 5Gh very high throughput.  For some reason, Signal thought that wifi has problems when they are not there.

**Comment by rashad-signal** [comment]
@arnowelzel It sounds like you're experiencing a different problem that affects all recorded audio. The original report was a report specific to WiFi calls (calls on cellular worked fine). If you don't want to share debug logs publicly but are ok with sending them privately, you can email them to me at rashad@signal.org. If not, that's ok too, but it's unlikely that we would be able to figure out what's going on.

---

@bhlevca 6.23 is fine too for testing the latest changes. If you post logs, I'll take a look at them too.

It isn't clear yet why this only happens on WiFi, and there doesn't seem to be anything that suggests that throttling is happening. Throughput looks normal based on the logs posted so far, but packets are being delivered in bursts. And when too many packets come in late, they're being discarded instead of playing out audio that's really delayed.

**Comment by bhlevca** [comment]
Here are my logs:
https://debuglogs.org/android/6.23.1/7ff7d8be691804866c560f266b35c461a1b6c1be47207e132340987962865451

**Comment by rashad-signal** [comment]
@bhlevca There's something that stands out in those logs. There were two calls done entirely over mobile data, and the problem with audio packets being discarded happened there too. So it doesn't seem like the problem is isolated to WiFi for you. It probably isn't worth looking further into what your router can do.

It also looks like the person / people you're calling are on an app version older than 6.22 (if they're on Android). It'll be useful to hear how things are when they update to have the latest changes.

**Comment by bhlevca** [comment]
> @bhlevca There's something that stands out in those logs. There were two calls done entirely over mobile data, and the problem with audio packets being discarded happened there too. So it doesn't seem like the problem is isolated to WiFi for you. It probably isn't worth looking further into what your router can do.

I have a weak signal over the mobile network in my area so that interruption may have been caused by the lack of bandwidth, but the overall performance was decent, better than over the wifi

> 
> It also looks like the person/people you're calling are on an app version older than 6.22 (if they're on Android). It'll be useful to hear how things are when they update to have the latest changes.

I can ask them to update the version and try again/

On another note, I tried an audio chat on Google Meet. It is a bit better over the wifi but there are still interruptions. So it is not only Signal with issues, but I admit Signal is worse.

Can you see in the logs if throttling could be the cause?

**Comment by ryannathans** [comment]
Updated debug logs

Affected device: https://debuglogs.org/android/6.22.8/bdbd15472bcdbc955efc4fad50e7d6e82f99519c81232069df9193c77b2591e2
Unaffected device: https://debuglogs.org/android/6.22.8/4410c1e12a6b5bf018a5e2e31619ddf669d30052ce847d63d31efc694e1d3b6d

The affected device called the unaffected device, both on wifi. The call was **very** delayed (5-10 seconds perhaps?), but there was no stutter.

Shortly after, the affected device called the unaffected device again, with the affected device on 4G data instead of wifi. The call seemed normal, there were no noted issues. The delay seemed to be about 1/4 to 1/2 second, seemingly normal.

**Comment by major-mayer** [comment]
I can't exactly tell since which version it works again, but currently I'm on 6.24.3 and i can finally call people again even on wifi! 🥳
No stuttering anymore, no missed frames, no delay, everything works as it always worked on cellular network, which was okay all the time.
Maybe if was also somehow related to my switch to Android 13, but I can't exactly tell. 
Thanks for the good work to the devs ❤️

I will closes this issue as it is already quite old. 
If you are still affected, please create a new issue.

**Comment by bhlevca** [comment]
Interesting to hear that problems have been fixed, I need to test that. Please don't close it yet. Perhaps is just a fluke, let open for a few more days until more people have the opportunity to test.

**Comment by arnowelzel** [comment]
> I can't exactly tell since which version it works again, but currently I'm on 6.24.3 and i can finally call people again even on wifi! 🥳 No stuttering anymore, no missed frames, no delay, everything works as it always worked on cellular network, which was okay all the time. Maybe if was also somehow related to my switch to Android 13, but I can't exactly tell. Thanks for the good work to the devs ❤️

When will this version be available on Google Play? So far I only got 6.23.5 and don't see any update.

**Comment by bhlevca** [comment]
If you subscribe as a beta user you will get it.

**Comment by arnowelzel** [comment]
> If you subscribe as a beta user you will get it.

Thanks, but using beta versions is not an option for me. I'll have to wait then.

**Comment by bhlevca** [comment]
> Thanks, but using beta versions is not an option for me. I'll have to wait then.

Why subscribing to beta is not an option? 

They are stable and bugs are fixed quicker but obviously, it is your choice. 
 6.24.4  has many more nice features like message editing after being sent and text formatting , etc.

**Comment by arnowelzel** [comment]
If these versions are stable and why not just releasing them? There is a reason why software has "beta" status - it is not considered finished yet and things may still go wrong. However a working and tested version is more important for me than having voice calls and nice features. I don't use beta versions on any production system. Yes, if the voice calls is once fixed as well, this would be nice. But I prefer having a regular update with the fix which is considered to be production ready as well.

**Comment by bhlevca** [comment]
As I said, the choice is yours. Sometimes beta versions are better than the “released” buggy versions, which is the case now.

**Comment by arnowelzel** [comment]
Now 6.24.4 has been released officially. But the issue remains :-( Audio recording is choppy (stops about every second) and neither I can hear the other person nor the other one hears me.

**Comment by keeponkeepnon** [comment]
At first I thought 6.24.4 fixed the issue as some calls were working
without issue but the problem remains. VPN still resolves it but I've also
found forcing the phone to not use NR (5G) and alternatively using LTE
exclusively seems to help the issue quite a bit but not entirely. Such a
weird problem. Still just continuing to use the VPN and rotating accounts
to get enough bandwidth. Now using about 6-8 gigs in audio a month. Has
anyone else tried using a VPN before initiating a call ? Thanks.

**Comment by ryannathans** [comment]
The issue remains unchanged.

Please reopen.

Affected device: https://debuglogs.org/android/6.24.4/d7c7b1a3ac0c87cea78e72053bef4793b23d6d61c2738f5eff17d4796006f55e
Unaffected device: https://debuglogs.org/android/6.24.4/791d62ce55a05a68bb5c7a8b1d4fe9bb18449123c1f6b5748b58d3c7b4575492

Order of events:
Disconnected vpn
One call on wifi
One call on 4g
Connected vpn after call
Collected logs

**Comment by bhlevca** [comment]
I still have the suspicion that someone is interested in compromising calls for Signal because they are too secure.
Some hints are:
- calls are better on VPN 
- calls are better on mobile

**Comment by ryannathans** [comment]
> I still have the suspicion that someone is interested in compromising calls for Signal because they are too secure. Some hints are:
> 
>     * calls are better on VPN
> 
>     * calls are better on mobile

Not with 2 phones on the same wifi network. Same signal version. One works. One doesn't.

**Comment by bhlevca** [comment]
> Not with 2 phones on the same wifi network. Same signal version. One works. One doesn't.

So you are suggesting that is a hardware or an Android issue?
Do you have the same android version and same hardware?

**Comment by arnowelzel** [comment]
> So you are suggesting that is a hardware or an Android issue?
> Do you have the same android version and same hardware?

For the records - these devices do not work here:

- Google Pixel 6a with Android 13
- Fairphone 4 with LineageOS 20 (which is based on Android 13)

**Comment by ryannathans** [comment]
Broken: Motorola edge 30 running lineage, android 13, kernel 5.4.191-lineage

Working: Samsung S22 stock android 13, 5.10.136-android12-9

**Comment by bhlevca** [comment]
Working with many interruptions:
Google Pixel 6 Pro
Android 13
Kernel: 5.10.157-android13-4-00002-g0eacbbcce3d5-ab9881766
#1 Tue Apr 4 08:07:13 UTC 2023
Build: TQ3A.230605.010

**Comment by ryannathans** [comment]
Very interesting that you guys are getting interruptions now, when the patch from quite some time ago changed the behavior on my device from constant stutter/interruptions to massive delay

**Comment by bhlevca** [comment]
I get delays sometimes, but also interruptions. In fact a delay is a buffered interruption and there's not much of a difference in terms of usability.
Based on various experiences from different users , works well with VPN and on LTE, I still suspect some interference from the ISPs. The BPN  connection was over wi-fi therefore is in the wi-fi stack at fault.
