### ISSUE TITLE
Vibrate setting not remembered

### ISSUE THREAD

**Issue by simonboy77** [signalapp/Signal-Android#11987]
The setting:

Settings/Notifications/Messages/Vibrate

Always returns back to "on" when I set it to "off" after I close the settings and return. Same for another android phone I had close. Both running android 11.

Thank you for the awesome work you do!

**Comment by flyingfruits** [comment]
For me neither the vibration setting is remembered nor the sound setting. And I can't disable sound and vibration in android because signal creates a new notification category for each contact. All I can do for now is completely disable signal notifications until this is fixed.

**Comment by flyingfruits** [comment]
up

**Comment by icebruce** [comment]
This has beeb open for several months. Are  any plans for a fix? 

On a samsung phone and not able to disable the vibration in signal, need to mute all phone notifications, which is quite annoying.

**Comment by alex-signal** [comment]
We are working on some fixes for notification settings not persisting, but I'm not sure if these are 12+ only or for Android 11 as well.

**Comment by w1bsb** [comment]
I will mention this again simply because I encountered this issue with Android 12 and this is how I fixed it.  Go into Android Settings, Apps, Signal, Notifications, and turn off vibrate in each notification channel. The system will override the app setting. Some other users had issues doing this because signal was creating a separate notification channel for each contact (which shouldn't happen, but either way). This is what fixed it for me.  Don't even bother adjusting the notification settings in the app, because the built in android UI allows you to set everything. @icebruce give it a try and see what happens. It may fix your issue.

**Comment by icebruce** [comment]
@alex-signal  thanks for the update. Looking forward for a fix.

@w1bsb thanks for the tip. I am experimenting with this approach. So far not very successful. I did disable the vibration in the Android settings (for messages only) and was able to confirm that the Signal app finally registered the vibration as "off". Unfortunately still getting vibrations and have to mute the whole phone. Next will try disabling it for all channels/categories. I have to say I prefer to manage these kind of options per app tho, as it can get tricky after to keep track of the settings, but that's another topic.

**Comment by Seb-Solon** [comment]
I am facing the issue too, vibrating for each message is a bit annoying especially when you are on your phone. 

Disabling all channel vibration did not work either

**Comment by cody-signal** [comment]
Hi @Seb-Solon what version of Android and Signal are you running?

**Comment by Seb-Solon** [comment]
6.32.5. I could provide a debug log or something if you want.

**Comment by nicholas-signal** [comment]
A debug log would be helpful!

**Comment by Seb-Solon** [comment]
Updated to [6.34.5](https://debuglogs.org/android/6.34.5/4e09d96b72f646a58fc7095f1c0081596015b16ba1a3e7f9bf27bf66950ba25f). 

Let me know if you want me to open another issue to avoid mixing old issue with that :+1:

**Comment by nicholas-signal** [comment]
Thanks for the debug log! Consider this my reaction 👍
