### ISSUE TITLE
Importing backup crashes because of one faulty SQL statement

### ISSUE THREAD

**Issue by neo1992** [signalapp/Signal-Android#12057]
I see this issue: https://github.com/signalapp/Signal-Android/issues/7560, but it's not fixed at all it seems. I use version 5.33.1
However, my backup is 11.3GB. Whenever I try to restore Signal after filling out my recovery pass phrase it says "Checking" in a blue bar for 1/2 second and then closes the app. I've tried restarting multiple times. My old phone actually crashed completely so I HAVE to use this backup....
What can I do?

**Comment by TheLastGimbus** [comment]
When on home welcome screen, you can tap multiple times on blank space to open secret debug log

Import a backup, make it crash, then check the log. If the error matches with mine, my solution *could* help you: https://github.com/signalapp/Signal-Android/issues/12048#issuecomment-1065883028

**Comment by bepaald** [comment]
@neo1992 There was a bug in 5.33.1 that caused this behavior (crash before actually starting the import). This bug was fixed in 5.33.2 so I'd say: update and try again, it worked for me and at least a few others. However (as @TheLastGimbus mentioned) you might run into another bug with 5.33.2.

**Comment by neo1992** [comment]
@bepaald thanks! I updated to v 5.33.2. The process now continues and Signal starts restoring messages. However, Signal crashes after restoring ~10,000 messages. I can also see the log now, but it's crazy long. What string/error should I be looking for? And if I share the log fully through that Signal UI, is there any risk of exposing personal data?

**Comment by TheLastGimbus** [comment]
> it's crazy long

Yep. You want to quckliy open it back after crash and see red-collored error. It will probably look like one i gave in my comment, which i pasted above: https://github.com/signalapp/Signal-Android/issues/12048#issuecomment-1065883028

`Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)`

Look thought it to see if it also origns at ` at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:171`

...or somehow paste it here and i'll tell you

> is there any risk of exposing personal data?

Not much. No plain-text phone numbers etc. Look here: https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#debug-log-privacy

**Comment by neo1992** [comment]
OMG, I have the same error but I'm no developer and no idea how to install and use all those tools you mention (and frankly in line of user friendliness, not should Signal users be required to do so imo). Why is this crashing the restore and not simply ignoring the faulty message and completing the import? Seems like a critical bug to me?

**Comment by TheLastGimbus** [comment]
> Why is this crashing the restore and not simply ignoring

> not should Signal users be required to do so imo

Yep. Guys, I think we should make this bug more serious. @neo1992 could you rename the issue to something more specific like "Importing backup crashes because of one faulty SQL statement" ?

Meanwhile, please take a debug log and submit it here - there should be a nice big blue button on the bottom to share. Here is mine: https://debuglogs.org/android/5.33.2/6150bc425254fd77e92057b42bc8a666ffd3e8a09da9c9da1cc41bae62343142


@greyson-signal @cody-signal could you guys take a look at this? I know that "just ignoring SQL statements" sounds like it could bring hell-lot of new bugs, but maybe some of these are skipp-able (maybe empty `msl_payload`s aren't that important?) - it would be really nice

**Comment by neo1992** [comment]
https://debuglogs.org/android/5.33.2/9896cede7772cb3bc264c270cc9e219a04ac57da90a89d8e94ec77b495f09d6b

**Comment by neo1992** [comment]
I don't even want to know how many people don't bother to report this bug and just grudgingly accept to have lost their entire message history. This is not good for Signal adoption (a different "issue" is the lack of restoring messages to Signal Desktop from your mobile app)

**Comment by clauz9** [comment]
> https://debuglogs.org/android/5.33.2/9896cede7772cb3bc264c270cc9e219a04ac57da90a89d8e94ec77b495f09d6b

this should be fixed in 5.33.3 you can update to that and import your back-up, 

> I don't even want to know how many people don't bother to report this bug and just grudgingly accept to have lost their entire message history. This is not good for Signal adoption (a different "issue" is the lack of restoring messages to Signal Desktop from your mobile app)

the back-up crash has been fixed in 5.33.3, you should be able to update to that, and restore your back-up, why would this mean you lost your message history ?

**Comment by bepaald** [comment]
@clauz9 Well that's good news! Not sure how we were supposed to know, as there has been no comment on this issue so far.

I don't see anything in [the commit log](https://github.com/signalapp/Signal-Android/compare/v5.33.2...v5.33.3) that deals with this issue, could you link the commit that fixes this? I'd be very interested. Thanks!

**Comment by neo1992** [comment]
@clauz9 what I meant is that people who ran into this bug before me will have simply started from scratch again as they didn't know how to report it or simply didn't feel like it.   Hopefully I won't have that issue after updating. I dont see the update yet in the play store, not sure how long it will take.

**Comment by TheLastGimbus** [comment]
@clauz9 is right, your error is the previous "dropAllTables" one. Altough you can always crash with the second ("bad sql" one) after that :grin:

Oh, and it was fixed in `5.33.2`, not `.3` - it's already on play store if you sign up for the beta

**Comment by neo1992** [comment]
I indeed am in the beta and I'm already on version 5.33.2. But that log is from the latest version (you guys can probably see what version the log if from too). The crash on restore however still happens

**Comment by TheLastGimbus** [comment]
Oh crap... hm.... well that's weird...

Did you factory your app before importing ("clear app data") ? Maybe try that

**Comment by neo1992** [comment]
Ok, I checked, and I saw that there was a lot of data already there (I guess the restore did unpack a lot). I cleared everything via "Clear data", which cleared data and cache. I retried the retore, but the same crash happens again. I tried uninstalling and reinstalling Signal, but same issue
![Screenshot_20220314-122526_Settings](https://user-images.githubusercontent.com/7127039/158163536-2e5fcae5-422a-4476-8adc-38f231f1a8b9.jpg)
.

**Comment by neo1992** [comment]
Latest log https://debuglogs.org/android/5.33.2/374d74cefd4347f6cbce42431f46369b01d8b94b49fac623401e06771a47874a

**Comment by TheLastGimbus** [comment]
Ooookay, this time you have different error (in programming, that means a big success):

```java
[5.33.2] [main ] 2022-03-14 12:30:04.967 GMT+01:00 I RestoreBackupFragment: Prompt for backup passphrase shown to user.
[5.33.2] [344  ] 2022-03-14 12:30:10.323 GMT+01:00 I RestoreBackupFragment: Starting backup restore.
[5.33.2] [344  ] 2022-03-14 12:30:10.947 GMT+01:00 I FullBackupImporter: Ignoring import for statement: CREATE TABLE sqlite_sequence(name,seq)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: Bad MAC for attachment 1631471916053! Can't restore it.
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:401)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:183)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:116)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:88)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 	at java.lang.Thread.run(Thread.java:920)
[5.33.2] [344  ] 2022-03-14 12:31:18.485 GMT+01:00 W FullBackupImporter: 
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:920)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.lang.System.arraycopy(Native Method)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:417)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:357)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:109)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:88)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 	... 4 more
[5.33.2] [344  ] 2022-03-14 12:31:18.503 GMT+01:00 E SignalUncaughtException: 
```

A `bad MAC for attatchemt` one!!

Lucky you, the `signalbackup-tool` can probably fix that: https://github.com/bepaald/signalbackup-tools/#running

The issue that describes it: https://github.com/signalapp/Signal-Android/issues/8355 is closed :confounded: Idk what's @alan-signal statement on this, but here is his response: https://github.com/signalapp/Signal-Android/issues/8355#issuecomment-559240406

From what i see, this hurts people with very old backups, so they may not be prone to fix that

On the side note - sorry that you need to come though all of this. I know the pain :broken_heart:

**Comment by TheLastGimbus** [comment]
I've seen this too... @bepaald why is that? (i would run them in the CI if i would be you - you can cross-compile C++ for windows on l00nix ??)

**Comment by neo1992** [comment]
@TheLastGimbus not sure if you're asking me to do something? :) I'm a total N00b and was hoping there would be some Windows installer I could use to fix my backup

**Comment by TheLastGimbus** [comment]
No no, bepald needs to compile the tool... or I could do this, but I'm not sure if i can do it from linux to windoza, and if that will already include dependencies (openssl), or leave you with the pain of installing them too 🙄

(Tldr no, we're waiting for bebald

**Comment by bepaald** [comment]
>Ok, I want to install the tool on Windows but there are no releases? https://github.com/bepaald/signalbackup-tools/releases

Oops, sorry about that. I have this publishing Windows releases automated, but a change in openssl last week required me to update part of the automation manually, which I didn't do. Fixed now.

I see indeed you now have a BAD MAC in your debug log. This error does not indicate a bug in Signal, but corruption in your backup file, it would be great if you had another copy of it somewhere, or even an older, uncorrupted backup. Though my tool was (originally) designed to recover all information from corrupted backups, in my experience, looking at your debug log specifically, the two most likely scenario's are that either no information is left in the backup (so there is nothing to recover), or the recovered info does not constitute a valid backup file (that is, essential and required parts are missing).

In this last case, with enough custom programming (which I am always willing to try), often part of your messages can be recovered and imported into a new backup, but it will take time and corporation.

If you need help with the tool, you should probably open an issue at my github, as this is not a Signal-issue (I think in fact this issue should be closed). If you do open an issue, please show the output of running my program.

Also, since this turns out to not be the issue @TheLastGimbus had in #12048, I still think an issue for that could be opened.

**Comment by cody-signal** [comment]
@neo1992 please follow issue template in the future, it's there for a reason.

Bad MAC means a corrupt backup file. We are dedicating time in this upcoming quarter to add better verification/alerting of backup creation to help reduce these issues before they become ones. If you still have your old device, I'd recommend trying to create a new backup. If you don't, then you can try one of the community created tools to attempt to recover it.

**Comment by clauz9** [comment]
> @clauz9 what I meant is that people who ran into this bug before me will have simply started from scratch again as they didn't know how to report it or simply didn't feel like it.   Hopefully I won't have that issue after updating. I dont see the update yet in the play store, not sure how long it will take. 

we are talking about a beta version yes ? 
i think there's a warning somewhere about the dangers of running beta versions

**Comment by neo1992** [comment]
I was simply responding to your question as to why my message history would probably be lost. I'll stop giving feedback

**Comment by TheLastGimbus** [comment]
No @clauz9, we're not talking beta version - #8355 "bad mac" (that neo has) was here for 3.5 years

> 10 Nov 2018

**Comment by clauz9** [comment]
you think you can close this? @neo1992 
the crash has been fixed right ?

**Comment by zachpetersen** [comment]
I am currently hitting the Foreign Key Constraint issue with my transfer/backup&restore for my new device. I've also posted on this issue #11952 but I'm not sure if its related. I dont see the "MAC" issue in my logs.

https://debuglogs.org/android/5.53.4/4f76bebcd5dc8c69e529cfe54270e2b7ccbe139df7a59e9a1fe4febb1c18a6c1



```
10-21 13:39:10.783 29708 29928 I FullBackupImporter: Ignoring import for statement: CREATE TABLE sqlite_sequence(name,seq)
10-21 13:39:32.635 29708 29727 I crime.securesms: Background concurrent copying GC freed 235175(39MB) AllocSpace objects, 0(0B) LOS objects, 75% free, 12MB/49MB, paused 55us,37us total 103.132ms
10-21 13:41:04.542 29708 29727 I crime.securesms: Background concurrent copying GC freed 1121446(37MB) AllocSpace objects, 0(0B) LOS objects, 75% free, 13MB/54MB, paused 78us,35us total 105.795ms
10-21 13:41:07.172 29708 29926 D DeviceTransferServer: Handle message: 1004
10-21 13:41:07.172 29708 29926 D DeviceTransferServer: transferStatus: NETWORK_CONNECTED
10-21 13:41:07.172 29708 29928 W NetworkServerThread: null
10-21 13:41:07.172 29708 29928 W NetworkServerThread: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:155)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:99)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at org.thoughtcrime.securesms.devicetransfer.newdevice.NewDeviceServerTask.run(NewDeviceServerTask.java:46)
10-21 13:41:07.172 29708 29928 W NetworkServerThread: 	at org.signal.devicetransfer.NetworkServerThread.run(NetworkServerThread.java:98)
10-21 13:41:07.172 29708 29928 I NetworkServerThread: Server exiting
10-21 13:41:07.172 29708 29926 D DeviceTransferServer: Handle message: 1002
10-21 13:41:07.173 29708 29926 D DeviceTransferServer: transferStatus: SHUTDOWN
10-21 13:41:07.173 29708 29926 I DeviceTransferServer: Shutting down ServerThread
10-21 13:41:07.173 29708 29926 I DeviceTransferServer: Shutting down WiFi Direct
10-21 13:41:07.173 29708 29926 D WifiDirect: Shutting down
10-21 13:41:07.174 29708 29950 I WifiDirect: clear service requests success
10-21 13:41:07.174 29708 29950 I WifiDirect: stop peer discovery success
10-21 13:41:07.175 29708 29950 I WifiDirect: clear local services success
10-21 13:41:07.175 29708 29926 I DeviceTransferServer: Shutting down command and control
10-21 13:41:07.175 29708 29926 I DeviceToDeviceTransferS: Shutdown
10-21 13:41:07.184 29708 29708 D DeviceToDeviceTransferS: Intentionally no notification text for: SHUTDOWN
10-21 13:41:07.191 29708 29708 D DeviceToDeviceTransferS: Action: stop
10-21 13:41:07.191 29708 29708 I DeviceToDeviceTransferS: Shutdown
10-21 13:41:07.199 29708 29708 V DeviceToDeviceTransferS: onDestroy
10-21 13:41:07.200 29708 29708 W MessageQueue: Handler (android.os.Handler) {837d652} sending message to a Handler on a dead thread
10-21 13:41:07.200 29708 29708 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {837d652} sending message to a Handler on a dead thread
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:778)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:662)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Handler.sendEmptyMessage(Handler.java:647)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at org.signal.devicetransfer.DeviceTransferServer.stop(DeviceTransferServer.java:88)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at org.signal.devicetransfer.DeviceToDeviceTransferService.onDestroy(DeviceToDeviceTransferService.java:117)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4715)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2186)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Looper.loopOnce(Looper.java:201)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.os.Looper.loop(Looper.java:288)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-21 13:41:07.200 29708 29708 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-21 13:41:24.948 29708 29708 D LoggingFragment: [NewDeviceTransferFragme] onStop()
10-21 13:41:25.618 29708 29708 I ApplicationContext: App is no longer visible.
10-21 13:41:25.618 29708 29708 D DeadlockDetector: Ending deadlock monitoring.
```

**Comment by bepaald** [comment]
@zachpetersen Hi Zach, two things:

I think this probably deserves opening a new issue. The other one you linked to was about bad MAC errors (corrupted backup files). This is one, while the error is the same, had a known cause which was fixed (which is why the issue is closed). Was this backup created by an old version of Signal that may still have contained this problem? Otherwise, you should probably open a new issue.

If you can't or don't want to wait for an official response and solution, I have written [a program](https://github.com/bepaald/signalbackup-tools) that could help (_no promises!_). If you decide to try this, run it on your backup with the `--checkdbintegrity` option and open an issue on my github with the results, we might be able to fix the issue. Also, the output of the program might be useful for the issue you open here.

**Comment by zachpetersen** [comment]
@bepaald thank you for your reply. Unfortunately I've had to move on and get my old device sent back to Google. I didn't try the ```--checkdbintegrity``` parameter with your app but I did try a few other things. Regarding versions I keep signal up to date with the beta versions and as you mentioned the issue I am seeing is probably not linked to the specific problem in 12057. 

I will check my new device and see if I left one of the old backups there and if so I'll give it a check and open a new issue with you if there is something interesting. Again, I appreciate your response. Thank you!
