### ISSUE TITLE
Voice messages cannot be listened to via earpiece

### ISSUE THREAD

**Issue by hindicc71** [signalapp/Signal-Android#12140]
### Bug description
Voice messages cannot be listened to via earpiece (hold to ear and listen). This used to work for a while, currently the audio stops as soon as I hold the phone (Android) to my ear and I can only listen to the voice message again when I delete the signal from the cache. Otherwise, I can no longer play them.

### Steps to reproduce
see the description above

**Actual result:** Audio stops completely and also does not play at all. I have to clear the cache first to be able to listen to any voicemail again.
**Expected result:** The voice message should be played normally over the listening speakers.

### Device info
**Device:** Samsung Galaxy S9
**Android version:** 10
**Signal version:** 5.34.10

**Comment by newhinton** [comment]
I think this is the same as #11922
Can you check that issue and close it if it is the same?

**Comment by hindicc71** [comment]
> I think this is the same as #11922 Can you check that issue and close it if it is the same?

No, it is not the same.
In your linked case, there is a Bluetooth connection and the voice message is played for 20% and then it stops.

What I'm describing has nothing to do with a Bluetooth connection and if I want to play a voicemail but listen to it quietly through the earpiece, it plays 0%. The app then freezes and no voice message can be played at all. Neither the current one that you want to listen to nor any other. This play button then also no longer works.

So no, please do not close my case, because I am describing something completely different here.

**Comment by mtts0** [comment]
Same exact problem here using a Samsung device—Android 11 with OneUI 3.1. The problem happens using either the stable version of the app or the beta. When I bring the phone close to my ear, the screen turns off for a brief moment and that stops the audio playing, then the screen turns while the message is not playing anymore.

And also if I go back to the app and try to play the same voice message I was listening to the app doesn't play the message until I either (1) play another different message on the conversation I am in (2) or go back to the "all conversations screen" and then return to the conversation in order to play the stopped message.

Please solve this as it is really annoying.

**Comment by cody-signal** [comment]
https://github.com/signalapp/Signal-Android/issues/7576

**Comment by f0lg0** [comment]
> Same exact problem here using a Samsung device—Android 11 with OneUI 3.1. The problem happens using either the stable version of the app or the beta. When I bring the phone close to my ear, the screen turns off for a brief moment and that stops the audio playing, then the screen turns on while the message stops playing.
> 
> And also if I go back to the app and try to play the same voice message I was listening to the app doesn't play the message until I either (1) play another voice message on the conversation I am currently in (2) or go back to the "all conversations screen" and then return to the conversation in order to play the stopped message.
> 
> Please solve this as it is really annoying.

exactly the same behavior as the one I'm getting.

**Comment by newhinton** [comment]
As of now, this has not been fixed, so not stale. (Though, thanks for working on it!)

**Comment by mtts0** [comment]
> We are working on it. We had a fix that was hopeful to go out into the next beta but it required us to target Android 12 directly which ends up breaking things in an even more impactful way.

Six -- six -- 6 months later and this HASN'T BEEN SOLVED YET. How is it possible that level of incompetence? It is bizarre that if I answer a voice call I can listen via the earpiece no problem. But not voice messages. Six fck' months!!! Just solve this issue!!!

**Comment by greyson-signal** [comment]
@mtts0 Hi there, I understand the frustration, but that isn't a respectful way to communicate with other people. We're all real human beings here :)

**Comment by mtts0** [comment]
Ok, @greyson-signal. It is not respectful and polite to supporters and donors that such a simple issue takes more than 6 months to be solved. Seems that no one cares.

**Comment by greyson-signal** [comment]
I think you're making the incorrect assumption that this is a simple issue. There was a lot of weirdness and nuance that made it difficult to fix before. I think we've made some changes recently as we work to target Android 12 that will make this easier though. We'll take another look :+1:

**Comment by greyson-signal** [comment]
Also know that we really do care, and we put a lot of time into this project. But resources are always limited, and there are so many things to care about. Sometimes we prioritize things differently than you, and sometimes things get temporarily lost, but  work is always happening (you can always look at our [commit history](https://github.com/signalapp/Signal-Android/commits)). But like I said, we'll take another look at this one.

**Comment by newhinton** [comment]
I agree with you that development often seems slow with signal, and that sometimes deserves a bump for attention in a polite way.

However, i highly disagree how you voice that grievance, and you should probably be more kind next time you ask for an update. Beenig firm can be acceptable, beeing aggressive, rude and cursing at people is just not okay.

**Comment by mtts0** [comment]
Ok @greyson-signal, I hope the issue gets solved. All the best for you and the team. And I am sorry if I was too aggressive.

**Comment by Jowat97** [comment]
> Also know that we really do care, and we put a lot of time into this project. But resources are always limited, and there are so many things to care about. Sometimes we prioritize things differently than you, and sometimes things get temporarily lost, but work is always happening (you can always look at our [commit history](https://github.com/signalapp/Signal-Android/commits)). But like I said, we'll take another look at this one.

I really hope your are joking. "Sometimes we prioritize things differently than you". This bug is there for more than 4,5 years! Check: #7576 

But instead of fixing this serious bug, Signal introduced stuff like reactions, donations and dozens of other functions. People tried to offer help, logs etc. but there are no replies from you other than "we are working on it, for almost 5 years". Yeah, sure..

Every other messenger and I mean literally every other messenger like WA, Telegram, Wire, Facebook messenger etc. can do this easily. But Signal is the only one which is not able to do so. People even tried to make forks of Signal and could have solved it in the forked version, but it was YOU denying forked versions and forbid F-Droid to host Signal with flimsy excuses: https://github.com/signalapp/Signal-Android/issues/9966#issuecomment-681943985
(I know moxie0 was the one denying it in first place, but he isn't CEO anymore)

Please don't get me wrong. I really appreciate your work and effort but I have friends leaving Signal and going back to WhatsApp because of this bug. That's really sad and will hurt Signal in a long term very hard! And all you say is "we are working on it but have other priorities"?! Like being able to hear voice messages on the messenger is not important but reactions, new stickers or redesigns are? What annoys me the most is that many people offer their help and suggest solutions. But nothing comes from you other than "we're working on it... *for 5 years*" and that's really frustrating..

Just one last thing: Telegram is using the exact same ExoPlayer V2 you are using and it works perfectly. May take a look on their source code? Already mentioned it more than 2 years ago: https://github.com/signalapp/Signal-Android/issues/7576#issuecomment-683319273

**Comment by f0lg0** [comment]
> > Also know that we really do care, and we put a lot of time into this project. But resources are always limited, and there are so many things to care about. Sometimes we prioritize things differently than you, and sometimes things get temporarily lost, but work is always happening (you can always look at our [commit history](https://github.com/signalapp/Signal-Android/commits)). But like I said, we'll take another look at this one.
> 
> I really hope your are joking. "Sometimes we prioritize things differently than you". This bug is there for more than 4,5 years! Check: #7576 
> 
> But instead of fixing this serious bug, Signal introduced stuff like reactions, donations and dozens of other functions. People tried to offer help, logs etc. but there are no replies from you other than "we are working on it, for almost 5 years". Yeah, sure..
> 
> Every other messenger and I mean literally every other messenger like WA, Telegram, Wire, Facebook messenger etc. can do this easily. But Signal is the only one which is not able to do so. People even tried to make forks of Signal and could have solved it in the forked version, but it was YOU denying forked versions and forbid F-Droid to host Signal with flimsy excuses: https://github.com/signalapp/Signal-Android/issues/9966#issuecomment-681943985
> (I know moxie0 was the one denying it in first place, but he isn't CEO anymore)
> 
> Please don't get me wrong. I really appreciate your work and effort but I have friends leaving Signal and going back to WhatsApp because of this bug. That's really sad and will hurt Signal in a long term very hard! And all you say is "we are working on it but have other priorities"?! Like being able to hear voice messages on the messenger is not important but reactions, new stickers or redesigns are? What annoys me the most is that many people offer their help and suggest solutions. But nothing comes from you other than "we're working on it... *for 5 years*" and that's really frustrating..
> 
> Just one last thing: Telegram is using the exact same ExoPlayer V2 you are using and it works perfectly. May take a look on their source code? Already mentioned it more than 2 years ago: https://github.com/signalapp/Signal-Android/issues/7576#issuecomment-683319273

yea this is definitely getting out of hand, it's been close to a full year of me being active in #7576 and yet no hints of progress other than "we are working on it". As you said this is a far more critical feature than reactions and new stickers and it is sad that people are leaving Signal for it. I still want to have faith in Signal developers but tbh I'm considering a switch too...

**Comment by mtts0** [comment]
> I really hope your are joking. "Sometimes we prioritize things differently than you". This bug is there for more than 4,5 years! Check: https://github.com/signalapp/Signal-Android/issues/7576

But hey! Now we have "Signal Stories" which is way more important than listening to voice messages privately. 🚀🚀🚀

By the way, "Signal Stories" were disabled on Day 1 here...

The Signal team might introduce Cake Day for this "minor" issue. Maybe a monthly cake day sent via the Signal Stories feature that was prioritized. ;)

**Comment by alex-signal** [comment]
Hi, one of our devs just got their hands on an A51 and is able to reproduce, and will be looking into this issue.

**Comment by Jowat97** [comment]
> Hi, one of our devs just got their hands on an A51 and is able to reproduce, and will be looking into this issue.

Wow, 5 years after dozens of people complaining about such a critical bug you guys decided to reproduce it and want to look at it?! Amazing! So, in the previous 5 years literally nothing happend about this? But I guess, you just "prioritize things differently than us", right? Signal Stories was released today. Thanks therefor, that's what the community really care about. Who needs working voice messages, if we can have stories instead, which no one uses, since people are leaving Signal because of bugs like this. "Priorities", yeah...

**Comment by mtts0** [comment]
> Hi, one of our devs just got their hands on an A51 and is able to reproduce, and will be looking into this issue.

Looks like the issue is finally fixed on my Samsung device. At least it is working here on version 6.2.0 (Beta). Thank you!!! I will make a donation to the Signal Foundation!

**Comment by Jowat97** [comment]
> > Hi, one of our devs just got their hands on an A51 and is able to reproduce, and will be looking into this issue.
> 
> Looks like the issue is finally fixed on my Samsung device. At least it is working here on version 6.2.0 (Beta). Thank you!!! I will make a donation to the Signal Foundation!

Just applied for the beta program, downloaded the latest beta (6.2.1) and still same issue with my A12 device.

**Comment by mtts0** [comment]
> downloaded the latest beta (6.2.1)

I updated earlier today to 6.2.0 and it is still working. I just checked and now there is this 6.2.1 available and I will try to avoid updating to this version until someone else reports the issue has not returned. Maybe @alex-signal can confirm whether or not the issue has been solved.

**Comment by mtts0** [comment]
> I updated earlier today to 6.2.0 and it is still working.

Updated to version 6.2.1 (Beta) on a Samsung Galaxy device (Android 12, OneUI 4.1) and listening to voice messages via the earpiece continues working just fine. Thanks to the team!

**Comment by Jowat97** [comment]
> > I updated earlier today to 6.2.0 and it is still working.
> 
> Updated to version 6.2.1 (Beta) on a Samsung Galaxy device (Android 12, OneUI 4.1) and listening to voice messages via the earpiece continues working just fine. Thanks to the team!

Could you maybe try this?
Close Signal completely, lower the media-volume to 0 and then open signal and play a voice message. It will play, but without any sound since media volume is set to 0. But while it is playing noiseless and the earpiece is triggered, it will start playing from the main speaker again. Either for a short period of time or completely.

If media volume is set to 0, the problems seems to occur with the latest beta.

**Comment by mtts0** [comment]
> But while it is playing noiseless and the earpiece is triggered, it will start playing from the main speaker again. Either for a short period of time or completely.

I tried replicating this issue here but couldn't. If I set "Media Volume" to 0 and play a voice message, it plays without any sound as it is expected. If I trigger the earpiece I can listen to the voice message on the earpiece (there is sound) while the proximity sensor is activated. When I remove the device away from my ear the sound stops playing completely (it pauses the voice message). In order to play the message at the point it stopped playing I hit play and it continues playing without any sound.

On my device, while listening to a voice message, if I use the volume buttons to increase or decrease the volume and quickly remove the device away from my ear I am presented with a on screen "soft menu" with a 3-dot option. If I click on these 3-dots I am presented with a menu with an additional volume setting: "In-call volume". While listening to a voice message —even if "Media Volume" is set to 0— the message continues playing as the "In-call volume" is not set to zero.  According to Samsung documentation I found online "You are only able to adjust the in-call volume when on a call."¹

By testing the "In-call volume" while listening to a voice message it cannot be set to zero either by the volume buttons or the soft menu. Therefore, even if "Media Volume" is set to 0, since "In-call volume" can never be set to 0 there will always be a sound while playing a voice message on the earpiece.

I don't know if this helps by any means but the issue you asked me to try to replicate didn't work as you described on my end.

¹ https://www.samsung.com/in/support/mobile-devices/adjusting-the-volume-on-my-samsung-galaxy/

**Comment by greyson-signal** [comment]
@mtts0 Thank you very much for taking the time to do all of that testing.

@Jowat97 This has always been an issue that only affected a subset of devices (aka it generally worked and we couldn't reproduce it on most phones -- one of the reasons this took longer to get to). I wouldn't be surprised if it worked on one device but not another. If you could submit more logs that would be helpful. Thanks!

**Comment by Jowat97** [comment]
> @mtts0 Thank you very much for taking the time to do all of that testing.
> 
> @Jowat97 This has always been an issue that only affected a subset of devices (aka it generally worked and we couldn't reproduce it on most phones -- one of the reasons this took longer to get to). I wouldn't be surprised if it worked on one device but not another. If you could submit more logs that would be helpful. Thanks!

@mtts0  Thanks for the amazing feedback and testing!

@greyson-signal I am currently using a Smartphone from BKK Electronics (https://en.wikipedia.org/wiki/BBK_Electronics)
They have following brands: Oppo, OnePlus, Realme, Vivo and iQOO. Maybe all of these are affected as well (and maybe others too?). Android Version is 11. Seems like the problem is partly fixed with latest beta (6.2.1). But still occurs if volume is set to 0. Of course I can provide logs! 😉

I have done following: Set volume to 0, played a voice message: No sound while playing. Then triggered earpiece sensor. The first second it played from the earpiece speaker, but then switched to the main speaker. I have logged it. Due to privacy reasons I have removed some unnecessary private stuff from the logs. If more Information is needed, feel free to ask! I am opted in to the beta program, and can provide logs, information, testings etc. Everything which is needed to fix this issue! 😃

[log - Signal.zip](https://github.com/signalapp/Signal-Android/files/10003742/log.-.Signal.zip)

**Comment by Jowat97** [comment]
@mtts0 @cody-signal 
Unfortunately, the bug still occurs. I tried to play a voice message via earpiece by triggering the sensors. Volume was on default, device wasn't set to silent mote etc. But still played from main speaker instead of earpiece speaker..

I have grabbed some logs:
[log2- Signal.zip](https://github.com/signalapp/Signal-Android/files/10014213/log2-.Signal.zip)

btw: Do you also need the information above LOGCAT too or is everything below enough?

**Comment by Femight13** [comment]
How are you doing

**Comment by f0lg0** [comment]
switched back to whatsapp :D

**Comment by RobertZenz** [comment]
This is still an issue as of 7.33.2, on a OnePlus 6 with Android 10 (though, I have a friend which sees the same on a newer phone, with Android 12 I think). You cover the proximity sensor, Signal turns the screen off and the message stops playing immediately.

Super bad, it basically means that you can't listen to audio messages in a private manner.

**Comment by RobertZenz** [comment]
That said, I believe the relevant part of the log is this:

```
[7.35.0] [main ] 2025-03-07 16:26:22.671 GMT+01:00 D VoiceNotePlaybackServic: [onPlaybackStateChanged] playbackState: Player.STATE_READY	playWhenReady: true
[7.35.0] [main ] 2025-03-07 16:26:22.692 GMT+01:00 D VoiceNoteProximityWakeL: [onPlaybackStateChanged] Player became active with start time -1, registering sensor listener.
[7.35.0] [main ] 2025-03-07 16:26:22.692 GMT+01:00 D VoiceNoteProximityWakeL: [onPlaybackStateChanged] Acquiring wakelock
[7.35.0] [main ] 2025-03-07 16:26:22.872 GMT+01:00 D BaseActivity: [MainActivity] onStop()
[7.35.0] [main ] 2025-03-07 16:26:22.872 GMT+01:00 D LoggingFragment: [ConversationListFragmen] onStop()
[7.35.0] [main ] 2025-03-07 16:26:24.638 GMT+01:00 I VoiceNotePlaybackServic: onAudioAttributesChanged: Setting audio stream to 0
[7.35.0] [main ] 2025-03-07 16:26:25.288 GMT+01:00 I VoiceNotePlaybackServic: onAudioAttributesChanged: Setting audio stream to 3
[7.35.0] [main ] 2025-03-07 16:26:25.290 GMT+01:00 D VoiceNoteProximityWakeL: [onSensorChanged] Releasing wakelock
```

`STREAM_VOICE_CALL == 0`, `STREAM_MUSIC == 3`. With this part in `VoiceNoteProximityWakeLockManager`:

```kotlin
      val newStreamType = if (event.values[0] < PROXIMITY_THRESHOLD && event.values[0] != proximitySensor?.maximumRange) {
        AudioManager.STREAM_VOICE_CALL
      } else {
        AudioManager.STREAM_MUSIC
      }

      sendNewStreamTypeToPlayer(newStreamType)

      if (newStreamType == AudioManager.STREAM_VOICE_CALL) {
        startTime = System.currentTimeMillis()
      } else {
        if (wakeLock?.isHeld == true) {
          Log.d(TAG, "[onSensorChanged] Releasing wakelock")
          wakeLock.release()
        }
      }
```

Most curiously, on a second attempt the order of the log lines is different:

```
[7.35.0] [main ] 2025-03-07 16:42:11.469 GMT+01:00 D VoiceNotePlaybackServic: [onPlaybackStateChanged] playbackState: Player.STATE_READY	playWhenReady: true
[7.35.0] [main ] 2025-03-07 16:42:11.471 GMT+01:00 D VoiceNoteProximityWakeL: [onPlaybackStateChanged] Player became active with start time -1, registering sensor listener.
[7.35.0] [main ] 2025-03-07 16:42:11.471 GMT+01:00 D VoiceNoteProximityWakeL: [onPlaybackStateChanged] Acquiring wakelock
[7.35.0] [main ] 2025-03-07 16:42:14.817 GMT+01:00 I VoiceNotePlaybackServic: onAudioAttributesChanged: Setting audio stream to 0
[7.35.0] [main ] 2025-03-07 16:42:16.992 GMT+01:00 D VoiceNoteProximityWakeL: [cleanUpWakeLock] Releasing wake lock.
[7.35.0] [main ] 2025-03-07 16:42:16.994 GMT+01:00 I VoiceNotePlaybackServic: onAudioAttributesChanged: Setting audio stream to 3
```

**Comment by RobertZenz** [comment]
With one of the latest versions a funny detail sneaked into this bug. If you cover the proximity sensor by accident while listening to a message, the playback will stop as reported. However, the playback volume will also drop to ~50% of the normal volume for subsequent playback (read, messages are played back with very low volume).

One needs to force-stop Signal to reset that bug.

**Comment by rearl** [comment]
On my Google Pixel 7 listening voice messages via earpiece (not Bluetooth) is not possible with Signal version 7.51.2 on Android v16.

**Comment by at4rka** [comment]
I have had similar experiences with different devices in the past (and today). It seems the readings of the proximity sensor are a bit buggy/inconsistent. When playing a voice-memo and holding the phone to my ear, it might stop instantly or play for a few seconds, or minutes if I am lucky. I never have this problem with apps such as WhatsApp.

It happens both on Fairphone 4 (Android 13) and Samsung Galaxy S25 (Android 15). I'll see if I can pull logs from both devices later today.

EDIT: I do not have cache issues like in the original issue description

**Comment by mjohenneken** [comment]
For me this happens of 8.4.1 on Samsung A51
