### ISSUE TITLE
Messages only received when opening the App after Update to 5.41.11

### ISSUE THREAD

**Issue by billie80** [signalapp/Signal-Android#12325]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I receive messages only if I open the App. This happened after the recent stable update to 5.41.11. There was no OS or other relevant Update I can think of in between. I already deleted App data and reinstalled from a backup but the behaviour is the same. I also went through the [Troubleshooting Notifications](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications) support page to make sure there is nothing missing regarding the setup.
 
### Steps to reproduce
- Ask a friend to send a message
- Notice that there is only one check mark at friends phone
- Open signal
- The message is immediately received and the notification pops up.

**Actual result:** Messages are only received when opening the App.
**Expected result:** A notification should inform about new messages.

### Device info

**Device:** Shiftphone Shift6mq
**Android version:** 10
**Signal version:** 5.41.11

### Link to debug log

https://debuglogs.org/android/5.41.11/3f3a6f4ddc385a9cf071e28d2b7e887fed31d39290500532fb245ee90b01c6ae

**Comment by userj** [comment]
I have the same issue.
Not sure if it's the same bug as this:
https://github.com/signalapp/Signal-Android/issues/12136

**Comment by billie80** [comment]
Thanks, I have read this. There @cody-signal mentioned problems on Android 12. As I am still on Android 10 I thought it might be a different issue and thus opened a new one.

**Comment by billie80** [comment]
Still the same problem with 5.41.13.
@userj from your logs on the other issue it seems that the issue is similar but the exception is slightly different
In your logs the messages say something about the BackgroundServiceStartNotAllowedException:

```
[5.41.11] [2335 ] 2022-06-30 09:05:27.370 PDT I FcmFetchManager: Starting in the background.
[5.41.11] [2335 ] 2022-06-30 09:05:27.372 PDT W FcmFetchManager: Failed to start service!
[5.41.11] [2335 ] 2022-06-30 09:05:27.372 PDT W FcmFetchManager: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=org.thoughtcrime.securesms/.gcm.FcmFetchBackgroundService }: app is in background uid UidRecord{efa4069 u0a167 RCVR bg:+14m16s577ms idle change:uncached procs:0 seq(0,0,0)}
```

In my case it is an IllegalStateException:

```
[5.41.11] [674  ] 2022-06-30 18:26:07.012 GMT+02:00 I FcmFetchManager: Starting in the background.
[5.41.11] [674  ] 2022-06-30 18:26:07.015 GMT+02:00 W FcmFetchManager: Failed to start service!
[5.41.11] [674  ] 2022-06-30 18:26:07.015 GMT+02:00 W FcmFetchManager: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.thoughtcrime.securesms/.gcm.FcmFetchBackgroundService }: app is in background uid UidRecord{48343de u0a155 RCVR bg:+10m44s229ms idle change:uncached procs:1 seq(0,0,0)}
```


In both cases the FcmFetchBackgroundService is not allowed to start which might be the reason for not getting notifications.

Maybe this is due to different versions of Play Services being installed on our devices. This might well be the case as I don't have them at all but microG is doing it's job instead.

**Comment by userj** [comment]
I am running Lineage for microG, so I'm also using microG rather than play services.

Thanks for digging into that. Is there a way to manually force FcmFetchBackgroundService to start as a temporary workaround?

Same error with manual start:
`adb shell am startservice org.thoughtcrime.securesms/.gcm.FcmFetchBackgroundService
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.thoughtcrime.securesms/.gcm.FcmFetchBackgroundService }
Error: Requires permission not exported from uid 10167`

Tried with a root shell and error:
` # am startservice org.thoughtcrime.securesms/.gcm.FcmFetchBackgroundService
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.thoughtcrime.securesms/.gcm.FcmFetchBackgroundService }
Error: app is in background uid UidRecord{2abcd26 u0a167 CAC  bg:+25m18s462ms idle change:idle procs:0 seq(0,0,0)}`

**Comment by billie80** [comment]
I don't think staring the service manually makes sense as enqueue from [FcmFetchManager](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/gcm/FcmFetchManager.kt) is started from [FcmReceiveService](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/gcm/FcmReceiveService.java) in handleReceivedNotification.

I think the relevant commit is https://github.com/signalapp/Signal-Android/commit/523f9c74098252ad40fab6c543c064f225a94380. Due to this an exception occurs. Strangely the error should have occurred also before but then somehow the fetch worked anyway. Maybe due to the exception the fallback to the legacy approach retrieveMessages from FcmFetchManager is not executed.

Mind this is me only guessing. No Android programmer here. I just try to make sense of the code.

**Comment by pflanzenandi** [comment]
> I am running Lineage for microG, so I'm also using microG rather than play services.

I have the same problem. Lineage (Android12) and microG. Tried reinstalling Signal and re-registering Signal to microG GCM.

**Comment by billie80** [comment]
> I have the same problem. Lineage (Android12) and microG. Tried reinstalling Signal and re-registering Signal to microG GCM.

Might be a good idea to also attach a debug log to verify if it is really the same issue.

**Comment by pflanzenandi** [comment]
[log](https://debuglogs.org/android/5.41.13/9874c70a179859f73e164eefdcd3e771c3031cb77b40e77de5c130fe1c8cceb9)

**Comment by greyson-signal** [comment]
@billie80 Your device is doing something weird. We only send high-priority FCM pushes, but your device is setting the priority as `PRIORITY_UNKNOWN`. Normally Android grants you an execution window to start services when you receive a high priority FCM push, but because your device is losing that info, it's not giving us that execution window, causing us to crash when we try to do work.

I know you said you hadn't received any system updates, but I can confirm that other OEMs (I don't know specifically about SHIFT) will push silent remote updates around notification behavior in the name of battery optimization. I would not be surprised if SHIFT did the same.

I'll think about it and see if there's anything we can do.

**Comment by pflanzenandi** [comment]
I also didn't receive any updates, because I need to flash them manually. The problem definitely occurred (I think) with 5.41.13 or an earlier 5.41. build. I downgraded to 5.40.4.1 and all notifications are getting pushed, even in deep sleep / doze (or whatever it is called nowadays). 

Here are the logs from both versions:
[5.41.13](https://debuglogs.org/android/5.41.13/9874c70a179859f73e164eefdcd3e771c3031cb77b40e77de5c130fe1c8cceb9)
[5.40.4.1](https://debuglogs.org/android/5.40.4/7201460e7ba9405062c4d1a1cdd45bc3dbaa64ee0ac3968d3cb2d0184aada1c1)

**Comment by userj** [comment]
@pflanzenandi would you be able to recommend a safe way to obtain the older version apk ?

**Comment by temporarium** [comment]
I can confirm that downgrading to 5.40.4.1 fixed the issue for me as well. I guess instead of fiddling with the "looks", let's make sure the engine works ;-)

I used Aurora store to manually download version 106406.

**Comment by userj** [comment]
> I can confirm that downgrading to 5.40.4.1 fixed the issue for me as well. I guess instead of fiddling with the "looks", let's make sure the engine works ;-)
> 
> I used Aurora store to manually download version 106406.

Thank you for this. Slightly off-topic question, but how do you know which version number to put in there? i.e. where do you find that? Thanks! 

P.S. Downloading that from Aurora store and reinstalling did indeed resolve the notification issue.

**Comment by billie80** [comment]
@greyson-signal Thank you very much for getting back to me/us :-)
I am close to the development of ShiftOS which is running on the device. So I am pretty sure there was no update. Latest was May 11th. The only thing which is updated during system updates is webview but it was also last updated on May 11th. This is why most likely the only difference is the latest Signal update as there was more than one release since that.

**Comment by greyson-signal** [comment]
@billie80 There *should* be a fix in 5.41.14, which should be available soon. Of course after I fixed it, I came here to let ya'll know, and just now I noticed [this comment of yours](https://github.com/signalapp/Signal-Android/issues/12325#issuecomment-1173046839) that describes exactly what the problem was. If I read more closely I probably wouldn't have suggested other things :) Thanks!

**Comment by billie80** [comment]
@greyson-signal Thank you very much for taking care of this. It means a lot!
I will ask regarding the priority reset and let you know if there is feedback.

**Comment by billie80** [comment]
@greyson-signal I checked my log again and can not find anything regarding priority unknown. I guess you are talking about the logs from FcmReceiveService onMessagereceived and  handleReceivedNotification which contain Priority, Original Priority and RemoteMessagePriority. All of them are 0. How should it look like? Or do you mean something else?

**Comment by userj** [comment]
I might missed something but I still have this issue as of 5.41.14 :
https://debuglogs.org/android/5.41.14/39b846440f69b42fc82eb0dbfe80fef625a1b595ec0fe95921df41f557da8547

**Comment by greyson-signal** [comment]
@userj 
> I might missed something but I still have this issue as of 5.41.14

The specific bug billie80 hit is fixed, but your OS is preventing us from doing any work in the background. It's a separate but related issue. Looks like OnePlus is downgrading our high-priority FCM push to `PRIORITY_UNKNOWN` and thus not giving us our execution window, but then is also disallowing us from doing any network activity in the receiver by not giving us any network access. When that failed we scheduled a JobScheduler job to fetch messages later, but it didn't get a chance to run before you foregrounded the app.

I honestly don't know what to do in this situation. Starting a service, doing network inline, and scheduling a job for later are all the mechanisms we have available to try to do a network request, and OnePlus has decided to let us do none of them. We'll have to think about it more. Feel free to continue discussion in #8692, which is our catch-all for notification issues like this. Also, per usual, make sure there aren't any battery optimizations in your settings that would prevent us from running

@amartinz Hi there! It sounds like it very well could be microg, wouldn't be surprised if it did something funny with changing priorities. But apparently OnePlus is doing something similar, so who knows. I suppose my only question would be "Do you know why an incoming FCM message would have it's priority set to `PRIORITY_UNKNOWN`?" But given you're not replacing GApps yourself, maybe you don't have any visibility there.

**Comment by billie80** [comment]
I took a look at the microG issue tracker and found the following commit https://github.com/microg/GmsCore/commit/60023887d101a272f01425bf7f130576960acd50. So it seems microG should treat high-priority pus notifications properly. As why there might be a change in priority is beyond my skills.

To get more insight why this might happen I opened an issue https://github.com/microg/GmsCore/issues/1745 at the microG issue tracker.

**Comment by cyberpunkedu** [comment]
@billie80 Thanks for looking into this more. This seems to be a workaround for me using microG:

`adb shell dumpsys deviceidle whitelist +org.thoughtcrime.securesm`

**Comment by billie80** [comment]
Isn't this basically disabling battery optimisation? In the UI it tells me this is not available for Signal!

While looking at the microG commits there was a recent one https://github.com/microg/GmsCore/commit/3e733135059a71550ff00ccc61588c028260856f which might improve the situation for those already on Android 12.
