### ISSUE TITLE
Sending Long Message Breaks Scrolling Down Conversation

### ISSUE THREAD

**Issue by inferenceus** [signalapp/Signal-Android#12355]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a long message (e.g. 100+ words), Signal does not allow scrolling down to the most recent message sent (which is the long message just sent), it jumps back up the conversation when attempting to do so; the scroll-to-bottom button has the same effect.

### Steps to reproduce
- Send long message (100+ words).
- Attempt to scroll down to most recently sent long message.

**Actual result:** Can no longer scroll to bottom of conversation.
**Expected result:** Scrolling to bottom of conversation works as intended.

### Screenshots
Not applicable.

### Device info

**Device:** Google Pixel 4a (5G)
**Android version:** 12.1 (GrapheneOS 2022071300)
**Signal version:** 5.42.8

### Link to debug log
https://debuglogs.org/android/5.42.8/9f4d66ab8027421eb848a74569dc2bf3f844c112a5e58009347a50985827d3fa

**Comment by inferenceus** [comment]
Updated Signal to version 5.43.7; same issue.

**Comment by inferenceus** [comment]
Updated GrapheneOS to version 2022072000; same issue.

**Comment by jcookin** [comment]
Experiencing the same issue on v5.43.7, Oxygen OS 11.0.6

**Comment by Lucas32578** [comment]
Same issue on a pixel 5a with grapheneos, been an issue for a few weeks now and ive been keeping both my os and the app updated to the latest release on the beta version the whole time. Signal beta is installed and auto updated through the google play store but ive heard of people having this issue with non beta editions of both the app and the OS. Really annoying and often app breaking bug, been having to fall back to whatsapp for longer messages. Not fun.

**Comment by cody-signal** [comment]
This is fixed in the latest beta and will be going to prod tomorrow.

**Comment by inferenceus** [comment]
The latest update seemed to not increase the version number, which was confusing. Both old and new versions are both 5.43.7; I discovered this through the build numbers.

After installing the update of 2022-07-27, the issue has not been fixed and the scrolling issue still occurs for me; sending a long message causes the scrolling to bounce back up the conversation, forcing me to send a short message after the long one in order to scroll down again.

**Comment by cody-signal** [comment]
The latest beta is 5.44.3, it's currently at 25% prod rollout.

**Comment by inferenceus** [comment]
Is this stable rollout? I'm not using beta.

**Comment by inferenceus** [comment]
Is there an ETA for the Signal website APK?

**Comment by cody-signal** [comment]
This will likely hit the website APK Monday.

**Comment by inferenceus** [comment]
Can confirm Signal version 5.44.3 fixes the issue.
