### ISSUE TITLE
Signal crashes when starting the App

### ISSUE THREAD

**Issue by DomeGamer14** [signalapp/Signal-Android#12626]
- [x] I have searched open and closed issues for duplicates
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My Signal App suddenly stopped working this afternoon. Every time I open it now, it just immediately closes again.
I have been using Signal for over 2 years and have never experienced this bug. This has also never happened before on my current phone.

### Steps to reproduce
- Open the Signal App

**Actual result:** The App closes / crashes
**Expected result:** The App starts as intended

### Device info

**Device:** Volla Phone 22 (Gigaset GS5)
**Android version:** 11.1
**Signal version:** 6.1.4

### Link to debug log

Since I cannot open the App, I cannot get a debug log.

 I really need Signal to work again, since this currently is the only way that I am reachable by others.

**Comment by DomeGamer14** [comment]
Hey, I have already cleared the cache and restarted my phone a few times.
I attached a part of the logcat output.
[logcat.txt](https://github.com/signalapp/Signal-Android/files/10058560/logcat.txt)

**Comment by MedzikUser** [comment]
Your database file appears to be corrupted. Do you have any signal backups?

**Comment by clauz9** [comment]
can you get a debug log from the app ? 🤔  since now it's working again .. it should contain logging around the crash as well

**Comment by ErikDohmen** [comment]
I have had and still have this error for the last couple of years. I've managed to download the project and fix it myself by updating the code.

The issue for me is that there is a corrupt database I guess.
In RecipientDatabase.kt on line 1193 you've got:
`val key = existing.storageId ?: throw AssertionError()`
That's the one that makes the app crash. If I transform it to
`val key = existing.storageId;
      if(null != key) {
        out[recipientId] = StorageId.forGroupV2(key)
      }`
then it works again. I just downloaded the latest version and the error is still there.
I tried to build the new release for myself as the app was telling me that I should renew the app, but for some reason I don't get the build directory with the apk in it when i do  ./gradlew assemblePlayProdDebug

I rather don't fix it for myself every time, but I hope this puts you in the right direction towards a solution.

**Comment by clauz9** [comment]
@ErikDohmen  the apk should be in `...\Signal-Android\app\build\outputs\apk\playProd\debug` 

and you should make a Pull Request so the developers may merge it and fix the issue.. if you are sure that is the fix for it. 🤔 

but I guess Greyson will see it now, that you tagged him..

**Comment by ErikDohmen** [comment]
@clauz9, thanks for that.

I'm willing to make a pull request, but I'm not sure whether this is a solution Greyson would like. Cause the assertion failure is probably thrown for a reason. For me it is a solution and it might for others. But I would rather have my database fixed in some kind of way. I believe it has to do with a group I was in, but even though I removed myself from the group and deleted it, I still get the error.

But if @greyson-signal, would want me to make such a PR, I'm more than willing to make it, cause that would make my live a lot easier instead of building a version again every three months or so (specially when I'm off for a week or so and need to generate a new one in time)

**Comment by greyson-signal** [comment]
@ErikDohmen your issue is different from OP's issue. OP's literal database file is corrupt and upopenable. I've forwarded the relevant bits of that log to the SQLCipher folks to have a look at.

Your issue is that the data in your database appears to be inconsistent, implying an error in our application logic, not the database file. Specifically, it looks like there exists a group in your group table that doesn't have a matching recipient in the recipient table. I'll have to think about what the correct solution is here.

**Comment by ErikDohmen** [comment]
@greyson-signal, thanks for the info. If I can be of any help, just let me know.

**Comment by DomeGamer14** [comment]
Ok, so I also have some updates:

As mentioned before, my app suddenly started working again, and it worked for 2-3 days. 
After that, the same issue started appearing again, this time it didn't fix itself. 

Luckily I made a successful backup two days before it completely stopped working. With this backup, everything looks good again.

@greyson-signal Thanks for forwarding my issue, if you need any further information, please let me know.
