### ISSUE TITLE
Signal 6.6.3. crashes on backup restore, likely due to "FOREIGN KEY constraint failed (code 787)"

### ISSUE THREAD

**Issue by ConnectToTom** [signalapp/Signal-Android#12703]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal app crashes while trying to restore a backup (both file backup and wireless transfer). Signal 6.6.3
Detail info in crash log: `FOREIGN KEY constraint failed (code 787)`

### Steps to reproduce
- On an Android device without previous data on it: Start to restore Signal data from file backup
- enter valid pass-phrase
- after about 25% of messages processed, Signal closes without notification. When starting the app again, it shows the welcome screen. 

**Actual result:** Signal app crashes, backup not restored. 
**Expected result:** Data from backup restored. 

Additional information: 
1. Signalbackup-tools ( https://github.com/bepaald/signalbackup-tools ) does not detect issues on the backup file, a backup file that was processed & output by the tool also encounters same problem. 
2. Creating a new backup with new pass-phase encounters the same problem.
3. Backup restore by wireless transfer (in Signal apps) aborts after about 30% of transferred messages with error symbol shown. 
4. Backup file size is about 2 GB. 

I would be really happy transfer my message history to my new device. I'll be glad to try out advice provided. 
**Thank you very much in advance for your kind support.** 

### Device info
Old device (source of backup file): 
**Device:** Samsung Galaxy S9
**Android version:** 10
**Signal version:** 6.6.3

New device (where trying to restore backup):
**Device:** Samsung Galaxy S20+
**Android version:** 13 (Original Samsung G985F...FGVL5)
**Signal version:** 6.6.3

### Link to debug log
Full debug log: https://debuglogs.org/android/6.6.3/bd9907a6965bfbe01a7913650b3e87a3e277f7151a043c13a11122c085ff6184 

Crash info section from debug log:
```
============ LOGCAT =============
--------- beginning of crash
12-31 11:51:34.822 20887 25909 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-31 11:51:34.822 20887 25909 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 20887
12-31 11:51:34.822 20887 25909 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:150)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 11:51:34.822 20887 25909 E AndroidRuntime: 	... 4 more
12-31 11:54:04.161   733  1379 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-31 11:54:04.161   733  1379 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 733
12-31 11:54:04.161   733  1379 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-31 11:54:04.161   733  1379 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:150)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 11:54:04.161   733  1379 E AndroidRuntime: 	... 4 more
12-31 11:55:39.038  1554  1629 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-31 11:55:39.038  1554  1629 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 1554
12-31 11:55:39.038  1554  1629 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:150)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 11:55:39.038  1554  1629 E AndroidRuntime: 	... 4 more
12-31 12:40:31.110  7361 16164 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-31 12:40:31.110  7361 16164 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7361
12-31 12:40:31.110  7361 16164 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:150)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 12:40:31.110  7361 16164 E AndroidRuntime: 	... 4 more
12-31 13:06:18.031 16229 24863 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-31 13:06:18.031 16229 24863 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16229
12-31 13:06:18.031 16229 24863 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:150)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 13:06:18.031 16229 24863 E AndroidRuntime: 	... 4 more
12-31 13:08:21.067 25729 26359 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-31 13:08:21.067 25729 26359 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 25729
12-31 13:08:21.067 25729 26359 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:150)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-31 13:08:21.067 25729 26359 E AndroidRuntime: 	... 4 more
--------- beginning of main
...
```

**Comment by ConnectToTom** [comment]
Additional note: 
In other, similar sounding bug reports such as #12048 , comments stated that their issue was solved with Signal version 5.33.2. Unfortunately, my Signal version 6.3.3 does encounter such an issue. Might it be a different root cause here?

**Comment by ninjypsy** [comment]
I'm not a coder so I'm going to be useless in helping to resolve this, but I've just created a github account specifically to say that I'm having the same exact problem. Same steps as OP, same version of Signal on both phones, same error log. Trying to transfer from a Pixel 3 to a Pixel 7. Really hoping this gets solved soon!

**Comment by pipejakob** [comment]
I am in the same boat, hitting the same crash/stacktrace when trying to restore from backup using Signal 6.6.3. Please let me know if more information or logs would be useful to root cause the issue.

**Comment by greyson-signal** [comment]
@pipejakob Do you know which version of signal was used to _create_ the backup? Can you also provide logs from the device that's crashing on restore? To get debug logs, you should be able to tap 8 times on most of the headers in the registration process to get to a log screen. Thanks!

**Comment by pipejakob** [comment]
I do not know for certain, but it is very likely that the Signal version used for backup was the same 6.6.3. I was reflashing my phone, so the backup and restoration happened only a few hours apart. My apps auto-update, and this was about a week after the 6.6.3 release, so it's extremely unlikely that the backup was created with an older version of Signal.

Crash log: https://debuglogs.org/android/6.6.3/8b1a99eab68a9a4de7c67ef4ade765bfd262739a11eef688baada3f74cea74da

**Comment by sgroppatore** [comment]
Same issue here - moving from Signal 6.6.3 on Pixel6a to Signal 6.6.3 on Pixel 7 Pro.

**Comment by sixcircuit** [comment]
Same here. Foreign key constraint. Both signal versions are 6.6.3. Make the backup, transfer the backup, blows up. Also, the "transfer account" function has the same problem. Both get about 30k messages in and blow up. Please help. Thanks for the (usually) great software.

**Comment by ConnectToTom** [comment]
> I have a fix for this, if you're technically inclined: download this tool: https://github.com/bepaald/signalbackup-tools download your backup and unpack it into a directory (you need to create an empty directory first for the unpacked files or the tool gets confused) open the database.sqlite file in the unpacked directory with sqlite3 run `pragma foreign_key_check;` https://www.sqlite.org/pragma.html#pragma_foreign_key_check delete the offending rows (4 total in my db) repack the backup into a file copy it to your device and you should be good to go.


Yes, I also achieved to fix my backup file by manually repairing the database on this approach. In addition to the description given by @sixcircuit , the following description was complementary & helpful: https://github.com/signalapp/Signal-Android/issues/12048#issuecomment-1065883028 
I had to delete one entry in the table **msl_message** and one entry in table **msl_recipient**, both linking to the same nonexistent msl_payload._id. 


To the Signal developers: With a brief look into the receipient id, I recognized the following detail: 
The affected contact, with which I am in some group chats but did not message him directly for long time. Some months ago, I had sent a first text message via Signal Desktop. This initial message from me to the contact was not synchronised to the Signal app on my (old) phone. Also, Signal Desktop is showing many other (system) notifications in the chat history, f.ex. about changed security verification number or changed profile names. All these system notifications are not present in any Signal app for that contact. Lastly, I had changed the contact name in my phone address book, which does not reflect in the old phone's Signal app. 
I hope this helps. 

Thank you for all your efforts!

**Comment by pipejakob** [comment]
Thank you @sixcircuit and @ConnectToTom for the pointers for how to manually repair a backup file, and a huge thank you to @bepaald for creating this great tool in the first place. I followed the same approach, and was able to create a new backup file that did not crash Signal.

I'm documenting my steps here verbosely both to try to help Signal devs root cause the bug(s), and to help any other users who might need more hand-holding than the previous explanations:

1. First, I downloaded and built https://github.com/bepaald/signalbackup-tools.
2. Then, I used this tool to decrypt and dump the backup file to a new directory:
```
$ mkdir export
$ signalbackup-tools signal-2022-12-31.backup '<my backup password>' --output export/
```
(I did this within the `/dev/shm` filesystem to try to keep it off disk, but I don't know if there are any guarantees that it won't get written out to swap)

3. Then, I manually inspected the sqlite database to find and delete the foreign key violations:

Open database:
```
$ sqlite3 export/database.sqlite
```

Turn on headers so that the results of queries are easier to understand:
```
sqlite> .headers on
```

Check for foreign key constraint violations:
```
sqlite> pragma foreign_key_check;
table|rowid|parent|fkid
thread|28|recipient|0
```
The result here shows that the constraint is violated in the `thread` table, in row `28`, when it references a record in `recipient` that fails the first foreign key rule (index `0`). So there is an entry in `thread` that tries to reference a record in `recipient` that doesn't exist.

So I looked up the foreign key definitions for `thread`:
```
sqlite> pragma foreign_key_list(thread);
id|seq|table|from|to|on_update|on_delete|match
0|0|recipient|recipient_id|_id|NO ACTION|CASCADE|NONE
```

This shows that the field in `thread` with the foreign key constraint is called `recipient_id`. I already knew the thread id was `28`, so now to find the offending `recipient_id`:

```
sqlite> select recipient_id from thread where _id = 28;
recipient_id
148
```

I confirmed that this recipient was indeed missing:
```
sqlite> select _id from recipient where _id = 148;
```

(the output here was empty, so no records were found)

To try to figure out how many messages I was about to orphan if I deleted this thread, I searched the `sms` and `mms` tables for anything that matched the offending thread:

```
sqlite> select _id from sms where thread_id = 28;
sqlite> select _id from mms where thread_id = 28;
```
(both had empty output)

I don't know if there are other tables that join with the `thread` table, but having a thread record that seems to have no matching SMS or MMS messages associated with it makes me think that either those messages failed to get backed up, or this thread entry was created erroneously.

Since a partial restore from backup is better than no restore, I deleted the thread from the database:

```
sqlite> delete from thread where _id = 28;
```

I still have the original backup file in case any progress gets made that helps me restore more data, but I do not have access to the original Signal installation, so I won't benefit from any bugs fixed in the export process.

4. After deleting that row, I pressed Ctrl-D to exit sqlite, and then created a new backup file using this unpacked (and now modified) directory:

```
$ signalbackup-tools export/ '<my backup password>' --output signal_fixed.backup
```

This created the new file `signal_fixed.backup` that successfully restored for
me using Signal 6.6.3.

Hope that helps anyone else!

**Comment by bepaald** [comment]
@ConnectToTom:
>Signalbackup-tools ( https://github.com/bepaald/signalbackup-tools ) does not detect issues on the backup file, a backup file that was processed & output by the tool also encounters same problem.

Right, by default the tool only does an integrity check when you actually modify the database or explicitly ask it to (`--checkdbintegrity`), otherwise it just assumes the database is in a correct state (which of course it usually is). But maybe I should change that, it is a very quick operation anyway.

@pipejakob 
I had no idea there were problems with backups until you tagged me, thanks.
And thanks for the great write up, I'm sure it will be helpful to others. Three small notes/additions:

- You could theoretically do the entire process without ever having decrypted data touch disk, using `--checkdbintegrity` and then `signalbackup-tools [input] [passphrase] --runsqlquery "DELETE FROM table WHERE something" -o [output]`. This is of course unless the OS decides to swap, but the program is not very memory hungry so it shouldn't be a problem for most cases I think. Your way is probably more comfortable though.
- After fixing the backup by deleting some data, it is probably a good idea to do another integrity check (the deletion itself could cause other foreign key constraint errors).
- In that last command, to repack the directory into a backup file, there is of course no passphrase for the input (it is not encrypted), but one is needed for the output. So the passphrase in your example code should be prepended with `-op` or `--opassphrase`.

Thanks!

**Comment by brunnme** [comment]
Thank you all for this.  @ConnectToTom for the solution, @pipejakob for the verbose logging of steps, and once again to @bepaald for the tool.  Created an account just to tell you my wife had this exact problem and I was able to fix it by following the steps outlined here.  Recovered over 15000 messages for transfer to new phone.  Can't imagine how many people are just giving up/uninstalling after this kind of exception.

**Comment by ninjypsy** [comment]
Thanks to everyone who's working on this, though I think the solution is a little beyond my skills to implement. Is there likely to be a software update with an official fix anytime soon? Cheers :)

**Comment by alex-signal** [comment]
Hey all, I believe some work was done on this for 6.7.x, so please try again on that version.

**Comment by strugee** [comment]
@alex-signal do you mean 6.7.x in general, or the latest version of 6.7.x? I reproduced this last night on a device receiving a transfer running 6.7.4. I'm not 100% sure what version the source device was on since I just updated it without thinking due to your comment, but I suspect it was around the same version - I can post the debug log I captured in a bit.

**Comment by strugee** [comment]
@alex-signal I can reproduce (on the target device) what appears to be the same stack trace with both devices running 6.7.5.

**Comment by alex-signal** [comment]
@strugee We released 6.7.6 which rolls back an update to SQLCipher, which may help. If there are still issues once you go to that if it still fails, I'll make sure the right person is made aware :-)

**Comment by strugee** [comment]
I'm on the beta, so I was given 6.8.0 by Google Play and can still reproduce.

Debug log on the old device: https://debuglogs.org/android/6.8.0/3a16eba8a02ba104fd96ae2bedaba5383f5dc1547dc4e23afd5a77f3386c9eab

**Comment by ninjypsy** [comment]
@alex-signal Just wondering if there's been any progress on this? Cheers :)

**Comment by ninjypsy** [comment]
Hi again @alex-signal - just an update this this is still happening with both phones running 6.9.2

Is this something that's likely to get fixed, or should I resign myself to losing my archives?

**Comment by pipejakob** [comment]
Regardless of the ultimate root cause fix here, I would recommend two adjacent improvements for the Signal app:

1. Improved UX when restoring from backup fails.

Right now, what all of us on the issue have experienced is Signal abruptly crashing, and needing to dig into adb logs in order to see the `SQLiteConstraintException` being thrown and understand what's happening. This is because all of SQLCipher's exceptions are `RuntimeException`s (which looks like it will [change in the next release](https://github.com/sqlcipher/android-database-sqlcipher/commit/f2e301eb386ea3bf364e0cbfc8f4ee4d260e6a88)), so if they aren't explicitly caught, they will cause the Android app to crash.

Since this exact foreign key constraint crash during restore isn't new (#12057, #12051, #11952), it seems sensible to explicitly catch `SQLiteConstraintException` during restoration and have dedicated messaging to the user about how to proceed when it's encountered. Maybe this could ask users to file a Github issue, maybe it could forward them to the debug logs UI. Even just showing them the contents of the caught exception seems better than crashing here to me, since it gives users a string to start Googling.

2. When restoring from backup fails, give users the option to restore *as much as possible* instead.

I think it would be valuable to support two passes of restoration: if the first (normal) attempt fails, show the user the failure and give them the option to try again while ignoring all `SQLiteConstraintException`s encountered. The UI messaging should make it clear that this button should be used as a very last resort, after contacting the development team, searching through issues, waiting for a bugfix, etc., but it would empower users to take action instead of a) waiting indefinitely for a bugfix or b) abandoning their backup file entirely (like @ninjypsy here). This would effectively automate the steps that the rest of us on this issue were doing manually, and allow less sophisticated users a one-click option to use the same approach without needing to use `signalbackup-tools` to manually patch their backup file.

The current restoration code is [here](https://github.com/signalapp/Signal-Android/blob/fe40e37da4525698c3393b7115cabc0ca7fc6e7e/app/src/main/java/org/thoughtcrime/securesms/backup/FullBackupImporter.java#L82), and catches no exceptions. This method could expose a new boolean parameter to enable partial restorations, and when set to `true`, it would simply catch and ignore any `SQLiteConstraintException`s encountered. Having this catch be very limited in scope would mean that any other unexpected `SQLiteException`s would still bubble up and fail the restore (which I think would be desirable). I believe the end result of this behavior would match what the rest of us were doing manually by patching our backup files via `signalbackup-tools`.

Do these seem like reasonable requests?

**Comment by strugee** [comment]
> Right now, what all of us on the issue have experienced is Signal abruptly crashing, and needing to dig into adb logs in order to see the SQLiteConstraintException being thrown and understand what's happening.

FWIW I get a nice "transfer failed" message when using "transfer from another device". Agreed that this should have a link to the debug logs though - I shouldn't have to know about the magic "tap 5 times on the registration screen" method.

**Comment by pipejakob** [comment]
> FWIW I get a nice "transfer failed" message when using "transfer from another device".

Thank you for clarifying; I didn't mean to overstate the impact. I believe that people hitting this issue while performing a restore from backup (but *not* transfers) are experiencing abrupt app crashes.

**Comment by ninjypsy** [comment]
Giving the user the option to restore as much information as possible would be greatly appreciated. Based on earlier posts in  this thread, I deleted some less-important conversations where the security number with other person had changed, or they had changed their user name, hoping this would create a clean backup file. It's still not working, and the only conversations left to delete are with people who are very dear to me, who live on the other side of the world and who I only get to see in person once every few years. The thought of losing my message histories with them is heartbreaking, frankly.

**Comment by strugee** [comment]
> @ninjypsy It's ongoing :) We're keeping tabs on it.

@alex-signal what exactly does this mean? Are y'all investigating, or does "keeping tabs on it" just mean that you're monitoring crash rates in the Google Play console? I've been holding off on doing anything so I could help confirm that this bug is fixed, but if it's not being actively investigated I may just doctor a backup with `signalbackup-tools` - I want to stop carrying two phones with me 😅

**Comment by wavemobileDev** [comment]
I am having the same issue. Pixel6a to Pixel7 transfer (or more accurately failure to transfer). Have also culled my database, rekeyed it, and tried backing up with the radios disconnected. All to no avail.
Please fix this Signal. I would consider it a showstopping fault!

**Comment by wavemobileDev** [comment]
> > @ninjypsy It's ongoing :) We're keeping tabs on it.
> 
> @alex-signal what exactly does this mean? Are y'all investigating, or does "keeping tabs on it" just mean that you're monitoring crash rates in the Google Play console? I've been holding off on doing anything so I could help confirm that this bug is fixed, but if it's not being actively investigated I may just doctor a backup with `signalbackup-tools` - I want to stop carrying two phones with me 😅
> 
> (I feel like this comment is _bordering_ on a +1 comment, my apologies if it comes off as being over that line)

+1 from me.

**Comment by bepaald** [comment]
@ninjypsy I'm a bit hesitant to recommend my project, because 1: it might not work and 2: an official solution may be incoming. But, if you're at the point where you're resigned to loose message histories that are so dear to you, I'd say: open an issue on my project and I'll happily try to talk you through the process.

No promises of course (also because the few details given in this thread actually show slightly different issues), but nothing to loose at that point.

**Comment by alex-signal** [comment]
Hi all, are folks still experiencing this on newer builds? 6.6.x is quite old at this point, and I know there's been some code churn here as we try to work through these issue. Particularly, if you are on 6.10.x (which at the time of writing is still rolling out) or 6.11.x (whatever the current beta happens to be)

**Comment by strugee** [comment]
I can still reproduce on 6.11.1. Here's the receiving device's debug log, though it's the same exception string: https://debuglogs.org/android/6.11.1/d92877175802791c10791b84107938d41423cf096657d3804a6ace2a6f0c4cb2

And from the source device: https://debuglogs.org/android/6.11.1/8cb70fba8f460ef4506166d886673af0159154e812731d3d03b14199c14ce922

**Comment by patrickhanft** [comment]
I ran into this issue when migrating to a new phone this monday. I think it was on a 6.11.x beta.

(Many thanks especially to @pipejakob as his instructions saved my message history!)

**Comment by Meteor0id** [comment]
I am looking ad hundreds of foreign keys divided over msl_message and msl_recipient .  The parent for all of them is msl_payload . Would love to help fix this for once and for all, but I can't share my backupfile because it contains a lot of personal messages and contacts. The backupfile I am using was generated just yesterday on the latest beta.

**Comment by alex-signal** [comment]
Hi folks, a fix for this should be out in 6.11.4

**Comment by strugee** [comment]
I can still reproduce with both devices on 6.11.4. Debug log from the new device: https://debuglogs.org/android/6.11.4/7fa46edbebae53a051c2c1d97ed0fea08042661d12884101866c77f8414610c6

And the old device: https://debuglogs.org/android/6.11.4/b687925dfcca0316a2d435a3d3429b63e4a83c337064e92e36c8b18d3c0f2fd1

**Comment by bepaald** [comment]
@strugee I believe the fix only deals with the FOREIGN KEY problems in the msl_*-tables. (See https://github.com/signalapp/Signal-Android/blob/d8eac87219e766f56c226eaa1320e236f4d4258b/app/src/main/java/org/thoughtcrime/securesms/backup/FullBackupImporter.java#L146-L150 and https://github.com/signalapp/Signal-Android/blob/d8eac87219e766f56c226eaa1320e236f4d4258b/app/src/main/java/org/thoughtcrime/securesms/database/helpers/migration/V179_CleanupDanglingMessageSendLogMigration.kt#L9-L14)

Though this should probably fix the problems for most people in this thread, your debug log shows a key constraint error in the `thread` table (same as @pipejakob in [his comment above](https://github.com/signalapp/Signal-Android/issues/12703#issuecomment-1374281675)).

**Comment by strugee** [comment]
Nice catch @bepaald. Shot in the dark, possibly related to 61e127fabf9e7414878a1b8113dcca3cbaeb8a0e? I suspect that that fixed a bug I was encountering where MMS group messages would go into a totally incorrect thread, but it didn't clean up old misthreaded messages (I've been meaning to file a bug).

**Comment by ninjypsy** [comment]
@bepaald thanks for your offer, and sorry for the delayed response. The latest fix has solved things for me, thankfully!

**Comment by greyson-signal** [comment]
Just wanted to follow-up on recent fixes. We did a DB migration in late December that, for some people, resulted in some bad DB states for the `msl_*` tables that would result in foreign key constraints if you imported a backup with them in it.

So I fixed the bad DB state in 6.11.4, but also ignored foreign key errors on those specific tables on import to allow people to still use their existing backups. The only reason I could do this is because the `msl_*` tables don't contain what I would consider "essential" information. They're part of an optimization, and don't contain any user-facing data.

I don't want to universally ignore all foreign key constraints, because usually that'll mean that they end up missing actual  data in their restore, and we won't really know how much. It could be entire threads, all communication with a specific person, stuff like that.

I'm going to close this issue because I believe the root cause for most people was the `msl_*` thing. If people are continuing to see other backup failures or foreign key violations for other tables, please open a new issue.

Thank you, and sorry for all the trouble!

**Comment by AJolly** [comment]
(I'll note I got this with a backup I made yesterday, and attempted to restore it that same day).  Silent crash on import.  I'm working on fixing the database myself manually thanks to @bepaald 's tools.

**Comment by HeyVern** [comment]
Same.  Backup and Restore same day one device to another.  My foreign key was reported in the reaction table.  I manually repaired it, and now am not getting any database integrity warnings...but Signal still crashes on import of repaired backup.

**Comment by bepaald** [comment]
@HeyVern It would be interesting to see exactly what the situation was in your database. What was the violation and what did you do exactly to fix it. Also, as the integrity check passed, a debug log of the failed restore would also be helpful. If you want to try to get to the bottom of this, you should probably open an issue on my project though, as this is out of Signal's scope now.

For the original problem though, the foreign key constraint violation in the reaction table, you might want to open a new issue here (as greyson mentions just a few posts above).
