### ISSUE TITLE
Signal installed version mismatch 6.18.4 <-> 6.19.6?

### ISSUE THREAD

**Issue by sseide** [signalapp/Signal-Android#12931]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a an android 11 phone (lineageOs) and Signal installed via "Play" Store. The play Store says the latest version is installed and looking in the app description within the Play Store it says version 6.18.4 is installed at 20.04.2023.
Playstore says there are no updates available, latest version installed.

Starting Signal app and looking into settings -> help it says the app version is 6.19.4 ?!?

Due to this version mismatch it is impossible to transfer my account to another Android phone. The other phone is a complete new install with latest version of Signal installed via Play Store (6.18.4). Now after starting the transfer the new phone does not allow the Account transfer because of the newer version of the other phone?

On the new phone i cannot check version installed because i cannot get past the Restore screen to check the settings.

### Steps to reproduce
- i dont know - only you can only say why the older, long time used, phone says it is running 6.19.6 and not 6.18.4 as Play Store on this phone shows...

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Version information in Play Store and App version installed do not match.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Expected: Version information in Playstore must match version within app.

### Device info

**Device:** Fairphone2
**Android version:** 11 (LineageOS 18.1 from 20.04.2023)
**Signal version:** i do not know - either 6.18.4 or 6.19.6 but suspect 6.19.6 as other phone rejects it due to newer version...

### Link to debug log

https://debuglogs.org/android/6.19.6/e0f15d1dc677a80483bc76ccd3acefe92ea7e46f7ec1dafff38695496952988b

**Comment by alex-signal** [comment]
Hi! Unfortunately we had to halt the release of 6.19.x due to a database issue. We are actively working on a fix and hope to have it out soon. Sorry for the inconvenience!

**Comment by jrw** [comment]
=> SEE HOW HAPPY I AM BY THE ALL UPPERCASE COMMENT <= IT'S NOT AN INCONVENIENCE.  IT'S A F***ING DISASTER.  I CAN NO LONGER RESTORE FROM BACKUP OR TRANSFER FROM ONE PHONE TO ANOTHER.  I HAVE LOST MY *****ENTIRE***** SIGNAL HISTORY BECAUSE OF THIS.  DID NOBODY THINK OF THE CONSEQUENCES OF REVERSING THE RELEASE NUMBERS?????????????????????????????????????????????????????

**Comment by jrw** [comment]
I have just wasted 3 hours of my trying to do what should be a no-brainer, restoring from a backup or transferring from another phone.  And the app helpfully prevents me from doing this because the latest release is backlevel from my current release.  Just create a new release the same as 6.18.4 and call it 6.19.7.  And let me restore my backup!!!!!  I have exactly the same problem as the OP.  Even if you had a database issue, can't you post instructions on how people are supposed to restore from backup to transfer to a new phone???

**Comment by terrakuh** [comment]
I wanted to migrate to my new phone but the versions mismatch. Is it possible that I export the Signal 6.19.6 APK from my old phone to my new phone and backup, or is this risky? Are my backups from version 6.19.6 safe to use for future versions?

**Comment by UserX404** [comment]
As a fast workaround you can search for the apk (e.g. fx file manager) and transfer it to the new phone.

**Comment by jrw** [comment]
**Can someone provide a link to further discussion about this issue?**  I have already burned one Signal account because of this (I have a backup of the previous Signal account, but I can't restore it, so I have had to start over with no history whatsoever).  I have another phone waiting to be enabled with a different Signal account, but it appears there is no path forward (not a single path forward???) to keeping my Signal history.  I definitely do not want to side-install a Signal apk.  But I would be happy to find a way to downgrade my current Signal install to get to a scenario where I can backup and restore on my new phone.

**Comment by greyson-signal** [comment]
@jrw The issue we halted the rollout for was specifically around a bad database situation that could occur during a backup restore. We released a new version the same day. Unfortunately, the Play Store is still reviewing the release at the time of this post. There's not much else to do in this situation except to wait. If you want the release more quickly, we provide advanced access to APKs via [Firebase App Delivery](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-distribution/17538).

**Comment by greyson-signal** [comment]
@terrakuh  
> Are my backups from version 6.19.6 safe to use for future versions?

Yes. The problem we had was during the import of a backup, not the exports. All the backups we create should be fine.

**Comment by jrw** [comment]
@greyson-signal Thanks for your reply.  Can you confirm my understand below?

1. My backup is OK and I should keep checking back to see if a release > 16.9.6 is available.  When it is, I should make sure I've installed that version and then follow the restore-from-backup procedure.  I will lose any Signal chats that have occurred in between the backup and the restore, but my backup should be restored properly.  

3. **Follow up questions:  when do you expect the Google Play Store to release the fixed version approximately?  Within a day, several days, a week, ...?  It appears from your Firebase link that it normally takes < 1 day.**
4. **Do you know what the newly fixed release will be numbered?**  
5. For my other phone that has not yet been copied, my understanding is:  it would be best if I just wait until I see a release > 16.9.6.  Then follow the normal restore from phone-to-phone procedure either with copy-backup-to-other-phone and then restore-from-backup or instead use WiFi Direct to restore across phones.

**Comment by greyson-signal** [comment]
1. Yep!
2. I can't say with complete confidence, but I'm hopeful it'll be out by EOD tomorrow. Typically Google reviews releases in < 1 day, but every once in a while (like with this release) they will randomly take several days. We don't have any visibility into the process, so that's all I know :/
3. 6.19.8
4. Yeah I think that's a good approach.


@jrw  + @terrakuh I've also updated our self-hosted APK on our website to 6.19.8, which you get can [here](https://signal.org/android/apk/).

It's totally safe to install this over top of your existing Play Store install, and it's totally safe to then stop using it and resume updating through the Play Store afterwards. They're all signed the same and work identically, the only difference is that the website APK has a self-updating mechanism that'll prompt you when there's a new version.

**Comment by mwberry** [comment]
This is not the first time users have been caught in this snafu. At first I found a 3 year old issue that was essentially the same.

The problem isn't that you had a bug in your database import/export. The problem is that you haven't provided users an easy way to unblock themselves. You know Google takes it's sweet time approving and rolling out updates yet you still don't have any forwards/backwards compatibility code that would allow the export of the database in an older format.

If, on my old device that has new signal, I could export the database in an old format that my new phone with old signal would accept then I would pretty quickly figure out how to do that and I could move on with what I was doing.

**Comment by cody-signal** [comment]
6.19.8 is available via play store now.

**Comment by sseide** [comment]
ok - after updating both phones to new 6.19.8 i was able to transfer the account to the new phone...

For future reference - it would be nice to document somewhere when a version was withdrawn from store to prevent this kind of issues for other users trying to backup/restore/transfer during this time...

**Comment by jrw** [comment]
OK.  I was able to see 6.19.8 on Google Play Store from my new phone.  However, from my desktop browser, Google Play Store is still showing 6.18.4.  I don't know what that's all about.
I agree that this needs to be documented in the backup and restore page (https://support.signal.org/hc/en-us/articles/360007059752) and hopefully fixed so that a user doesn't have to wait for Google to approve the new release before restoring onto a new device.
