### ISSUE TITLE
"Link new device" does nothing

### ISSUE THREAD

**Issue by t-chaik** [signalapp/Signal-Android#13748]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

Trying to link my laptop device, from my Android phone I go to ``Settings`` > ``Linked devices`` and press ``Link a new device``. A dialog appears informing that `Before linking, confirm it's you` , asking to enter my phone's lock to confirm. I press `Continue`, enter my phone's PIN (PIN is correct, I know because if I enter something deliberatly wrong, it says `Wrong PIN`), validate and then nothing happens, back on the ``Linked devices`` app. page, without an error message...

### Device

Sony Xperia XA1 (G3112)

### Android version

8.0.0

### Signal version

7.21.5

### Link to debug log

https://debuglogs.org/android/7.21.5/96f6139eb8090eec09fc761fa96119abada7225f6a308adaa2f4ed4054d87210

**Comment by JoakimThorsen** [comment]
Same exact problem for me, signal desktop version 7.39.0 on Windows 11, app version 7.30.2 on Pixel 6a on Android 15.

**Comment by greyson-signal** [comment]
@JoakimThorsen Can you please share a link to a [log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by RedDirtDog** [comment]
Similar issue on Samsung S10+, advised that I'd be prompted for PIN, wasn't prompted & now "Link new device" button does nothing

**Comment by greyson-signal** [comment]
@RedDirtDog Can you please share a link to a [log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by RedDirtDog** [comment]
> [@RedDirtDog](https://github.com/RedDirtDog) Can you please share a link to a [log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

Yep!!

https://debuglogs.org/android/7.32.0/bb4c5baba6010e1df1ae7dfbe3acac20e2ee7d77ec2a0d19bc0b85d1247200c4

**Comment by TheTechnician27** [comment]
Sorry to reopen this, but this clearly wasn't resolved despite a log being provided upon request and multiple people having the same issue across several months and different manufacturers.

This appears to be related to a problem with the method of login, as neither a PIN unlock nor a pattern one would work (I didn't test a password and am unwilling to test biometrics). Selecting 'Swipe' or whatever the equivalent of 'no authentication' is in your phone's settings makes this feature suddenly work. Hope that helps, and yes, this is still an issue.

**Comment by cody-signal** [comment]
We think we fixed the original issue, but you may be encountering a different flavor. Would you be willing to provide your own debuglog after attempting to link a device with a some sort of device lock enabled.

**Comment by TheTechnician27** [comment]
Sure thing, Cody: https://debuglogs.org/android/7.42.2/f9a41a648ce9fced2b8abd669d3a7e173e12bdac7b7f7709b1ed81109607eb21

Please let me know if there's anything else I can do to help. This behavior was seen across both One UI 6 and One UI 7 (I came here after updating didn't work). The log should show me entering the app, going directly to settings, tapping the 'Link a new Device' button, backing out, trying again, backing out, and going to 'Help' for the log. A pattern lock was enabled at the time. Thanks again.

**Comment by t-chaik** [comment]
> We think we fixed the original issue, ...

Seems to be working again for me with 7.43.1, thanks a lot!

**Comment by JackThursby252** [comment]
It's still not working for me. I approve the code, nothing happens. 

/Edit: I nood to correct myself, it works. Im stupid. For everyone who is also stupid: make sure the qr code gets properly utf8 encoded.
