### ISSUE TITLE
Signal (Android) crashes after clicking/joining group via link (not solved by leaving group)

### ISSUE THREAD

**Issue by Kwurqx** [signalapp/Signal-Android#13949]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

Signal on Android 12:

After clicking https://signal.group/#CjQKIFBA8_aUor7************* to join a private Signal Group Signal Android crashed. I then did the same on Signal Windows 10 Desktop. I then could join and access the Group via Signal Desktop.

But...Signal Android crashes ever since (within a second).

I then left the group, restarted the phone, cleared Signal cache, and tried again. But Signal Android keeps crashing within a second from starting. I restarted and cleaned the cache several times, but Signal keeps crashing.

I do get Chat Push Notifications on Signal Android, but as soon as I then click the notification, Signal Android crashes.

I cannot access/send the Signal Error/Debug log via the app (non-rooted phone) since teh app won't run. But the Custom MI OS (MIUI 14) phone presented me with a partial log after several crashes. I captured a screenshot and applied OCR. It starts with:

java.lang.Assertion Error: org.signal.Iibsignal.zkgroup.InvalidlnputException: Failed to deserialize zkgroup::api::auth::auth_credential_with_pni::AuthCredentialWithPniResponse at org.thoughtcrime.securesms.keyvalue.GroupsV2AuthorizationSignalStoreCache.read(GroupsV2AuthorizationSignalStoreCache.java:91) at org.thoughtcrime.securesms.keyvalue.GroupsV2Aut horizationSignalStoreCache.read(GroupsV2AuthorizationSignalStoreCache.java:65) at org.thoughtcrime.securesms.groups.GroupsV2AuthorizationMemoryValueCache.read(GroupsV2AuthorizationMemoryValueCache.java:32) at org.thoughtcrime.securesms.groups.GroupsV2Authorization.getAuthorizationForToday(GroupsV2Authorization.java:43) at org.thoughtcrime.securesms.groups.v2.processing.GroupsV2StateProcessorupdateViaServer(GroupsV2StateProcessor.kt:291) at org.thoughtcrime.securesms.groups.v2.processing.GroupsV2StateProcessor.updateLocalGroupToRevision(GroupsV2StateProcessor.kt:190) at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupUpdater.updateLocalToServerRevision(GroupManagerV2.java:745) at org.thoughtcrime.securesms.groups.GroupManager. 

I am pretty sure this all started with clicking the link. Signal was working fine even minutes before. And its surely about Group functionality. Also evidenced by the Group related error/debug log entries.

How to get Signal Android working again? My Andriod phone is not rooted.

EDIT:

I solved the crashing of Signal Android by Removing the Group (not just Leaving) via the Signal Windows Desktop App. I guess Signal Android was still trying to sync the Windows Desktop App conversation/chat history for this non-working/non-existing Group from desktop to the phone. This stopped after completely removing the Group from Desktop side.

The core issue is still unsolved. Apparently some types of Groups will NOT work with my Signal Android and cause it to crash. Apparently when trying to get or sync messages form this group (which is not supported on my Signal Android).

Older groups work just fine. This was a newly set up group.

### Screenshots

![Image](https://github.com/user-attachments/assets/03097892-9fec-4216-b7b7-43bac2d5d65f)

### Device

MI POCO X3 NFC, running MIUI Global 14.0.5.0 (SJGEUXM)

### Android version

12 SKQ1.211019.001

### Signal version

7.30.2

### Link to debug log

https://debuglogs.org/android/7.30.2/ef456039853ba0a92b72d6194ab010252f22d93de726770c3292275f93fb1865

_No response_

**Comment by Bartype** [comment]
Hi, i have the same issue after clicking on a private group link for Signal, shared within whatsapp. One time i got the app starting again after rebooting the phone and long pressing the Signal icon and selecting a contact directly. But after a long 2,5 hour video call it's crashing again and ever since...

**Comment by Kwurqx** [comment]
I did not mention this in my bug report yesterday.

My Join Signal Group link was also shared and opened in WhatsApp. From WhatApp, Android then tried to open Signal, but the Signal GUI never appeared. And Signal kept crashing ever since.

As said, I solved the crashes by removing the group I successfully created using the same link using Signal Desktop. Which leads mevto believe the group was actually succesfully created in Signal Android. But not supported by either phone (MI) or custom Android GUI layer (MIUI). Or...it's a bug in Signal Android.

**Comment by greyson-signal** [comment]
Hi there, we're still looking into this, but we have something that should resolve this for most people in the upcoming 7.32 release (going to beta today). Thanks!

**Comment by keever** [comment]
I have also experienced this issue by clicking on a group in my Chats history that had removed me. I can open Signal without it crashing by enabling airplane mode on my samsung 21 ultra running android 13. I have tried deleting the group from the Chats history, clearing the storage cache, and rebooting, but v7.30.2 still crashes when airplane mode is not enabled.

**Comment by Kwurqx** [comment]
A possible solution is  good news.

I have bad news.

Today....I found out Signal Android keeps crashing again (was working after
removing Group via Desktop).

Installed today's Signal Android update. But, still crashing. Same error
log messages.

Signal Desktop on Windows still working just fine.

Hoping for a solution soon...

Op wo 29 jan. 2025 21:08 schreef Greyson Parrelli ***@***.***

**Comment by greyson-signal** [comment]
@Kwurqx are you on 7.32? That's where the fix is, and it's only in beta.

**Comment by Kwurqx** [comment]
No. Not 7.32 yet. Had an update today, but just checked and saw it is still
7.31.

Op do 30 jan. 2025 21:54 schreef Greyson Parrelli ***@***.***

**Comment by Kwurqx** [comment]
For what it's worth:

Reading Keever's comment (Jan 30)...

There is a WORKAROUND for this issue (until 7.32 hopefully solves the issue)

We already established that this issue is limited to Signal on Android. E.g. Signal for WIndows Desktop works fine as a workaround.

But...what about a workaround with limited READ ONLY use for Signal Android app?

I can confirm that enabling Airplane mode (disabling all radios / internet connectivity) will allow you to open and use the Signal Android App (in my case 3.71). This will at least give you READ ONLY access to you Signal message history on you Mobile (so no need for Desktop). Even shows new messages, if they where received in the background.

But...

As soon as Internet connectivity is (re)established (e.g. via switching on Wifi or 3/4/5G Mobile Internet) Signal will crash.

So...READ ONLY access, no sending messages. At least not while your offline.

But....

You can type messages while in Airplane mode. Then reestablish internet connectivity. Signal Android will crash. It will also crash when (re)started. But....the message was sent (just before crashing?).
