### ISSUE TITLE
Android app notifications "you may have new messages" and conversations don't update

### ISSUE THREAD

**Issue by youbzh** [signalapp/Signal-Android#14322]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

The issue started a few weeks ago. On Android, I'm getting regular "you may have new messages" notifications, while the app doesn't have any battery restrictions whatsoever.

- Conversations are up to date on the desktop app but they don't update quickly on the Android app. 
- Posting a personal note on the Android app updates the desktop app, but doing the opposite doesn't update the Android app.
- To update conversations on Android, I need to close the app and reopen it.
- I even got a notifications that "you may have new messages" while the app was open on my phone, as I'm writing this issue.

Thank you for your help, this is driving me nuts and ruining the experience for an otherwise wonderful app :(

### Device

Hisense A9 on LineageOS

### Android version

7.54.1

### Signal version

7.69.0 on MacOS

### Link to debug log

Here are both debug logs:
Android app
https://debuglogs.org/android/7.54.1/acf4dccf92ab17bd272dc42f93b523fe6267831554d1baa1cbaf219d126fd633
Desktop app
https://debuglogs.org/desktop/7.69.0/43efb0c947dd5173791a5bcc501e4f526f0fe99c6ce05788bb6f96acff2121cc.gz

**Comment by cody-signal** [comment]
Your android log are littered with network reachability problems. It implies the OS is tell us there's internet available but when we go to connect we are unable to reach Signal servers. Does doing an app restart always fix the issue? Is there anything special about your phone/network setup? A proxy server or anything?

**Comment by youbzh** [comment]
I'm experiencing the issue quite severely these days, and indeed restarting the app doesn't always solve the problem, it might take minutes before the new messages are downloaded.

This is strange, since it happens both with my home Wifi and when I'm out using 4G. There is nothing particular about my network setup, no proxy, no VPN. All the other messaging apps are working properly. I've checked Signal's network authorisations, everything is properly setup there.

As said before, the issue appeared maybe a couple of weeks ago. I have another debug log from the 1st of september, so it looks like the issue appeared with the latest release. Should I try downgrading to see if this has anything to do with it?

**Comment by youbzh** [comment]
Quick update: I checked an older log and now I can say that the issue appeared after updating from 7.52.2 to 7.54.1. Here is the log in question:
https://debuglogs.org/android/7.54.1/e3a1e917f33aad99ed8727c0c8422b2e7a60023111f3c039442304896311d085

So I rolled back to 7.51.2 (for some reason after rolling bak to 7.52.2 Signal kept crashing), and the issue has disappeared. Here is the new log after rolling back:
https://debuglogs.org/android/7.51.2/ccb02f20e3dc1251f4f7be64cdf22c88b5204874753097e787c3248729fb2bfb

If you compare all three logs, "TCP connection timed out" messages only appear under 7.54.1

**Comment by cody-signal** [comment]
Appreciate the extra due diligence. We'll look into it right away. Thanks.

**Comment by andrew-signal** [comment]
Hi @youbzh!

If I'm reading your logs correctly, they indicate that you are failing to connect to a proxy that you have set in the system settings. 

Here is a video of how you can check your system settings to see if you have one set:

https://github.com/user-attachments/assets/18cac27a-79c2-4315-a251-957f8f7ad46c

If so, you can try unsetting it if it is not needed, or you can reach out to whoever hosts your proxy to see if they can fix the issue there. Other apps may also be having the same problem. 

We are already working on some improvements in this area, too. 

Thanks for reporting the issue, and let me know if this was helpful or if you have more questions,

- Andrew

**Comment by youbzh** [comment]
@andrew-signal 
Thank you for your input. I know what a proxy is and there isn't one set up on my phone. As stated before, this is a version related problem: downgrading to 7.51.2 solved my issue.

**Comment by Panzerfather** [comment]
> Appreciate the extra due diligence. We'll look into it right away. Thanks.

Maybe a hint to search for errors:

Even on phones configured with a link-local address for IPV6 (fe80::) the app is ONLY trying to connect to IPV6 servers (2600:9000:a61f:527c:d5eb:a431:5239:3232 or 2600:9000:a507:ab6d:4ce3:2f58:25d7:9cbf) when using a proxy. So it will receive a 503 if the proxy only support/configured for IPV4.

Maybe this is also the case without a proxy. This error is present for about more than 2-3 months right now, but I can't give an exact version.

It would be good to integrate a check if IPV6 is configured as link-local address and then switch to IPV4 for fallback before trying to connect to the signal servers.

**Comment by andrew-signal** [comment]
@Panzerfather I think we've fixed that issue in the latest Beta, if you don't mind downloading it, trying it, and reporting back.

**Comment by youbzh** [comment]
@andrew-signal 
So should I download the latest release on here to check whether the issue is solved?
Thanks

Edit: Also, Signal on Android keeps auto-updating without me asking (since I downgraded, it did it twice, which is very annoying, I get updated to 7.56 which isn't functionnal. Messages get lost because of the network issue). Is there any way to disable that ?

**Comment by andrew-signal** [comment]
Yes, if you can test again on the latest production build, that would be helpful.

We've made two changes. The first change is in v7.57.2 or later, which is the current production version. We've already gotten reports from the field that this has helped with similar problems on other platforms. 

If that does not solve your problem, the second change/improvement is in v7.59.x, which will be released to beta in the next few days.

**Comment by youbzh** [comment]
Hello,
I've tried both 7.57.2 and 7.58.1, I'm still getting connection failures.
I'll wait for the next version and report then.
Here is my latest log FYI:
https://debuglogs.org/android/7.58.1/5ea671d99d22e1b513ffc877d8f47ae977c68c6064fc2bf4127c38e2ae20943f
Cheers

**Comment by youbzh** [comment]
Adding a message, to let you know that now I can't revert back to 5.51.2, which was the only working version I could find. Signal keeps crashing. It feels like a hopeless situation, Signal is kind of critical for me, to communicate, and I can't use it anymore 🙁
How come I can't downgrade anymore? Any reason why this should happen?

**Comment by andrew-signal** [comment]
Hi!

Looking at your logs, it looks like the issue improved due to the fix that went into v7.57.2, and then (separately) you hit the issue that was fixed in v7.59, but you were not yet running 7.59 yet.

Can you try updating to the latest and seeing if the issue has resolved? If the issue has not resolved, please post some debug logs from the latest version, and I can take a look.

Thanks!

- Andrew

**Comment by youbzh** [comment]
Hi Andrew,
I've been on 7.60.1 for two days now, and it looks like the issue is resolved. No more pesky messages, it seems.

I'll let you know if anything arises.

Thank you

**Comment by wertzuz** [comment]
@youbzh if you didn't encounter any more issues I think its fine to close the issue

**Comment by youbzh** [comment]
@wertzuz Everything is good now, it can be closed indeed.

Thanks very much to everyone.

**Comment by kotecky** [comment]
I dare to report that the issue (the symptoms = "you may have new messages") strikes back since the update to 8.5.0 beta, installed on March 25.

**Comment by cody-signal** [comment]
Can you report it on the community forum or provide debuglogs here?

**Comment by kotecky** [comment]
I would but - starting this morning the app started quitting immediately after after it starts. Restarting the phone or wiping the cache does not help. No recent phone update made thought. Running Samsung Galaxy S23, One UI 8.0, Android 16.

**Comment by cody-signal** [comment]
Oh man, sorry to hear that. Can you try to launch in airplane mode and see if that lets the app keep running? You can then get a log zip to share from the 3 dot menu.

**Comment by kotecky** [comment]
OK, this worked. 

[signal-log-177487NNN.zip](/signal-log-177487NNN.zip) removed

**Comment by kotecky** [comment]
New logs, online, replacing the above removed ones: https://debuglogs.org/android/8.5.1/7b738c3a70910ccfa417d34d93b56e9072f2332662b922fcebbae8cbce983aa8
