### ISSUE TITLE
Signal always goes back to the last used chat/group

### ISSUE THREAD

**Issue by Machion** [signalapp/Signal-Android#14505]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

Since some weeks (don't know the exact version change), when I reopen Signal, it always goes straight into the last used chat/group, ALTHOUGH I was in the chat overview before! 
I hate this behaviour. I don't want to be thrown into a chat without my agreement (and marking received messages "read", but I don't want to deal with them right now). I hope it's not a feature. I even can't alter it somewhere in the settings. 
It seems the opposite bug to this report https://github.com/signalapp/Signal-Android/issues/14177 

### Device

Moto G100

### Android version

LineageOS 21/Android 14

### Signal version

7.68.4

**Comment by vickylarmour98** [comment]
I also experience this on a Samsung Galaxy A13 on Signal 7.68.5. It's very annoying for all the reasons stated and I would like to add a vote for addressing it please! I can provide a debug log if needed.

**Comment by Maroko** [comment]
I can also confirm this. My workaround is closing the app through the app switcher and then open it again. As mentioned above, it's quite frustrating to open chats I did not intend to open.

**Comment by Machion** [comment]
The problem didn't show up for month, so I thought it was fixed. I am on version 8.17.4 now.

**Comment by Maroko** [comment]
I have Version 8.18.1 and it happened multiple times today. I haven't figured it out when / why it happens.
But it even happens when I had opened another chat and minimized signal and reopened it, that it ooenened the chat before, even if that chat was archived.

**Comment by alex-signal** [comment]
Hi folks, sorry for the churn here. We recently rewrote a bunch of the main activity navigation code here to try to resolve this. Please let us know if it is still an issue once 8.19 goes out and I'll make sure it gets looked at.

**Comment by Maroko** [comment]
I'm now on 8.19.2 and the bug is still occurring.
I have the feeling that it happens more often (or even just) when I'm low on battery and in battery saving mode.
https://debuglogs.org/android/8.19.2/57f081874b65efb7e615e0d40f982e954f94ffedd6f8d8c7ab88ebc601c3212e
