### ISSUE TITLE
Self-sent messages are duplicated

### ISSUE THREAD

**Issue by brinerustle** [signalapp/Signal-Android#5820]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When sending a message to one's own account, it appears twice, using twice as much screen space. I know I sent it and I know I got it, showing it once is enough.
### Steps to reproduce
- make a contact for yourself with your number if you don't already have one
- write a message to your contact

**Actual result:** 
The message I sent appears twice.

**Expected result:** 
The message I sent should appear as sent or as received, but not both, which is redundant. 
### Screenshots

![stop repeating everything](https://cloud.githubusercontent.com/assets/643789/19829648/62908150-9de7-11e6-9cb3-5943a04598fc.png)
### Device info

**Device:** Huawei P8 Lite
**Android version:** 6.0
**Signal version:** 3.20.4

**Comment by Trolldemorted** [comment]
this is fixed by #5816.

**Comment by McLoo** [comment]
All SMS Apps do it that way. 
And even if changed for according to your request, I bet there will be a couple of new tickets complaining, that half of there self-correspondence is missing...

**Comment by Trolldemorted** [comment]
@McLoo that is ok for SMS Apps because they cannot do better, but not for an instant messenger.

Who would complain if duplicated messages are removed?

**Comment by brinerustle** [comment]
I must say, the ability for a secure channel to pass data from my desktop to my phone via the internet is great, but I noticed this peculiarity:

Even messages sent from the desktop version (chromium) appear twice on the android device. How can that be? 

The other direction doesn't work at all.

I can confirm that this issue (internal parroting) is still occurring in signal 4.0.1.

**Comment by Trolldemorted** [comment]
for Signal-Android: https://github.com/WhisperSystems/Signal-Android/pull/5905
for Signal-Desktop: https://github.com/WhisperSystems/Signal-Desktop/pull/959

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
