### ISSUE TITLE
Receive duplicate MMS message after 3-4 days

### ISSUE THREAD

**Issue by RandomDragon** [signalapp/Signal-Android#7621]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A duplicate MMS or "picture message" is received after a period of about 3-4 days. 
It seems to be mainly (or only) MMS's from people that don't use Signal.
Based on the previous bug (Legacy issue #5396), it seems like it might have something to do with not letting the phone provider know that the MMS was successfully received. As such, it might not apply to everyone, just specific phone providers. I use Virgin Mobile in Canada.

### Steps to reproduce
ask someone to send you an MMS
wait

**Actual result:** Receive the MMS as intended, but then receive it again about 3-4 days later.
**Expected result:** Only receive the MMS once, when it is sent.

### Device info

**Device:** Nexus 4
**Android version:** 5.1.1
**Signal version:** 4.17.5

**Comment by moxie0** [comment]
This should be fixed in 4.17.5. Are you sure that you originally received the MMS *after* the upgrade to 4.17.5?

**Comment by RandomDragon** [comment]
I'm not actually sure when the 4.17.5 upgrade happened, but I have been receiving duplicate MMS messages every time I receive them for over a year now. The most recent one was originally 4 days ago, and I received the duplicate yesterday. So unless the update happened in the last couple days, it's still not fixed.

**Comment by moxie0** [comment]
Yes, it's actually quite possible that you received the 4.17.5 update within the last 4 days. Can you do a test with a new MMS message now that you're for sure running the update?

**Comment by RandomDragon** [comment]
Okay, test started. I'll update in a few days. :-)

**Comment by micressor** [comment]
I can definitely confirm that this error still exists with signal 4.17.5. It's even worse. Signal crashes regularly as soon as an MMS arrives. From then on signal crashes regularly and is unusable until I do this workaround:

* Put the phone into airplane mode and delete the affected MMS according to signals [support page](https://support.signal.org/hc/en-us/articles/216770567-Signal-crashed-What-do-I-do-).

Probably I have to use adb logcat to provide a debug log at all?

### Device info
**Device:** Fairphone 2 FP2
**Android version:** 7.1.2 / LineageOS 14.1
**Signal version:** 4.17.5

**Comment by haffenloher** [comment]
To capture a debug log, put your phone into airplane mode after a crash, start Signal and go to Signal settings > Advanced > Submit debug log.

**Comment by micressor** [comment]
Here is the procedure for this debug log:
1. Wait until an MMS receive -> Signal crashes
2. Put the phone into airplane mode
3. Get a debug log from settings > Advanced > debug log:  https://gist.github.com/micressor/d3a21eaf5b713cfc7afc7d7c9f5a1aed
4. Delete the affected MMS so that signal works again.

@haffenloher Thanks for this hint.

**Comment by RandomDragon** [comment]
It sounds like Micressor has a different bug than this one....

Also, experiment completed, and it does appear to be fixed on my phone. Very awesome, thank you guys!

**Comment by micressor** [comment]
@haffenloher Whew, that wasn't the way I intended. I'll test it again. Sorry!
