### ISSUE TITLE
Calls are not silent in Do Not Disturb mode

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7828]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
#6411 
Incoming Signal calls still ring when phone is in do not disturb mode.

### Steps to reproduce
- Set do not disturb
- Receive signal call 

**Actual result:** Signal call still rings or vibrates based on the Ringer volume setting when do not disturb mode is on.
**Expected result:** Silent when do not disturb is active.

A temporary workaround to prevent ringing is to set Ringtone to silent in Settings > Notifications

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.19.3

**Comment by 2-4601** [comment]
Unable to reproduce on Moto G4 Play, 7.0.1, Signal 4.20.1

**Comment by bme13** [comment]
Hi. I also have a Samsung Galaxy (S5) and thought I could reproduce this however after double checking the 'do not notify' settings it turned out that for calls there was an exception. After changing this to no exceptions it worked as expected (no sound, only vibrating) @wesinator can you verify these settings?

**Comment by wesinator** [comment]
@bme13 Do not disturb should be totally silent, if it still vibrates then it isn't completely respecting do not disturb.

To clarify the bug, Signal will currently do whatever the Ringer is set to during do not disturb, so if you have the ringer set to vibrate it will vibrate, if you have the ringtone sound enabled, it will ring.

**Comment by 2-4601** [comment]
@wesinator Can you list the exact steps of how to reproduce this (including system settings and Signal settings) because I cannot reproduce this despite trying everything.

**Comment by bme13** [comment]
@wesinator I think your right and my expectations about do not disturb were wrong. 
@2-4601. Here's what I could do to provide some extra information. Hope that's useful.
settings:
**In Signal for calls:**
Notifications enabled
Ringtone Default ringtone
Vibrate enabled
**In Android do not disturb settings:**
Enabled, with no exceptions.

[Here's](https://debuglogs.org/c63e595bb2587a4cf083db60ae60c933f27ca40279e8b02e6d17a996b6287cb0) a logfile with the first call where the do not disturb mode is off (16:48). After that I've enabled the do not disturb mode and made an other call (16:50). Now as described earlier my device only vibrates in do not disturb mode.
Now the first thing I noticed that in both situations the IncomingRinges says: Playing ringtone now, however in the second situation prior to that message the Mediaplayer reports the volume is set to 0.
Also on both occations the IncomingRinger says 'Start vibration'.
Now just to be clear I'm no Android programmer however based on the logfile the logic for ringing and/or vibrating seems to be done in IncomingRinger.java. I think the ringermode should determine what to do. This is done by
`ringerMode = audioManager.getRingerMode()`
I think this call should return the Android ringermode setting. I've wrote a small test program that only does exacly that. Just ask the ringermode. On my Samsung S5 this call returns 2 (RINGER_MODE_NORMAL) no matter if I enable do not disturb mode. It does return 0 if I put the ringtone to silent(as the workaround suggests).  On a second device (Acer, running android 6.0) the getRingermode returns 0 (RINGER_MODE_SILENT) if the do not disturb mode is on.
Now one thing that's not clear to me is where the volume is set to 0 on the samsung device. I could not find this in the Signal source. Perhaps is this done by Samsungs implementation for the 'do not disturb'?
Anyhow, to me it seems Signal uses the ringmode to determine what to do however on my Samsung device this seems to work different.
In addition to all this, the caller app does stop vibrating in the 'do not disturb mode' so that's seems to work.

**Comment by wesinator** [comment]
@2-4601 Here is my configuration:
#### Phone settings:
 - Sound, ringtone volume on low
 - Do not disturb active with no exceptions

#### Signal "Calls" settings:
 - Notifications on
 - Ringtone Silent
 - Vibrate on

**Expected:** Totally silent when receiving call
**Actual:** still vibrates when receiving call (would ring if Signal Ringtone was not Silent)

**Comment by 2-4601** [comment]
#### Phone settings:
 - Sound, ringtone volume on 29%
 - _Do not disturb_ active in _total silence_ mode (with no exceptions)

#### Signal "Calls" settings:
 - Notifications on
 - Ringtone Silent
 - Vibrate on

**Result**: totally silent (no vibration) when receiving a call as expected

Android 7.1.1
Signal 4.20.4
Moto G4 Play

**Comment by 2-4601** [comment]
I can reproduce this in _Alarms only_ mode. Signal calls vibrate while normal calls do not.

Android 7.1.1
Signal 4.20.5
Moto G4 Play

**Comment by rosejasperfox** [comment]
I just experienced this on my Samsung Galaxy S7. I tried to submit the debug log but Signal crashed whenever I attempted to load the log (whee). With Do Not Disturb enabled and no exceptions other than permitting repeat callers to ring through, Signal calls still ring and vibrate.

Android 8.0.0
Signal 4.23.4

**Comment by techlever** [comment]
Calls still coming through with DND on. Device is Samsung Galaxy S8 running Android 9.

**Comment by wesinator** [comment]
> Calls still coming through with DND on. Device is Samsung Galaxy S8 running Android 9 and Signal 4.37.2

FWIW, it seems like the default system behaviour was changed in Android 9 - calls from contacts still ring in Android 9 DND.

**Comment by greyson-signal** [comment]
I think this was fixed recently.

**Comment by rosejasperfox** [comment]
I tested this just now.

DND off: Signal calls make noise and vibrate.
DND on: Signal calls make the Signal app crash.

**Comment by rosejasperfox** [comment]
This time opening the debug log didn't crash the app, so here's the log:

https://debuglogs.org/73c7d619d4dfb3179c8caba9f1648e81236eaebc035fbd11d9400f08878fa8e8

**Comment by feeela** [comment]
@rosejasperfox Please reopen or fix.

This issue is still valid. If I set my Android system settings to do-not-disturb, Signal keeps ringing for imconming calls and messages. As of 2023-01-26 Signal seems to be the only app, that completely ignores the Android do-not-disturb setting. 

Currently the only way to silence Signal is to mute all chats for a certain timespan.

**Comment by johnalanwoods** [comment]
Also an issue on iOS 16.

**Comment by karolzlot** [comment]
@greyson-signal 
Still an issue on Android

**Comment by Qubitza** [comment]
I have the same issue with the latest version (7.7.1) on Android 13.

**Comment by Penguin-Guru** [comment]
Still an issue on my Pixel...

**Comment by peterwilli** [comment]
I have this issue too and it drives me mad. I already checked if Signal is an exception

**Comment by ferricoxide** [comment]
Still an issue on my OnePlus 9Pro with Android version 14/vendored version LE2125_14.0.0.730(EX01)

**Comment by GenocideStomper** [comment]
This is obviously still an ongoing problem for a number of users. Should a new ticket be created if the author or any contributors refuse to re-open this issue? Closed tickets have less visibility in the issue tracker.

**Comment by ferricoxide** [comment]
@GenocideStomper 

I'd also found (and commented on) this, other [issue](https://github.com/signalapp/Signal-Android/issues/12708). This morning. It's at least open, even if it's been marked as stale
