### ISSUE TITLE
Messages get stuck after retries on SailfishOS

### ISSUE THREAD

**Issue by schmeat** [signalapp/Signal-Android#8536]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

This only affects one of my chats but it effectively locks me out of talking to the person because it keeps retrying without actually sending. All of my subsequent messages are stuck in queue and never get sent or delivered. Message sending/delivery work fine in the same chat on desktop though, so only stuck on mobile.

### Steps to reproduce
- Send a message before network cuts out (elevator?)
- Observe retry loop forever

**Actual result:** Messages are stuck in retrying loop
**Expected result:** for my messages to send

### Screenshots

Note there are stuck messages above the one that sent correctly (from desktop)

![photo_2019-01-17_19-26-05](https://user-images.githubusercontent.com/1139817/51357968-4dd59800-1a8f-11e9-995e-fb8baa3268e0.jpg)

### Device info
 Device : OnePlus ONEPLUS A6003 (OnePlus6) 
Android : 9 (1812250000, ONEPLUS A6003_22_181225) 
Memory : 46M (44.27% free, 512M max) 
Memclass: 256 
OS Host : ubuntu-14 
App : Signal 4.32.5 

### Link to debug log
https://debuglogs.org/bfeb4b01b7a80edce0fca69e5fd797d2c7321d0dce6fd708d1fdde17d6c8e0da

**Comment by greyson-signal** [comment]
Looking into it. In the meantime, try force-stopping signal and re-opening it.

**Comment by schmeat** [comment]
I initially did force stop and it did not work at the time. However, I tried it now (after sending desktop messages) and it seems to have properly failed now.

I'm not sure if it's the time that's passed or the desktop messages that did that? or neither? 🤷🏼‍♂️

**Comment by greyson-signal** [comment]
You had a message that experienced some network failures, and was therefore scheduled to be retried in the future, but it wasn't being retried, blocking future messages from sending (messages need to be sent in order within a conversation). Looks to be a problem with WorkManager.

**Comment by late-latte** [comment]
Not sure if it's related, but my client can call, receive calls, and receive encrypted text messages, but I can't send any text message and send or receive media messages. All they do is stuck in retrying loops.
Website latest release 4.31.8, without Play Services/GCM.
Lineage 15.1 Official Build 17/01, Asus Max Pro M1.
I'll send debug log later if you needed it, but there's nothing indicative of a problem so far.

**Comment by schmeat** [comment]
I have "adaptive battery" turned off for Android P and I also have signal white listed for battery optimizing, but I don't know what my phone is actually doing due to that OP bug lol

https://www.androidpolice.com/2019/01/18/oneplus-phones-are-discarding-androids-battery-optimization-whitelist-a-problem-as-more-apps-update-to-target-oreo/

**Comment by PaulXiCao** [comment]
Same issue. App is stuck in retry loop, but still receives messages. Only effects 1 chat.

Debug log: https://debuglogs.org/2575d415b57d8078b19931fc154f114e0f505dc58e142551677d33574cfcdc63

Device : Samsung S7 edge (SM-G935F)
Android : 8.0.0
OS Host : debian testing
App : Signal 4.32.7

**Comment by greyson-signal** [comment]
After doing more digging, this could be a bug that was introduced in WorkManager beta02. I'm seeing problems with it in my testing. I'm going to be moving us back to beta01. Let me know if the issue comes up again in 4.32.8. Thanks!

(Note: If the message is still stuck when you do the update, you may still have to force-stop and/or restart your device to kick it in gear. But hopefully no new occurrences come up in 4.32.8)

**Comment by akutuzov** [comment]
@greyson-signal @strybe Do you know of any way to 'force-stop' Signal on Jolla/Sailfish? I've run into exactly the same issue with messages not being sent to one particular contact from my mobile. The only way to fix this was to completely reinstall the app, with new keys generated, etc. 
Several days after reinstalling the same happened again. I upgraded the app to the version 4.32.8, but the messages still are not being sent to the 'problematic contact'. Rebooting the phone or restarting Android support does not fix the problem. 
So, is there any way to 'reset' the messages schedule from within the Signal? I would really hate to reinstall it again from scratch.

Thanks for this thread, it was very helpful.

**Comment by strybe** [comment]
See also #8559, problem still exists.

@akutuzov For SailfishOS you can go to Settings -> Apps -> Signal -> Force Stop or you stop the Android Support or restart the phone. The problem was not fixed for me by these measures.

In both chats my last message remained in the state with spinning circle. In one chat the problem resolved itself notifying about dozens of unsuccessful attempts to send. After that, sending was working again. The other chat still remains stuck.

**Comment by akutuzov** [comment]
@strybe same here, all conversations that were stuck before upgrading to 4.32.8 are still stuck, whatever I do.
Seems very weird, considering that the same conversations work perfectly with Signal Desktop.

**Comment by greyson-signal** [comment]
@akutuzov This is an Android client issue, not a server issue. That's why you don't have any problems on desktop. The library we use to schedule message sends had a bad release that was present in 4.32.7, which caused messages to get stuck. This was fixed in 4.32.8, and any stuck messages should typically be able to get 'unstuck' by restarting your phone or force-stopping signal.

However, it also appears you and @strybe are running SailfishOS. After a message failure, messages are scheduled to be retried on JobScheduler, which is an Android system component. I'm going to guess that SailfishOS has some bug, or otherwise undesireable  behavior, in their JobScheduler implementation. I'm basing that on the premise that the only users I've seen who haven't been able to recover are either running rooted devices without Google Play Services or SailfishOS.

That said, I'm not trying to be dismissive. WorkManager (the library we use for scheduling message sends and stuff) has been a real pain point lately, and I'm looking for ways to resolve some of these issues we're running into.

**Comment by akutuzov** [comment]
Thanks @greyson-signal, you are doing a great work!

Yes, I wouldn't be surprised if Sailfish had a bug in Dalvik (their Android compatibility layer). That's why I asked is there any way to 'reset' the message queue for a particular conversation **from Signal itself**. 
I suspect it should in theory be possible, since if a conversation with a contact X is stuck, I am able to create a new group chat including only me and X, and it works fine, messages are sent without any problems. Would be nice if instead of this one could simply 'reset' a conversation.

**Comment by strybe** [comment]
Thanks @greyson-signal  for your time and effort!

> This was fixed in 4.32.8, and any stuck messages should typically be able to get 'unstuck' by restarting your phone or force-stopping signal.

There is already an option "restart encryption" in Signal chats. I tried this and it did not solve the problem. Maybe the behavior of this option could be expanded to also 'reset' the conversation or message queue as @akutuzov said.

> I'm basing that on the premise that the only users I've seen who haven't been able to recover are either running rooted devices without Google Play Services or SailfishOS.

For me, some logs in issue #8559 look like they are normal Android devices with GCM enabled.

**Comment by greyson-signal** [comment]
At this point this issue seems to be limited to SailfishOS and rooted devices. I don't see logs of 4.32.8 devices in #8559 that _aren't_ rooted, but please point them out if you see them. 

> Maybe the behavior of this option could be expanded to also 'reset' the conversation

This currently isn't a simple thing to do. WorkManager doesn't make it easy to resubmit an entire work chain. 

I'll re-open this issue, but I'm retitling it to be specific to SailfishOS.

**Comment by Furocious** [comment]
I've had this problem for some time now (it started with the beta version where typing indicators was introduced) and I am using Android 6.0.1 (MotoG3 without root). Currently running version 4.33.5 and I have tried everything except wiping the app data. Curiously, this is happening only on one device. I have another unrooted Android 6.0.1 device (Xperia z3c) and only the MotoG3 exhibits this problem. 

It usually starts after trying to send a gif or image file.  Another Signal user (unrooted also) has also indicated that they had problems trying to send image files to me.

In essence, this problem is not limited to SailfishOS.

**Comment by greyson-signal** [comment]
Merging this into #8602

**Comment by schmeat** [comment]
I got this again on 4.35.1

https://debuglogs.org/f3a0ecc2ceb108fb52aa88a0740b9b826eff33b815d4744d78a4ad4b1d8d5d42

Same device info as above
