### ISSUE TITLE
[Video Chat] image freezes/stuck after a time or when switching cameras

### ISSUE THREAD

**Issue by peterpanondrugs** [signalapp/Signal-Android#8685]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video image freezes/stuck after a time or when switching to rear camera. Turning the camera anew on and off doesn't help. Reinstalling the app neither.

### Steps to reproduce
- calling someone
- activate camera
- switch to rear camera or wait till it gets stuck after a time

**Actual result:** Video image freezes/stuck
**Expected result:** Video image should continue running like in the other versions. I can't tell which one was the last working version.

### Device info

**Device:** Samsung S7
**Android version:** 8.0.0
**Signal version:** 4.35.3

### Link to debug log

https://debuglogs.org/fcfbe39774fec94041413896257c2055bda2f7570b18475f135fe4a12c8230f0

**Comment by lckarssen** [comment]
The same has been happening to me (at least for a couple of months). 

Not sure if it is related, but since a week or two, maybe three, the receiving party also sees my video frozen (with the front facing camera) after a couple of minutes of video calling.

### Device info
**Device:** Samsung S7
**Android version:** 7.0.0
**Signal version:** 4.35.3

**Comment by Vaesper** [comment]
Same problem (also happening for a few months).

Device: OnePlus One (bacon)
Android version: 8.1.0
Signal version: 4.35.3

**Comment by five-c-d** [comment]
This problem was brought up in the forum, https://community.signalusers.org/t/video-call-freezes-for-other-user/7022/3 has the relevant excerpts from the debuglog of @peterpanondrugs  ...key portion was 

```
E ACodec  : [OMX.Exynos.VP8.Encoder] ERROR(0x90000006)
E ACodec  : signalError(omxError 0x90000006, internalError -2147483648)
E MediaCodec: Codec reported err 0x90000006, actionCode 0, while in state 6
```

This is caused about ~20 seconds after successful CALL_CONNECTED, by flipping to the back-cam (or vice versa), and is seemingly specific to Samsung devices with the Exynos CPU, and is also specific to the VP8 codec.  

Possibly this is a problem upstream, but they are marking it "patches welcome / reproduction steps on our AppRTCmobile test-apk needed" and not working towards a fix it looks like.  https://bugs.chromium.org/p/webrtc/issues/detail?id=8736 + https://bugs.chromium.org/p/webrtc/issues/detail?id=9797 are the main bug-reports.  Discussion here from August 2018 was helpful, https://github.com/oney/react-native-webrtc/issues/501#issuecomment-415245947 and in particular switching to another codec *does* work around the freeze. 

If other folks will please post debuglog URLs from the caller AND the callee devices, shortly after hanging up on a cryptocall exhibiting the video-freeze issue, that will potentially help narrow down the exact range of impacted chips/devices.  You can paste them here into github, or paste them over in the signalUsers thread linked at top of this comment

**Comment by jargonfilter** [comment]
Same issue here happening for the past few months like @Vaesper. 

Samsung Galaxy S7
Android 8.0
Signal 4.37.1 (but its been happening for several versions now)

This issue has effectively made video calls completely unusable. Hope there's a fix down the pipe, either from the signal team or people working on webrct.

**Comment by peterpanondrugs** [comment]
[Update]
Now my chatpartner isn't able to see me starting directly a video call:
debug.
https://debuglogs.org/25ee3cb5d8256413af447563477de547450cf5d7494d8a6911d36b683135a652

**Comment by Cre0** [comment]
Same issue here, it's happening over LTE and Wifi. The freezes seems to occur very random, everything from first second on established connection and at other times after 20 minutes. @five-c-d how can I change video codec? Just change it in mediaprofiles.xml, from like h.264 to h.263 or mpeg-4?

Oneplus One
Android: 7.1.2 & 9.0
Signal 4.38.2 (begun from 4.35.3 from what I can remember)

**Comment by soykanaydin** [comment]
I have the same problem for months. Today it happened in first 15 seconds of video call too. It makes video calls impossible to use. I can ask for other sides debug log too if it will help.

Samsung Galaxy S7
Android 8.0

Debug log: https://debuglogs.org/97590e9baa33d3e91a0b9bd7329c331359bf7405ce8810ea20a8647316f28c52

**Comment by jargonfilter** [comment]
Any word on whether this bug is going to get any attention? Video calls are _still_ totally unusable as of right now.

**Comment by apptester235** [comment]
Is there anyone working on this issue so that it can be resolved finally, have been having this issue for months now, still can't have a video call properly and it crashes all the time.

**Comment by greyson-signal** [comment]
There's been a lot of changes to video calling since this issue was reported. If you experience it, please submit a debuglog.

**Comment by apptester235** [comment]
Here are my Logs for when I have video called and it has crashed, I am using a Samsung s6: 
https://debuglogs.org/3ed9f95fdd0f93733f463494488d17ca19cbdb00f8e9ff6496e0a9d54459ce59
Here is my friends logs during the same call: 
https://debuglogs.org/ad267bdc5ecf0ef2305bdac36ef42eb4e997be0d8422828196295a90e937aa18
We both started to call around 17:22 and then on my side it was black and he couldn't see any thing that I had shown him on my camera but his stream had continued without any issue and I could still see what he was streaming.

**Comment by apptester235** [comment]
I have built the newest Signal build 4.54.2, with the commit (Add SM-G920F and BLK-L09 to LegacyCameraModels) which makes Samsung s6 use Legacy mode has fixed the #9150 issue, but still when video calls are being done then my video feed would freeze or go entirely black and then the person who is viewing the stream would not be able to see what is being shown live. So not entirely sure on what the issue is or could it still be app based issue that could be solved?

**Comment by j850** [comment]
I experienced the same problem several times. After some time (5-15min) the video image during a video call freezes on my device. The video image on the call partners device is still normal then, the image freeze always only happens on my device. The issue does not seem to be related to switching from back to front camera, it happens also when I stay in the app and only use the front camera all the time.

Here is the corresponding debug log I made shortly after hanging up the last time the issue occured:
https://debuglogs.org/c6fc3b779586b4849a5998d75ff720ba4ff92e2ffde7b9a0451572c8c8f12f22

Device: Samsung S7
Android version: 8.0.0
Signal version: 4.54.3

**Comment by j850** [comment]
Here are two further debuglogs, that were created after the image was frozen in a video call. It is again the same characteristic, that the image only freezed on my device but not on my call partners device. 

First debuglog (unfortunately no idea what caused the image freeze):
https://debuglogs.org/1392b9ca077f9080d03f1a7cdb4a9786f11cf639ade8e2caf7ff3845be79741b

The second debuglog reports an image freeze after my call partner switched from back camera to front camera:
https://debuglogs.org/0d5f25fced5c646622bea987835fe671e75529ef5eb09b03c5f4783e7d90bef7

**Comment by soykanaydin** [comment]
I also have the issue for a long time. Here is the debug log:

https://debuglogs.org/a2761922504a5d4b0b13f80f28c20ec6f5586d0c65e3a1896ce9bd3f27bede31

Image gets frozen after some minutes of video call.

**Comment by saghul** [comment]
FWIW we (Jitsi) had similar issues and switching to the software encoder seems to have helped.

**Comment by apptester235** [comment]
> FWIW we (Jitsi) had similar issues and switching to the software encoder seems to have helped.

Is this fix going to be implemented into any future versions of signal so that this issue can finally be resolved in the end?

**Comment by JeffMusgrave** [comment]
> Is this fix going to be implemented into any future versions of signal so that this issue can finally be resolved in the end?

At least if we had some sort of switch in the settings for hardware/software encoding that would be nice (at least if that's the real problem signal is having).

**Comment by ionphractal** [comment]
Just to put in my coin. It happens on my Nokia 6.1 (Android 9 and recently 10) as well as on a Sony Xperia XA2 Ultra (Android 9) where I could get the debug log from: https://debuglogs.org/e0aa830195db4e97cc014ded22269205e84d523820c353b0bfe3e7073c820e05

It could be related to round trip time as I couldn't replicate it between above two when they were not far apart network wise yet they still show the same pattern when calling to Japan (both call partners have a >100Mbit cable/fiber connection like myself yet but an older smartphone) . Additionally it hasn't been always the case. I can't directly associate it to a version but there was a time between last year August and December where I had no issues at all calling to Japan. But starting in January you can bet it crashes, yet not at a 100% chance. Currently when I notice a slight but periodic single stutter in my own camera image, it is most certain to happen, then my camera completely freezes and the call will be disrupted/cut off after around 10s though audio and the call partner's video still work until the end.

**Comment by saghul** [comment]
FWIW, here is how those with affected devices might be able to test this.

Here: https://github.com/signalapp/ringrtc/blob/d816012799dfacf9c9b69f30b7cf2bdcac57b78c/src/android/api/org/signal/ringrtc/CallManager.java#L762 replace `DefaultVideoEncoderFactory` with `SoftwareVideoEncoderFactory` (it takes no parameters).

You'll need to rebuild the ringrtc library, then Signal itself.

Note that CPU usage will be higher.

**Comment by apptester235** [comment]
> FWIW we (Jitsi) had similar issues and switching to the software encoder seems to have helped.

As Jitsi had managed to fix the issue I have tried there app, Jitsi Meet, on my Samsung s6 and there is no Video problem everything works and no black screens. 




> FWIW, here is how those with affected devices might be able to test this.
> 
> Here: https://github.com/signalapp/ringrtc/blob/d816012799dfacf9c9b69f30b7cf2bdcac57b78c/src/android/api/org/signal/ringrtc/CallManager.java#L762 replace `DefaultVideoEncoderFactory` with `SoftwareVideoEncoderFactory` (it takes no parameters).
> 
> You'll need to rebuild the ringrtc library, then Signal itself.
> 
> Note that CPU usage will be higher.

As for the fix which Saghul had proposed I was unable to build the RIngRTC due to many errors I was getting during the building process. And so if any other developer is up to the challenge they would be welcome to build the RingRTC library with the changes which he has proposed and then build the Signal app with it, and so if they could upload the APK, I will be willing to test it out to see if the issue has been fixed. 

But as I have tested the Jitsi Meet program and so it has fixed the issue, I would say that it would be appropriate if the signal team could implement such a change in Encoders through the use of a toggle in a settings tab for example. As suggested here: 

> > Is this fix going to be implemented into any future versions of signal so that this issue can finally be resolved in the end?
> 
> At least if we had some sort of switch in the settings for hardware/software encoding that would be nice (at least if that's the real problem signal is having).

**Comment by erik55** [comment]
I always have this problem with the **Samsung S6** (calling from S9). The image sent from the S6 freezes after rapid movements. Or sometimes without any obvious reason.

**Comment by haltman-at** [comment]
I've been having this issue as well -- or rather, I don't see the screen freeze, but the person I'm talking to does.

Debug log for me: https://debuglogs.org/aba40dd9c8e930fcaa07b91f5703c1cb95480097d611895809c05d789ece2121

Debug log for the person who sees the freezing: https://debuglogs.org/0f1b6f127b160323bc55ef903882b622c667de5a387913ad757ad95ae40dd9fc

**Comment by Tectract** [comment]
BUMP. This is a major, critical bug. Signal video freezes and is unusable on Android, as of January 2021.

**Comment by mehmetalianil** [comment]
This happens to me when the amount of change in the video streamed is high, when there is a jerky  motion, or when the camera is changed.

**Comment by erik55** [comment]
> This happens to me when the amount of change in the video streamed is high, when there is a jerky motion, or when the camera is changed.

The same happened to me when I used a Samsung S6 phone and the load was to high (video image changed a lot, of course changing camera was also like a big change of image). The problem disappeared with a newer phone, the Samsung S7. But I still have the problem, when other users don’t use the newest, most powerful phone.

Instead of freezing, video frames should just be dropped. And then continue with streaming video. For the moment it is always like: Please, don’t move to much. That is not nice for talking or showing things.

And this always happened when I had low bandwidth to the internet or varying connection quality (no connection loss, but bad wifi, many walls in between for example).

So, to reproduce: Use a Samsung S6, move a lot the camera, and not the best wifi. That together always led to a frozen image.

**Comment by cbkerr** [comment]
I also have this issue where the video of my chatpartner freezes on my device after chatpartner switches video from front to back camera. We are both on the latest Signal update from January.

My device:
SM-G955U1 (Samsung Galaxy S8+)

Chatpartner's device:
SM-J337AZ (Samsung Galaxy Amp Prime 3)
It's chipset is [apparently](https://www.phonemore.com/specs/samsung/galaxy-amp-prime-3/sm-j337az/), 64bit - Samsung Exynos 7 Quad 7570 (14nm) , in agreement with [the comment above](https://github.com/signalapp/Signal-Android/issues/8685#issuecomment-479362762).

I will update with debug logs when we have a chance to reproduce.

**Comment by reglos** [comment]
Same problem on a Samsung Galaxy S6 edge.
