### ISSUE TITLE
RAM useage > 1Gb (average) without google play services

### ISSUE THREAD

**Issue by svrouwenvelder** [signalapp/Signal-Android#9251]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
The Signal app uses more than 1Gb of RAM on my OnePlus 3 on average (currently it is using 1.3Gb)

### Steps to reproduce
0) Have a Oneplus 3 (A3003) 
1) flash NLOS 16 (Lineage OS derivative), see https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-nlos-16-0-t3879405
2) Do not flash google apps
3) Install signal via the apk on the website. 
4) check RAM consumption

Clean flash of this ROM makes no difference.

**Actual result:**  High RAM usage (>1 Gb)
**Expected result:** ~30 Mb (that's what my friend's mobile using google play services use, I expect slightly more RAM usage in my case.)

### Device info

**Device:** ONEPLUS A3003
**Android version:** 9
**Signal version:** 4.50.5

### Link to debug log
https://debuglogs.org/c64f04ba34f0874dcb5a26590477093a7fa5b1b269ef16adbe9d0b541875d8f0

**Comment by uiopc** [comment]
Hi,
I have the same problem running Signal 4.50.5 on GrapheneOS without Play Services. 
RAM consumption is very high and after one week I need to reboot the phone because everything is stuck.
Debuglogs are here: https://debuglogs.org/5905584d5b2973fbf35ab14fad2ac64b84c73bca2208f412382eca4a7d4013c9

Thanks for investigating this issue.

**Comment by svrouwenvelder** [comment]
On the signal website, the listed apk version to download is 4.50.5. Using the Aurora store (FOSS google play frontend) I downloaded and tried 4.51.6. Unfortunately right now my RAM consumption is 870Mb (still seems rather high)

https://debuglogs.org/a1ae95e1ac1c71af3d6ad6550f0b7d961c0df1e34ce21c10aeeafe56ccc3576c

**Comment by uiopc** [comment]
2 days later the RAM is almost exhausted.

https://debuglogs.org/296affda959ace425cea99e94987bfeed2c4e7e5a559708891c3a91b26ee51f9

**Comment by sucrecacao** [comment]
Have you folks check the integrity of the app ?

**Comment by Aang23** [comment]
Currently experiencing the same issue, with lower, but similar high RAM usage.
I'm running LineageOS 16.0 (GSI, custom build) on a Galaxy A3 2017 without any google services (nor OpenGapps nor MicroG).
Signal was installed from the site (through a F-Droid repo)
![Screenshot_20191225-113742_Settings](https://user-images.githubusercontent.com/23421917/71443581-01b5bd80-270c-11ea-9ab7-0d70f43bacd3.png)
![Screenshot_20191225-114038_Trebuchet](https://user-images.githubusercontent.com/23421917/71443582-01b5bd80-270c-11ea-8385-91dc30a92d97.png)

**Comment by 1337haXXor** [comment]
I've been having the same issue for a couple of weeks now. I don't have RAM numbers right now, as I just had to restart my phone again. I am running a stock OS with Google Play Services, but I have a LOT of things disabled via adb. Let me know if I can provide any more info. LG V40 on Sprint.

**Comment by EukalyptusX** [comment]
Maybe this is related:

https://github.com/signalapp/Signal-Android/issues/9240

**Comment by shivanju** [comment]
I have a Samsung Galaxy M10s, which has 3GB of RAM. It's running stock ROM whatever come preinstalled with phone. No rooting, no custom ROM. Even I am having the same issue(up to 1.4GB Ram usage in under 60hours). I have to clear the app manually. Honestly I couldn't find the reason myself but found this thread. I am posting here to increase this issue's visibility.

**Comment by uiopc** [comment]
It would be interesting to know if a developer has already looked at it. The bug is already present for a few months.

**Comment by greyson-signal** [comment]
Interesting. I'd be curious what types of things you're doing in Signal. For instance, if you're sending/recording a lot of video. There's not a ton of thing that we could do to shoot up our RAM usage.

But just in general, no one should need to be concerned about the RAM usage of any app on their phone. If you're using another app and it needs more memory, the system will evict Signal from memory if it feels like it needs to. You shouldn't be hitting performance problems.

**Comment by uiopc** [comment]
Hi, thanks for your reply. 
Well, my Signal usage basically only consists of writing "normal" messages. I send/receive one video per month on average and I do one voice call per month on average. But that's it.

Regarding the performance problems: Well, the situation is (at least with my phone) as I described it. Within one week after the last phone reboot the phone is stuck again and freezes because Signal uses all the RAM (and apparently doesn't release it).

**Comment by EukalyptusX** [comment]
I don't know for sure, but it happened to me now when I sent the same picture to more than one contact (about 3 contacts). Maybe this helps?

**Comment by uiopc** [comment]
I just spoke with some friends who have the same setup like me. Pixel 3a, GrapheneOS (no play services) and Signal website distribution build. All of them have the same problem with this high RAM usage. One of them already had 1,9 GB RAM usage 33 hours since the process started.


![Screenshot_20200220-205836](https://user-images.githubusercontent.com/16373631/74974862-4917ac00-5426-11ea-8c27-55f6da2cc35b.png)
![signal-2020-02-20-205845](https://user-images.githubusercontent.com/16373631/74974866-4a48d900-5426-11ea-86da-fff19159252c.png)

**Comment by christianfl** [comment]
Same problem with Pixel 2, GrapheneOS without Play Services with 4.58.5 from Play Store Beta Channel.

![Screenshot_20200408-150019](https://user-images.githubusercontent.com/11208965/78787849-40b20b00-79ab-11ea-97bb-568c07f1e86c.png)

RAM is often nearly full (4GB in total), swapping doesn't really work @greyson-signal , e.g. Fennec can most of the time only hold one or two tabs active. This was definetely better before installing Signal.

Total used disk space of Signal is 206,1MB. Using it everyday, mostly sending messages and sometimes send and receive images. What can we do to help with this issue? It is really critical in my opinion.

**Comment by EukalyptusX** [comment]
I also think, that this issue is getting worse. I have to force kill the app every few hours.
We really need to fix this asap.
Anything we can do?

**Comment by uiopc** [comment]
I'm wondering why the signal-devs don't encounter the same problem as well. For sure they must have some test devices without play services installed.
I talked to 5 people now which have this setup (AOSP-based ROM, no play services, signal website build) and all of them need to kill signal / reboot phone every few days because of this bug.
If we can help with more information to debug, please let us know.

**Comment by EukalyptusX** [comment]
https://github.com/signalapp/Signal-Android/pull/9221

Possible fix?

**Comment by uiopc** [comment]
> But just in general, no one should need to be concerned about the RAM usage of any app on their phone. If you're using another app and it needs more memory, the system will evict Signal from memory if it feels like it needs to. You shouldn't be hitting performance problems.

Doesn't seem so....

![Screenshot_20200429-133315](https://user-images.githubusercontent.com/16373631/80592873-74b7a380-8a20-11ea-9b8c-20ded5afd01f.png)

**Comment by uiopc** [comment]
but nobody cares anyway...

**Comment by EukalyptusX** [comment]
Ok wow.
It's really annoying to force kill Signal every few days. Can a developer get into this, PLEASE?
Really don't want to switch back to WhatsSh*t...

**Comment by EukalyptusX** [comment]
I have a workaround for the next 2 years, until it gets fixed, but you need root access.

Install the FOSS-App "Easer". Create a profile and run these 3 seperate commands:

```
am force-stop org.thoughtcrime.securesms

am start -n org.thoughtcrime.securesms/org.thoughtcrime.securesms.MainActivity

input keyevent 3
```

Ensure that you enabled root in the Easer settings. I run this profile every 2 hours. Hope it helps someone.

**Comment by EukalyptusX** [comment]
Tried again... but... Serious? Average 1.8 GB RAM usage...

![Screenshot_20200606-231124_Einstellungen](https://user-images.githubusercontent.com/42608576/83954695-aefc3800-a84b-11ea-8801-0a97e57961ec.png)

**Comment by EukalyptusX** [comment]
> #9221
> 
> Possible fix?

FYI:
I just forked Signal and merged that PR. This does not fix the problem - it just takes longer until it starts lagging. So, I guess it's related to missing Play Services.

**Comment by shivanju** [comment]
> I just forked Signal and merged that PR. This does not fix the problem - it just takes longer until it starts lagging. So, I guess it's related to missing Play Services.

I was having the same problem with my stock/non-rooted Galaxy M10s. I've play services installed.
My previous comment ITT: https://github.com/signalapp/Signal-Android/issues/9251#issuecomment-574233720

**Comment by mottsauce523** [comment]
I've worked extensively on Android devices without Play Services, so I am going to have a look at this. I have some ideas...

**Comment by mottsauce523** [comment]
There's really only one thing in the Signal-Android codebase I've found that is related to Play Services - the UpdateApkRefreshListener and UpdateApkJob. I wonder if something isn't cleaned up after the periodic job runs - based on a quick look-over, it runs every six hours. Seems like the kind of thing that would cause a problem over a period of several days.

I'll let it run overnight and see what the memory profile has to say.

**Comment by mottsauce523** [comment]
We're back! And, uh, my Android Studio is pretty sluggish this morning.

This memory profile is...not good. Memory usage roughly doubled from 64MB to about 128MB overnight, which is definitely not what you want to see. I started this test around midnight, and am revisiting at approximately 10AM.

Methodology: Apart from modifying gradle versions, I made a single modification to the webDebug build variant. I modified the UpdateApkJob to run every few minutes instead of every six hours, and, well...

![image](https://user-images.githubusercontent.com/67131477/85227304-a0189800-b3aa-11ea-8269-0f7809d6e0c0.png)

In order to confirm this theory is true and that I didn't mess something up, I am going to modify the code again so the UpdateApkJob does not run *at all* for a day.

**Comment by mottsauce523** [comment]
I will note, however, that this effectively squeezes multiple days' work of ApkUpdates into a night, and this test did not show the enormous consumption of memory that others have seen. That being said, this is an emulator and not a true device, and the memory settings are of course different, etc. etc. Just to temper expectations.

**Comment by mottsauce523** [comment]
So...I ran this all day today, and yet again my emulator was brought to its knees.

@greyson-signal, I see you added FrameRateTracker in early December. This ArrayList capturing the FPS data becomes quite large when I'm running this thing all day. I don't know if this is an emulator-only deal or something that is also on prod, but could you comment on whether or not it needs to be capped or fixed? Not sure what your intent here was.

![mottsauce523_SignalEmulatorAndroid_FullDay](https://user-images.githubusercontent.com/67131477/85479340-f7c22980-b58b-11ea-92e4-90c35087546f.PNG)

**Comment by mottsauce523** [comment]
Ran the emulator again overnight.

I decreased the size of LRUCache from 1000 to 100, and turned off FrameRateTracker, and the issue appears to be all fixed.

![SignalEmulator_overnight_noFrameTracker](https://user-images.githubusercontent.com/67131477/85554599-127bb900-b5f3-11ea-8fce-f41b9eac487f.PNG)

Really, I think FrameRateTracker is the culprit here - the LRUCache just caches the last 1000 "Jobs", which shouldn't be a problem under normal operation. I misinterpreted its purpose before.

@EukalyptusX - if you have the ability to make your own builds, could you give me a hand and test out a fix on your HW? I have google play on my pixel2, and I don't want to toss up a commit for something that's only been tested in an emulator.

All you should have to do is comment out
ApplicationDependencies.getFrameRateTracker().begin();
and
ApplicationDependencies.getFrameRateTracker().end();

within ApplicationContext.java.

**Comment by EukalyptusX** [comment]
Thank you so much for your help!
I'll build this asap - hopefully tonight. I'll let you know.

**Comment by EukalyptusX** [comment]
Ok, just finished the build. I'll report back asap (until weekend I guess).

**Comment by EukalyptusX** [comment]
![Screenshot_20200625-105317_Einstellungen](https://user-images.githubusercontent.com/42608576/85688640-35c96580-b6d2-11ea-9e7c-b22f407d76c4.png)

I can confirm, this works!! Usually I'd already have about 500MB RAM used by Signal. Max. is now definetly lower!

Thank you so much!

**Comment by EukalyptusX** [comment]
Lol...Now it says it didn't use ANY ram in the last 3 hours 😂 Is that even possible?
![Screenshot_20200625-140321_Einstellungen](https://user-images.githubusercontent.com/42608576/85717243-974afd80-b6ed-11ea-81f2-09061c78f5c7.png)

**Comment by mottsauce523** [comment]
Glad to hear it! Do you keep signal active all the time? In the background all the time? Or do you close it when you are not using it?

**Comment by EukalyptusX** [comment]
> Glad to hear it! Do you keep signal active all the time? In the background all the time? Or do you close it when you are not using it?

Yes, it's always active - I can see the Signal icon in the taskbar, too (see attached screenshot). I also get notifications. I'm not closing the app. I just press the menu button.

![Screenshot_20200625-151440_Fennec_F-Droid](https://user-images.githubusercontent.com/42608576/85726684-9d91a780-b6f6-11ea-822d-3c81df3af120.png)

**Comment by mottsauce523** [comment]
Okay, that is helpful!

Basically the problem is that the FrameRateTracker adds the framerate once per second to an arraylist, and that arraylist has no upper bound. It really needs to be a data structure with a max size. I will revisit when I have time early next week - but regardless this needs @greyson-signal to weigh in since it's his code. I think the purpose was to make performance issues easier to spot, since framerate drops could easily be correlated with logs.

I'm sure you see the irony.

**Comment by mottsauce523** [comment]
Potentially resolved by @alan-signal at 3741493cb733eb8bfbe944a8a195ddaf596e259b. Thanks Alan (maybe!)!

**Comment by mottsauce523** [comment]
Thanks Greyson, much appreciated!

**Comment by uiopc** [comment]
Thanks everybody. RAM consumption got much better. Phone is running for a week now without rebooting, and Signal only consumes 870 MB.

**Comment by EukalyptusX** [comment]
Back again... Great.... not... 


![Screenshot_20200820-111802_Einstellungen](https://user-images.githubusercontent.com/42608576/90754780-a0fe7500-e2da-11ea-8f51-1366793a4ecb.png)

**Comment by EukalyptusX** [comment]
That's not even funny...
The issue still exists. Gonna fork again with this "analytics" stuff deactivated.

Guys PLEASE fix this issue which is open for almost a year!!!

**Comment by EukalyptusX** [comment]
![Screenshot_20201215-133329_Einstellungen](https://user-images.githubusercontent.com/42608576/102218165-dd835b80-3edd-11eb-9a04-5d6cbff6d6e6.png)

Tested again. Issue still exists.
Wow.

**Comment by EukalyptusX** [comment]
![Uploading Screenshot_20210114-140602_Einstellungen.png…]()

4.7GB max ram usage. I won't let you rest until it's fixed...

**Comment by EukalyptusX** [comment]
![Screenshot_20210114-140602_Einstellungen](https://user-images.githubusercontent.com/42608576/104594940-2b70b800-5672-11eb-8b52-e9715b136258.png)

4.7GB max ram usage. I won't let you rest until it's fixed...

**Comment by EukalyptusX** [comment]
![Screenshot_20210115-091813_Einstellungen](https://user-images.githubusercontent.com/42608576/104699487-1a2bb800-5713-11eb-961e-b33f50ede69a.png)

Just a funny picture for the weekend. 7,1GB max ram usage by Signal.
I think that's a new record.

**Comment by EukalyptusX** [comment]
![Screenshot_20220128-193455](https://user-images.githubusercontent.com/42608576/151602824-82e1b207-ac60-4c62-91e8-3070c7f70793.png)

Seriously???

**Comment by EukalyptusX** [comment]
Still not fixed.

**Comment by alex-signal** [comment]
The best way to help us fix an issue like this is to analyze a heap dump after you hit a high amount of ram usage. I'm not going to ask anyone to submit that, because it'd contain any data that is in-memory at the time. However, I do indeed have a bunch of random devices around so I'll see what I can do about installing a non-gps brand of android on one of them.

**Comment by Aang23** [comment]
It does appear signal "only" uses ~500MB on my phone nowadays. Still more than I would expect... But I can live with that. (Though, I wouldn't personally call it fixed)

If that helps, Element (Matrix client) also has a very similar issue without Google Play Services, where RAM Usage can go well above 1GB in exactly the same way as Signal.

**Comment by ristein** [comment]
![Screenshot_20230712-184410_Settings](https://github.com/signalapp/Signal-Android/assets/55446611/1a8d88c3-2b88-4811-94f5-1e264a1a783b)
