### ISSUE TITLE
Echo cancellation doesn't work on Nokia 7.2

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#9817]
When in a Signal call with loudspeaker on, the other side can hear itself. 

**Phone**
Model: Nokia 7.2
Android version: 10
Signal version: 4.64.7

**Comment by ozgurakyazi** [comment]
If they really do sth about this, I will also create another issue for Xiaomi Redmi Note 7.
Waiting for #9351, for months...

**Comment by blokeley** [comment]
Every person I call using Signal gets an echo of themselves. I don't though.

My phone: Nokia 8 Sirocco running Android 10.

Example phones at their end:
 * Samsung Galaxy A5 I think running Android 10
 * iPhone 8 I think

**Comment by PrSunflower** [comment]
Same problem for me. I never hear myself but the other side can hear themselves.

**Phone:** Nokia 7.2
**OS:** Android 10
**Signal version:** 4.73.4 but I've had the issue on previous versions too.

### Smartphones of my correspondents

- Xiaomi, Honor, iPhone X.

The Xiaomi and Honor owners have already called themselves, everything is fine.

### Testing with earphones, earpiece and different volume levels

When I am on loudspeaker my correspondent hears themselves but as soon as I plug in my earphones (with an integrated microphone) or use the earpiece everything is fine.
I have also tried lowering my loudspeaker's volume, the other side can still hear themselves but less louder.

These tests may confirm that the phone's microphone is picking up sound from the speakers.

### Testing with other apps

I called the same correspondents on WhatsApp and Messenger, everything is fine.

It would be very nice if this issue can be fixed as soon as possible. Signal is pretty stable and this problem is the only major bug I have.

### Which microphone does Signal use?

I just thought of this but the Nokia 7.2 has 2 microphones. Could Signal activate both so that's why the echo cancellation doesn't work?
How can I test which microphone is activated during a call?

**Comment by marfrh** [comment]
I can confirm this issue for Nokia 7.2 (Stock Android) and Signal 5.08. (and older Signal versions):

Person A calls Person B (with Nokia 7.2) -> Person A hears an annoying loud echo of his own voice as long as Person B uses loudspeakers.

**Comment by PrSunflower** [comment]
Hi everyone,

I have noticed this week that the issue is solved with my Nokia 7.2. I have called my contacts as normal, turned on the speaker at 100% volume and they did not hear their own voice. Echo cancellation seems to work fine now 😄

I don't exactly know the version that solved the problem but I am currently using **5.3.7.1**. Cheers!
<br> (@EmilVogt thanks for having opened the issue. If you could close it now ☺)

**Comment by ozgurakyazi** [comment]
I think we should check the commits for this. When I see the issue on other phones, it sometimes disappear and appear again. 

My gut feeling is that: randomly(!, no idea how) you dont see this issue and there is no work done for this. If there were, I believe we would see some comments from developers. 

Can you please write back here, if you experience the issue again?

**Comment by PrSunflower** [comment]
@ozgurakyazi Oh right, I haven't checked everything but indeed nobody wrote about solving this problem.

I don't understand the concept of Pull Requests yet, how can I check if this potential fix has been implemented somewhere in the code? https://github.com/signalapp/Signal-Android/pull/10420

**Comment by juhaj** [comment]
@PrSunflower I have a Nokia 7.2, everything up-to-date (Android 10, signal 5.3.7.1), but still have the echo problem.
There seem to be at least three issues open for this issue, so if this is not the right one to comment on, please direct me to the one that is.

**Comment by juhaj** [comment]
I did some testing on this and
1. echo does not appear when headphones are plugged in 
1. echo does not appear when not on "speaker phone"
2. echo does appear when "on speaker".

So I'd guess echo cancellation is simply totally disabled/off in signal because disabling speaker phone mode avoids the echo.
Curiously, video call forces speaker phone mode (I can understand why: who'd want to watch someone's ear?). This is probably intentional feature, and it switches to headset when that plugged in, but still does not allow switching between the outputs. Is this, too, intentional? Switching between speaker-phone and headset could be useful in some circumstances and still not force the other party to watch the ear canal.

**Comment by PrSunflower** [comment]
@juhaj Hi, thanks for replying. Oh wow if so I'm really surprised that mine works well. I have just updated to **Signal 5.3.12** and everything is still fine.

I would say that this is the right issue to write on, because it's the oldest describing the echo problem for Nokia 7.2.

About the testing, [my results](https://github.com/signalapp/Signal-Android/issues/9817#issuecomment-714640253) are similar to yours. 

Concerning the sound outputs, this is unrelated to this issue but I would say that it is not unusual. In most situations if you don't want to use your earphones you can just unplug them, no need for a button to switch outputs. But if you don't agree with me and would like to propose a new feature, you can go on and create a new issue 🙂

**Comment by juhaj** [comment]
Thanks @PrSunflower. I think for consistency's sake keeping the button would be nice, but as I cannot see any use for watching someone's ear canal, and the plug/unplug is easier than the button (and necessary anyway), you're probably right about it. I don't have a BT headset, but how does that behave? Does it get used by video calls without ability to switch to speaker (apart from turning the headset off)?

**Comment by PrSunflower** [comment]
Hi again @juhaj . I don't have a Bluetooth headset myself. 

In this issue we talk about the echo cancellation problem of the Nokia 7.2. If you are generally curious and have questions about how to use Signal, I would suggest you take a look at the Signal community website: https://community.signalusers.org/

Let's keep this conversation focused 🙂

**Comment by PrSunflower** [comment]
Hello everyone, hope you're all well.

Since this issue disappeared on my phone ~1 month ago it hasn't come back. I am still able to call my contacts with loudspeaker at full volume and they don't hear their echo, everything is fine. 

I am using Signal 5.4.7 (with Nokia 7.2 on Android 10), that's strange if some of you are using the same as I do and your contacts still hear their echo 🤔

Can some people confirm that they are using the same as I do but still have the echo problem? <br>
(Precision : I am using regular Signal from the Play Store, not part of the Beta program or anything)

**Comment by marfrh** [comment]
For me the problem also seems to have disappeared.

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
