### ISSUE TITLE
Error downloading MMS message when a group message is received. 

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#9836]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive messages in an MMS group chat, I _also_ see an erroneous message from the sender in a one-to-one MMS message.

_Error downloading MMS message, tap to retry_

Using Signal as default SMS app. 
Delivery reports enabled. 
Wifi calling disabled.

Generally default settings; I don't recall playing with them.

### Steps to reproduce
- recieve a MMS intended for multiple people
- look at any of those contacts on their own
- these messages are even interspersed with encrypted conversations

**Actual result:** I am notified twice and have tons  of garbage messages that take up a lot of space.
**Expected result:** I only receive the message in the group chat.

### Screenshots
![signal-2020-07-09-193222](https://user-images.githubusercontent.com/6789641/87097172-f5fa9600-c21a-11ea-948f-2010865a0ddf.jpeg)

### Device info

**Device:** Samsung Galaxy Note 9
**Android version:** 10 (just says 10) Kernel version 4.9.186-18249188
**Signal version:** 4.65.2

### Link to debug log

https://debuglogs.org/58526f75dc96fd45c22619d510fc17a5e069150a45bb79c5456336a1f5d83ea8

**Comment by jwhendy** [comment]
I'm going to post here, but can open a new thread if that is desired.
- samsung s8
- signal 4.70.5
- android 9, kernel 4.4.153-17214672

Everything _was_ working fine until the past few days. I have a group chat with my brother and dad (non-signal) and we've been sending plenty of pictures and text messages back and forth for months.

Starting a couple days ago, I started getting MMS messages in my _individual_ text threads with both my brother and dad. They could not be downloaded (just like the above). I asked my brother if he was trying to send pics, and he said only to our group thread.

It appears texts meant for the group chat are trying to come through the individual thread but subsequently forever are undownloadable.

Happy to provide additional information or try troubleshooting steps as advised.

Here is my [debug log](https://debuglogs.org/353395870bed01ceadbed902ee1c96a8410debc1dbbe7cb4a566585df9b34829).

**Comment by Kage1** [comment]
Seems like this issue is back after it was solved in an earlier issue request, #9173. I'm having the same issue again as the others. I'm on a AT&T MVNO. I am using beta version 4.72.2, sent a feedback note with debug log.

**Comment by jwhendy** [comment]
Update to my situation: I'm on a shared plan, and the plan owner said he was experiencing issues as well. He called Sprint, our provider, and was told there were known issues with Samsung devices as of the last update. For reference, I'm on:

`G950USQU8DTI3 / G950UOYN8DTI3 / G950USQU8DTI3`

He was told by Sprint that there is an ongoing issue downloading messages over wifi. I can confirm that my phone more or less worked itself out when I turned off wifi and then re-tried downloaded pending MMS messages.

Lastly, for what it's worth, the agent provided the following steps that may or may not do anything (we both did it, but could be easily be like drinking snake oil on the eve of a harvest moon while standing on one leg).
```
- airplane mode
- leave it in airplane for 30 seconds
- take out of airplane mode and let it sit for 2 minutes
- power phone completely off for 30 seconds
- power up and unlock immediately and let sit for 5 minutes
- ##72786# and let it sit for 5 minutes
```

This doesn't align with @Kage1 (AT&T and unsure of device), but might pertain to OP.

**Comment by grravity** [comment]
Having this issue as well
- lgv40
- signal
- android 10

**Comment by Kage1** [comment]
Has anyone tried to enable the WiFi  Calling compatibility mode? While I don't have wifi calling enabled it has fixed most of the MMS issues on my device.

**Comment by grravity** [comment]
I have wifi calling enabled, I'll try disabling it however

**Comment by BeAnonymousTech** [comment]
I am also experiencing the error shown but the MMS is not sent in the group chat thread either. So only the error in the single recipient thread of the person that sent the message to the group chat, even if they sent a simple text message. In my case this only happens when the "Signal messages and calls" setting is disabled in Setting > Advanced

**Comment by richid** [comment]
Chiming in with my info here:

- Pixel 2
- T-Mobile (BYOD)
- Signal 
- Android 11, Kernel 4.4.223

I've tried everything I can find: toggling airplane, toggling wifi, restarting phone, resetting APN configuration, WiFi calling compatibility and I cannot get it to download some group MMS messages. I've been a dedicated user since the first couple releases of TextSecure but I am losing important family messages, so I had to revert back and make the bundled Messages app the default for SMS. It's a shame, but thanks for all the hard work.

**Comment by grravity** [comment]
Out of curiousity, does anyone have trouble with this but just with users who have iPhones?
I could be wrong, but it seems like whenever I get a MMS message over SMS/MMS from an iPhone user, it fails. As does being in group chats with them.

However when chatting with Android users over SMS/MMS, it seems like it's fine.

This could be a coincidence, I rarely group chat however in independent messages I can receieve from iPhone users no issues, but group chats always have this issue.

Was just curious, maybe it's related to iOS sending some flag when not talking to other iMessage users and Signal fails to read it properly.

**Comment by jwhendy** [comment]
@grravity I'd never paid attention before, but literally just had the opportunity to do so. Sent a pic to a group chat between my family and another and it wouldn't send until I went off wifi, going back on wifi to connect to my NAS. I just got a reply from a known android user which showed up as an MMS in our individual thread, then showed up in the group chat after I turned off wifi and re-downloaded once it failed.

**Comment by grravity** [comment]
Interesting

**Comment by jen615** [comment]
Having the same issue:

Samsung Note 9 (SM-N960U)
Signal 5.5.5
Android 10, Kernel 4.9.186-19871035
T Mobile
Wi-Fi calling enabled

**Comment by jen615** [comment]
And to add: most of the time the failed messages are just duplicates but sometimes retrying the download actually adds new messages to the group message. For me it's mostly a wi-fi issue, and I've experienced this in a group chat with android and iPhone users

**Comment by jerryyhom** [comment]
I want to add my experiences.

Almost a month ago, I switched services, from AT&T to T-Mobile, and upgraded phone, from LG Stylo 5 to LG Stylo 6, both Android 10.  I use wifi calling and have "WiFi Calling" compatibility mode enabled.  On AT&T, receiving MMS messages in group chats, with both Signal and non-Signal users, was mostly successful.  On rare occasion, I would get the error downloading MMS message.

Now on T-Mobile, the success/failure rate has flipped.  I tested turning off WiFi, using cellular connection only, and receiving MMS messages seemed fine.  Then I tested turning on WiFI but disabling "WiFi Calling" compatibility mode, and receiving still seems fine.  T-Mobile's wifi calling seems uniquely different, and the compatibility mode needs a special case for T-Mobile.

**Comment by grravity** [comment]
Tmobile user myself, I can't recall if I had similar issues on Verizon but I want to say for the most part no.
Sounds like this is either a Tmobile issue, or an issue with iOS users being in the group chat (or both)

**Comment by jwhendy** [comment]
@grravity 

> Sounds like this is either a Tmobile issue, or an issue with iOS users being in the group chat (or both)

I'm on Sprint (though I don't recall if it was happening before the Tmobile merge), this happens to me on wifi in one-on-one texts with pics as well (both sending and receiving), and has also happened to me in group chats from android users (though I think one member was iPhone).

I just set up a 3 person group of android users now specifically to try this and I still get it. Message comes in like a failed MMS to my individual chat with the sender, retrying fails, I turn off wifi and it shows up in the group. I get that this issue is about groups, but I want to re-itreate that this is not exclusive to groups for me. I would generalize to MMS while on wifi. Also, I have LTE calling on, but not wifi calling (counter to @jerryyhom 's experience).

**Comment by jerryyhom** [comment]
I think I have figured out my particular issue with receiving MMS.  Hopefully my experiences might help others.  The summary is, configure your APN for your network.

My service provider is actually Metro, a subsidiary of T-Mobile.  I had assumed I was on T-Mobile's network, but Metro operates their own network.  Unfortunately, Metro's coverage is spotty where I am.  However, I am allowed to access T-Mobile's network by configuring an APN.  The confusing part is, I thought service providers have roaming agreements such that phones can access any network, automatically, and just work, but no?

Okay, so I configure APN for T-Mobile but discover that my connection bandwidth is slow, as though my data is classified as second class.  I tested a T-Mobile device and saw what first class bandwidth looks like.  Grrrr...

Then I properly configure the APN for Metro, and connection bandwidth is much better.  But the spotty coverage means that my phone may switch APN between Metro and T-Mobile.  Whenever a switch occurs, network routes must be updated; that is, any MMS messages in flight are lost until my phone's network route is registered.  This was my epiphany because I had been losing MMS messages seemingly at random.  I kept trying several different configurations, but a working configuration would somehow fail again.  Grrrr, I have great sympathy for those who debug networks.

So my dilemma is how to configure APNs?  Is there a way to get the higher bandwidth of Metro's network when available, backed by the more reliable coverage of T-Mobile's network, or perhaps just with MMS?  I have found very little information about configuring APNs.  Can anyone shed light on this topic?

**Comment by seniorm0ment** [comment]
Personally I'm not using Metro, but am using T-Mobile.
I have tried messing with the APN in the past with no success, everything is as specified by T-Mobile.

Also despite my previous ideas of it possibly being related to iMessage, I've been having trouble with Android users the past few weeks.
This is honestly a very frustrating issue, and it would be nice to have some developers comment, or give any ideas or even a it's being looked into. It's clearly a fairly widespread issus.

**Comment by jerryyhom** [comment]
Just to clarify, I think the widespread error in receiving MMS (ERROR) has many possible causes.  In my case, the cause is essentially poor cellular coverage, possibly poor APN configuration, and most likely not due to Signal.  I should verify this 100% by using Android's default Messenging app, but I think I have tested enough configurations to feel confident about my situation.

Re: ERROR caused by iOS
I experienced the ERROR from both iOS and Android users, and both Signal and non-Signal users.  I wonder about the situation where a group chat uses Signal exclusively.  I believe those messages would use Signal's protocol, instead of MMS, and be routed via Signal instead of the service providers' MMSC.  In my case, Signal would be a buffer against changing network routes.

@seniorm0ment - I share your frustration ever since switching service providers about two months ago.  I have wasted hours in debugging my issue.  Many others have experienced this same ERROR, and I actually hesitated to add my comments, which just seems to add burden to the considerable existing burden (ie, 1.2k issues).  I am sure the developers are busy; I am busy.  A developer could comment, but that would take away precious time for an issue with many possible causes.  I wish more info was easily available online (eg, APN, MMS, roaming); I would gladly read them.  I am still researching the issue and, in sharing at least one thing I learned during my debugging process, hopefully it helps some users and maybe reduces the burden.

**Comment by seniorm0ment** [comment]
I do not believe it is related to poor cellular coverage, as I am in generally very good coverage area 24/7, and the APN configuration is directly based off T-Mobiles recommendations. 
As for a situation where a group chat uses Signal exclusively, I have never noticed issues. It's only when working with MMS.

**Comment by brokenalarms** [comment]
I just fixed this myself on my Android device, see comment here: https://github.com/signalapp/Signal-Android/issues/9490#issuecomment-958591984

**Comment by jwhendy** [comment]
Every few months I've looked at the mess of issues that are sort of similar to this. I finally just used developer settings to toggle "mobile data always on" and now things work.

I gave up and @stale, I've not seen anyone that I recognize as officially signal troubleshooting the many clones of this issue. It's been hugely frustrating though, and super nebulous to dig into and understand, which is why I personally think it's blocked (need someone with signal internal knowledge to suggest what to even look for/check/etc.).

The amount of black magic in all the "fixes" is a ridiculous burden on each user to try.

**Comment by brokenalarms** [comment]
Definitely still active, been going on for years, see no fix, have since left signal specifically due to this, it makes talking in iPhone group chats where everything is sent as an SMS unworkable.

**Comment by richid** [comment]
Not trying to pile on, but...yeah this is still an issue. After a lot of frustration I've resigned myself to using the default Messages app for vanilla SMS rather than Signal.

**Comment by seniorm0ment** [comment]
Can confirm relevant

**Comment by PhilomathJ** [comment]
I am just now troubleshooting this on my Android (12) S2. I did find that if I turn off wifi and stay just on cellular that this behavior goes away entirely. Clearly this is not fix, but hopefully will help to diagnose the root cause

**Comment by jwhendy** [comment]
@PhilomathJ indeed, wifi vs. cell behavior is mentioned many times above. Examples:

> I can confirm that my phone more or less worked itself out when I turned off wifi and then re-tried downloading pending MMS messages.

> Sent a pic to a group chat between my family and another and it wouldn't send until I went off wifi

>  Message comes in like a failed MMS to my individual chat with the sender, retrying fails, I turn off wifi and it shows up in the group.

> I tested turning off WiFi, using cellular connection only, and receiving MMS messages seemed fine.

**Comment by jwhendy** [comment]
No, thank _you_ @stale for your kind reminders to periodically recall that this long standing issue is still an issue. Does anyone here know what it would take to get attention or simply assistance on how to troubleshoot further? I'm a techie, but don't know android or how I would go about pinpointing the cause of this... is there anyone from the Signal team interested in helping us to resolve this?

**Comment by Viss** [comment]
I am also having this issue.
All inbound texts to an SMS group where not everyone is using signal result in this behavior. The sms message arrives from the person directly as an 'MMS error', then when I press the download button in the center of the error, the sms message 'arrives' and is correctly deposited into the proper sms group.
Android 12
Oneplus 7 pro
I'm on the signal beta code out of google play

**Comment by Viss** [comment]
I am happy to do debug logs or perform troubleshooting if any of the signal staff can point me in the right direction. Best I can tell without going under the hood is that it's some kind of parsing problem. Regular sms messages come in just fine, but this only happens when someone not using signal sends a message to a group where people are using signal.

**Comment by alex-signal** [comment]
@Viss Debug logs are always a wonderful first step! Unfortunately MMS is... a terrible and overly complex protocol. But hopefully the debug logs can spread some insight.

**Comment by LutzHeinrichs** [comment]
I have this issue as well, exactly as OP describes.

Samsung S21 Ultra
Latest updates to OS
T-Mobile plan I've had for >10 years
Signal version 5.41.10

This issue was not always present. I want to say it started right around when OP posted, it's been a while. But before then, group chats worked perfectly fine.
I am mostly on Wi-Fi but I have that problem on the road, without Wi-Fi, as well.
I'll look for instructions to submit any debug logs.

**Comment by gabefair** [comment]
This issue can be closed because MMS and SMS are no longer supported in Signal
